package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AAcctfiscal generated by hbm2java
 */
@Entity
@Table(name = "A_ACCTFISCAL")
public class AAcctfiscal implements java.io.Serializable {

	private AAcctfiscalId id;

	public AAcctfiscal() {
	}

	public AAcctfiscal(AAcctfiscalId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "acctfiscal", column = @Column(name = "ACCTFISCAL", precision = 22, scale = 0)) })
	public AAcctfiscalId getId() {
		return this.id;
	}

	public void setId(AAcctfiscalId id) {
		this.id = id;
	}

}
