package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AAcctfiscalId generated by hbm2java
 */
@Embeddable
public class AAcctfiscalId implements java.io.Serializable {

	private String ctrMatfis;
	private BigDecimal critid;
	private BigDecimal acctfiscal;

	public AAcctfiscalId() {
	}

	public AAcctfiscalId(String ctrMatfis, BigDecimal critid, BigDecimal acctfiscal) {
		this.ctrMatfis = ctrMatfis;
		this.critid = critid;
		this.acctfiscal = acctfiscal;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "ACCTFISCAL", precision = 22, scale = 0)
	public BigDecimal getAcctfiscal() {
		return this.acctfiscal;
	}

	public void setAcctfiscal(BigDecimal acctfiscal) {
		this.acctfiscal = acctfiscal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AAcctfiscalId))
			return false;
		AAcctfiscalId castOther = (AAcctfiscalId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getAcctfiscal() == castOther.getAcctfiscal())
						|| (this.getAcctfiscal() != null && castOther.getAcctfiscal() != null
								&& this.getAcctfiscal().equals(castOther.getAcctfiscal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getAcctfiscal() == null ? 0 : this.getAcctfiscal().hashCode());
		return result;
	}

}
