package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AAdvtotaltoId generated by hbm2java
 */
@Embeddable
public class AAdvtotaltoId implements java.io.Serializable {

	private String ctrMatfis;
	private BigDecimal critid;
	private BigDecimal taxadv;
	private BigDecimal cafttc;
	private BigDecimal advtotaltorate;
	private BigDecimal decok;

	public AAdvtotaltoId() {
	}

	public AAdvtotaltoId(String ctrMatfis, BigDecimal critid, BigDecimal taxadv, BigDecimal cafttc,
			BigDecimal advtotaltorate, BigDecimal decok) {
		this.ctrMatfis = ctrMatfis;
		this.critid = critid;
		this.taxadv = taxadv;
		this.cafttc = cafttc;
		this.advtotaltorate = advtotaltorate;
		this.decok = decok;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "TAXADV", precision = 22, scale = 0)
	public BigDecimal getTaxadv() {
		return this.taxadv;
	}

	public void setTaxadv(BigDecimal taxadv) {
		this.taxadv = taxadv;
	}

	@Column(name = "CAFTTC", precision = 22, scale = 0)
	public BigDecimal getCafttc() {
		return this.cafttc;
	}

	public void setCafttc(BigDecimal cafttc) {
		this.cafttc = cafttc;
	}

	@Column(name = "ADVTOTALTORATE", precision = 22, scale = 0)
	public BigDecimal getAdvtotaltorate() {
		return this.advtotaltorate;
	}

	public void setAdvtotaltorate(BigDecimal advtotaltorate) {
		this.advtotaltorate = advtotaltorate;
	}

	@Column(name = "DECOK", precision = 22, scale = 0)
	public BigDecimal getDecok() {
		return this.decok;
	}

	public void setDecok(BigDecimal decok) {
		this.decok = decok;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AAdvtotaltoId))
			return false;
		AAdvtotaltoId castOther = (AAdvtotaltoId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getTaxadv() == castOther.getTaxadv()) || (this.getTaxadv() != null
						&& castOther.getTaxadv() != null && this.getTaxadv().equals(castOther.getTaxadv())))
				&& ((this.getCafttc() == castOther.getCafttc()) || (this.getCafttc() != null
						&& castOther.getCafttc() != null && this.getCafttc().equals(castOther.getCafttc())))
				&& ((this.getAdvtotaltorate() == castOther.getAdvtotaltorate())
						|| (this.getAdvtotaltorate() != null && castOther.getAdvtotaltorate() != null
								&& this.getAdvtotaltorate().equals(castOther.getAdvtotaltorate())))
				&& ((this.getDecok() == castOther.getDecok()) || (this.getDecok() != null
						&& castOther.getDecok() != null && this.getDecok().equals(castOther.getDecok())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getTaxadv() == null ? 0 : this.getTaxadv().hashCode());
		result = 37 * result + (getCafttc() == null ? 0 : this.getCafttc().hashCode());
		result = 37 * result + (getAdvtotaltorate() == null ? 0 : this.getAdvtotaltorate().hashCode());
		result = 37 * result + (getDecok() == null ? 0 : this.getDecok().hashCode());
		return result;
	}

}
