package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AAdvtotalto generated by hbm2java
 */
@Entity
@Table(name = "A_ADVTOTALTO")
public class AAdvtotalto implements java.io.Serializable {

	private AAdvtotaltoId id;

	public AAdvtotalto() {
	}

	public AAdvtotalto(AAdvtotaltoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "taxadv", column = @Column(name = "TAXADV", precision = 22, scale = 0)),
			@AttributeOverride(name = "cafttc", column = @Column(name = "CAFTTC", precision = 22, scale = 0)),
			@AttributeOverride(name = "advtotaltorate", column = @Column(name = "ADVTOTALTORATE", precision = 22, scale = 0)),
			@AttributeOverride(name = "decok", column = @Column(name = "DECOK", precision = 22, scale = 0)) })
	public AAdvtotaltoId getId() {
		return this.id;
	}

	public void setId(AAdvtotaltoId id) {
		this.id = id;
	}

}
