package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ACaftotclId generated by hbm2java
 */
@Embeddable
public class ACaftotclId implements java.io.Serializable {

	private String ctrMatfis;
	private BigDecimal critid;
	private BigDecimal assettcl;
	private BigDecimal cafttc;
	private BigDecimal caftclrate;

	public ACaftotclId() {
	}

	public ACaftotclId(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	public ACaftotclId(String ctrMatfis, BigDecimal critid, BigDecimal assettcl, BigDecimal cafttc,
			BigDecimal caftclrate) {
		this.ctrMatfis = ctrMatfis;
		this.critid = critid;
		this.assettcl = assettcl;
		this.cafttc = cafttc;
		this.caftclrate = caftclrate;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "ASSETTCL", precision = 22, scale = 0)
	public BigDecimal getAssettcl() {
		return this.assettcl;
	}

	public void setAssettcl(BigDecimal assettcl) {
		this.assettcl = assettcl;
	}

	@Column(name = "CAFTTC", precision = 22, scale = 0)
	public BigDecimal getCafttc() {
		return this.cafttc;
	}

	public void setCafttc(BigDecimal cafttc) {
		this.cafttc = cafttc;
	}

	@Column(name = "CAFTCLRATE", precision = 22, scale = 0)
	public BigDecimal getCaftclrate() {
		return this.caftclrate;
	}

	public void setCaftclrate(BigDecimal caftclrate) {
		this.caftclrate = caftclrate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ACaftotclId))
			return false;
		ACaftotclId castOther = (ACaftotclId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getAssettcl() == castOther.getAssettcl()) || (this.getAssettcl() != null
						&& castOther.getAssettcl() != null && this.getAssettcl().equals(castOther.getAssettcl())))
				&& ((this.getCafttc() == castOther.getCafttc()) || (this.getCafttc() != null
						&& castOther.getCafttc() != null && this.getCafttc().equals(castOther.getCafttc())))
				&& ((this.getCaftclrate() == castOther.getCaftclrate())
						|| (this.getCaftclrate() != null && castOther.getCaftclrate() != null
								&& this.getCaftclrate().equals(castOther.getCaftclrate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getAssettcl() == null ? 0 : this.getAssettcl().hashCode());
		result = 37 * result + (getCafttc() == null ? 0 : this.getCafttc().hashCode());
		result = 37 * result + (getCaftclrate() == null ? 0 : this.getCaftclrate().hashCode());
		return result;
	}

}
