package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ACaftotcl generated by hbm2java
 */
@Entity
@Table(name = "A_CAFTOTCL")
public class ACaftotcl implements java.io.Serializable {

	private ACaftotclId id;

	public ACaftotcl() {
	}

	public ACaftotcl(ACaftotclId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "assettcl", column = @Column(name = "ASSETTCL", precision = 22, scale = 0)),
			@AttributeOverride(name = "cafttc", column = @Column(name = "CAFTTC", precision = 22, scale = 0)),
			@AttributeOverride(name = "caftclrate", column = @Column(name = "CAFTCLRATE", precision = 22, scale = 0)) })
	public ACaftotclId getId() {
		return this.id;
	}

	public void setId(ACaftotclId id) {
		this.id = id;
	}

}
