package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ACashmoretoId generated by hbm2java
 */
@Embeddable
public class ACashmoretoId implements java.io.Serializable {

	private String ctrMatfis;
	private BigDecimal critid;
	private BigDecimal cashtransmoreto;

	public ACashmoretoId() {
	}

	public ACashmoretoId(String ctrMatfis, BigDecimal critid, BigDecimal cashtransmoreto) {
		this.ctrMatfis = ctrMatfis;
		this.critid = critid;
		this.cashtransmoreto = cashtransmoreto;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "CASHTRANSMORETO", precision = 22, scale = 0)
	public BigDecimal getCashtransmoreto() {
		return this.cashtransmoreto;
	}

	public void setCashtransmoreto(BigDecimal cashtransmoreto) {
		this.cashtransmoreto = cashtransmoreto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ACashmoretoId))
			return false;
		ACashmoretoId castOther = (ACashmoretoId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getCashtransmoreto() == castOther.getCashtransmoreto())
						|| (this.getCashtransmoreto() != null && castOther.getCashtransmoreto() != null
								&& this.getCashtransmoreto().equals(castOther.getCashtransmoreto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getCashtransmoreto() == null ? 0 : this.getCashtransmoreto().hashCode());
		return result;
	}

}
