package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AConsecloss generated by hbm2java
 */
@Entity
@Table(name = "A_CONSECLOSS")
public class AConsecloss implements java.io.Serializable {

	private AConseclossId id;

	public AConsecloss() {
	}

	public AConsecloss(AConseclossId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "actsec", column = @Column(name = "ACTSEC", length = 4)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "tocat", column = @Column(name = "TOCAT", precision = 22, scale = 0)),
			@AttributeOverride(name = "lossyears", column = @Column(name = "LOSSYEARS", precision = 22, scale = 0)),
			@AttributeOverride(name = "lastaudyear", column = @Column(name = "LASTAUDYEAR", length = 4)),
			@AttributeOverride(name = "lossnorefund", column = @Column(name = "LOSSNOREFUND", precision = 22, scale = 0)) })
	public AConseclossId getId() {
		return this.id;
	}

	public void setId(AConseclossId id) {
		this.id = id;
	}

}
