package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AConseclossId generated by hbm2java
 */
@Embeddable
public class AConseclossId implements java.io.Serializable {

	private String ctrMatfis;
	private BigDecimal critid;
	private String actsec;
	private String ctrCatego;
	private BigDecimal tocat;
	private BigDecimal lossyears;
	private String lastaudyear;
	private BigDecimal lossnorefund;

	public AConseclossId() {
	}

	public AConseclossId(String ctrMatfis, BigDecimal critid, String actsec, String ctrCatego, BigDecimal tocat,
			BigDecimal lossyears, String lastaudyear, BigDecimal lossnorefund) {
		this.ctrMatfis = ctrMatfis;
		this.critid = critid;
		this.actsec = actsec;
		this.ctrCatego = ctrCatego;
		this.tocat = tocat;
		this.lossyears = lossyears;
		this.lastaudyear = lastaudyear;
		this.lossnorefund = lossnorefund;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "ACTSEC", length = 4)
	public String getActsec() {
		return this.actsec;
	}

	public void setActsec(String actsec) {
		this.actsec = actsec;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "TOCAT", precision = 22, scale = 0)
	public BigDecimal getTocat() {
		return this.tocat;
	}

	public void setTocat(BigDecimal tocat) {
		this.tocat = tocat;
	}

	@Column(name = "LOSSYEARS", precision = 22, scale = 0)
	public BigDecimal getLossyears() {
		return this.lossyears;
	}

	public void setLossyears(BigDecimal lossyears) {
		this.lossyears = lossyears;
	}

	@Column(name = "LASTAUDYEAR", length = 4)
	public String getLastaudyear() {
		return this.lastaudyear;
	}

	public void setLastaudyear(String lastaudyear) {
		this.lastaudyear = lastaudyear;
	}

	@Column(name = "LOSSNOREFUND", precision = 22, scale = 0)
	public BigDecimal getLossnorefund() {
		return this.lossnorefund;
	}

	public void setLossnorefund(BigDecimal lossnorefund) {
		this.lossnorefund = lossnorefund;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AConseclossId))
			return false;
		AConseclossId castOther = (AConseclossId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getActsec() == castOther.getActsec()) || (this.getActsec() != null
						&& castOther.getActsec() != null && this.getActsec().equals(castOther.getActsec())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getTocat() == castOther.getTocat()) || (this.getTocat() != null
						&& castOther.getTocat() != null && this.getTocat().equals(castOther.getTocat())))
				&& ((this.getLossyears() == castOther.getLossyears()) || (this.getLossyears() != null
						&& castOther.getLossyears() != null && this.getLossyears().equals(castOther.getLossyears())))
				&& ((this.getLastaudyear() == castOther.getLastaudyear())
						|| (this.getLastaudyear() != null && castOther.getLastaudyear() != null
								&& this.getLastaudyear().equals(castOther.getLastaudyear())))
				&& ((this.getLossnorefund() == castOther.getLossnorefund())
						|| (this.getLossnorefund() != null && castOther.getLossnorefund() != null
								&& this.getLossnorefund().equals(castOther.getLossnorefund())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getActsec() == null ? 0 : this.getActsec().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getTocat() == null ? 0 : this.getTocat().hashCode());
		result = 37 * result + (getLossyears() == null ? 0 : this.getLossyears().hashCode());
		result = 37 * result + (getLastaudyear() == null ? 0 : this.getLastaudyear().hashCode());
		result = 37 * result + (getLossnorefund() == null ? 0 : this.getLossnorefund().hashCode());
		return result;
	}

}
