package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AExportbene generated by hbm2java
 */
@Entity
@Table(name = "A_EXPORTBENE")
public class AExportbene implements java.io.Serializable {

	private AExportbeneId id;

	public AExportbene() {
	}

	public AExportbene(AExportbeneId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "exportbenefit", column = @Column(name = "EXPORTBENEFIT", precision = 22, scale = 0)) })
	public AExportbeneId getId() {
		return this.id;
	}

	public void setId(AExportbeneId id) {
		this.id = id;
	}

}
