package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AExportdeductId generated by hbm2java
 */
@Embeddable
public class AExportdeductId implements java.io.Serializable {

	private String ctrMatfis;
	private BigDecimal critid;
	private BigDecimal expded;
	private BigDecimal deduc;
	private BigDecimal cafexp;

	public AExportdeductId() {
	}

	public AExportdeductId(String ctrMatfis, BigDecimal critid, BigDecimal expded, BigDecimal deduc,
			BigDecimal cafexp) {
		this.ctrMatfis = ctrMatfis;
		this.critid = critid;
		this.expded = expded;
		this.deduc = deduc;
		this.cafexp = cafexp;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "EXPDED", precision = 22, scale = 0)
	public BigDecimal getExpded() {
		return this.expded;
	}

	public void setExpded(BigDecimal expded) {
		this.expded = expded;
	}

	@Column(name = "DEDUC", precision = 22, scale = 0)
	public BigDecimal getDeduc() {
		return this.deduc;
	}

	public void setDeduc(BigDecimal deduc) {
		this.deduc = deduc;
	}

	@Column(name = "CAFEXP", precision = 22, scale = 0)
	public BigDecimal getCafexp() {
		return this.cafexp;
	}

	public void setCafexp(BigDecimal cafexp) {
		this.cafexp = cafexp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AExportdeductId))
			return false;
		AExportdeductId castOther = (AExportdeductId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getExpded() == castOther.getExpded()) || (this.getExpded() != null
						&& castOther.getExpded() != null && this.getExpded().equals(castOther.getExpded())))
				&& ((this.getDeduc() == castOther.getDeduc()) || (this.getDeduc() != null
						&& castOther.getDeduc() != null && this.getDeduc().equals(castOther.getDeduc())))
				&& ((this.getCafexp() == castOther.getCafexp()) || (this.getCafexp() != null
						&& castOther.getCafexp() != null && this.getCafexp().equals(castOther.getCafexp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getExpded() == null ? 0 : this.getExpded().hashCode());
		result = 37 * result + (getDeduc() == null ? 0 : this.getDeduc().hashCode());
		result = 37 * result + (getCafexp() == null ? 0 : this.getCafexp().hashCode());
		return result;
	}

}
