package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AExportdeduct generated by hbm2java
 */
@Entity
@Table(name = "A_EXPORTDEDUCT")
public class AExportdeduct implements java.io.Serializable {

	private AExportdeductId id;

	public AExportdeduct() {
	}

	public AExportdeduct(AExportdeductId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "expded", column = @Column(name = "EXPDED", precision = 22, scale = 0)),
			@AttributeOverride(name = "deduc", column = @Column(name = "DEDUC", precision = 22, scale = 0)),
			@AttributeOverride(name = "cafexp", column = @Column(name = "CAFEXP", precision = 22, scale = 0)) })
	public AExportdeductId getId() {
		return this.id;
	}

	public void setId(AExportdeductId id) {
		this.id = id;
	}

}
