package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AnnualCriteria generated by hbm2java
 */
@Entity
@Table(name = "ANNUAL_CRITERIA")
public class AnnualCriteria implements java.io.Serializable {

	private BigDecimal annualCriteriaId;
	private CriteriaDef criteriaDef;
	private BigDecimal criteriaYear;
	private Boolean yearLocked;

	public AnnualCriteria() {
	}

	public AnnualCriteria(BigDecimal annualCriteriaId) {
		this.annualCriteriaId = annualCriteriaId;
	}

	public AnnualCriteria(BigDecimal annualCriteriaId, CriteriaDef criteriaDef, BigDecimal criteriaYear,
			Boolean yearLocked) {
		this.annualCriteriaId = annualCriteriaId;
		this.criteriaDef = criteriaDef;
		this.criteriaYear = criteriaYear;
		this.yearLocked = yearLocked;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator ="SEQUENCE1" )
	@SequenceGenerator(name="SEQUENCE1", sequenceName="SEQUENCE1", allocationSize=1)
	@Column(name = "ANNUAL_CRITERIA_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAnnualCriteriaId() {
		return this.annualCriteriaId;
	}

	public void setAnnualCriteriaId(BigDecimal annualCriteriaId) {
		this.annualCriteriaId = annualCriteriaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRITERIA_ID")
	public CriteriaDef getCriteriaDef() {
		return this.criteriaDef;
	}

	public void setCriteriaDef(CriteriaDef criteriaDef) {
		this.criteriaDef = criteriaDef;
	}

	@Column(name = "CRITERIA_YEAR", precision = 22, scale = 0)
	public BigDecimal getCriteriaYear() {
		return this.criteriaYear;
	}

	public void setCriteriaYear(BigDecimal criteriaYear) {
		this.criteriaYear = criteriaYear;
	}

	@Column(name = "YEAR_LOCKED", precision = 1, scale = 0)
	public Boolean getYearLocked() {
		return this.yearLocked;
	}

	public void setYearLocked(Boolean yearLocked) {
		this.yearLocked = yearLocked;
	}

}
