package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ANoaudit generated by hbm2java
 */
@Entity
@Table(name = "A_NOAUDIT")
public class ANoaudit implements java.io.Serializable {

	private ANoauditId id;

	public ANoaudit() {
	}

	public ANoaudit(ANoauditId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "actsec", column = @Column(name = "ACTSEC", length = 4)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "tocat", column = @Column(name = "TOCAT", precision = 22, scale = 0)),
			@AttributeOverride(name = "notaudit", column = @Column(name = "NOTAUDIT", precision = 22, scale = 0)) })
	public ANoauditId getId() {
		return this.id;
	}

	public void setId(ANoauditId id) {
		this.id = id;
	}

}
