package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ANpmargin generated by hbm2java
 */
@Entity
@Table(name = "A_NPMARGIN")
public class ANpmargin implements java.io.Serializable {

	private ANpmarginId id;

	public ANpmargin() {
	}

	public ANpmargin(ANpmarginId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "exerci", column = @Column(name = "EXERCI", length = 4)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "actsec", column = @Column(name = "ACTSEC", length = 4)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "tocat", column = @Column(name = "TOCAT", precision = 22, scale = 0)),
			@AttributeOverride(name = "acctresult", column = @Column(name = "ACCTRESULT", precision = 22, scale = 0)),
			@AttributeOverride(name = "turnover", column = @Column(name = "TURNOVER", precision = 22, scale = 0)),
			@AttributeOverride(name = "npmargin", column = @Column(name = "NPMARGIN", precision = 22, scale = 0)),
			@AttributeOverride(name = "decok", column = @Column(name = "DECOK", precision = 22, scale = 0)) })
	public ANpmarginId getId() {
		return this.id;
	}

	public void setId(ANpmarginId id) {
		this.id = id;
	}

}
