package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ARentreport generated by hbm2java
 */
@Entity
@Table(name = "A_RENTREPORT")
public class ARentreport implements java.io.Serializable {

	private ARentreportId id;

	public ARentreport() {
	}

	public ARentreport(ARentreportId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "crityear", column = @Column(name = "CRITYEAR", precision = 4, scale = 0)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "rentnotreported", column = @Column(name = "RENTNOTREPORTED", precision = 22, scale = 0)) })
	public ARentreportId getId() {
		return this.id;
	}

	public void setId(ARentreportId id) {
		this.id = id;
	}

}
