package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ARentreportId generated by hbm2java
 */
@Embeddable
public class ARentreportId implements java.io.Serializable {

	private String ctrMatfis;
	private Short crityear;
	private BigDecimal critid;
	private BigDecimal rentnotreported;

	public ARentreportId() {
	}

	public ARentreportId(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	public ARentreportId(String ctrMatfis, Short crityear, BigDecimal critid, BigDecimal rentnotreported) {
		this.ctrMatfis = ctrMatfis;
		this.crityear = crityear;
		this.critid = critid;
		this.rentnotreported = rentnotreported;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CRITYEAR", precision = 4, scale = 0)
	public Short getCrityear() {
		return this.crityear;
	}

	public void setCrityear(Short crityear) {
		this.crityear = crityear;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "RENTNOTREPORTED", precision = 22, scale = 0)
	public BigDecimal getRentnotreported() {
		return this.rentnotreported;
	}

	public void setRentnotreported(BigDecimal rentnotreported) {
		this.rentnotreported = rentnotreported;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ARentreportId))
			return false;
		ARentreportId castOther = (ARentreportId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCrityear() == castOther.getCrityear()) || (this.getCrityear() != null
						&& castOther.getCrityear() != null && this.getCrityear().equals(castOther.getCrityear())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getRentnotreported() == castOther.getRentnotreported())
						|| (this.getRentnotreported() != null && castOther.getRentnotreported() != null
								&& this.getRentnotreported().equals(castOther.getRentnotreported())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCrityear() == null ? 0 : this.getCrityear().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getRentnotreported() == null ? 0 : this.getRentnotreported().hashCode());
		return result;
	}

}
