package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuditSelectScoresId generated by hbm2java
 */
@Embeddable
public class AuditSelectScoresId implements java.io.Serializable {

	private Short taxYear;
	private BigDecimal criteriaId;
	private String ctrMatfis;
	private BigDecimal score;

	public AuditSelectScoresId() {
	}

	public AuditSelectScoresId(Short taxYear, BigDecimal criteriaId, String ctrMatfis, BigDecimal score) {
		this.taxYear = taxYear;
		this.criteriaId = criteriaId;
		this.ctrMatfis = ctrMatfis;
		this.score = score;
	}

	@Column(name = "TAX_YEAR", precision = 4, scale = 0)
	public Short getTaxYear() {
		return this.taxYear;
	}

	public void setTaxYear(Short taxYear) {
		this.taxYear = taxYear;
	}

	@Column(name = "CRITERIA_ID", precision = 22, scale = 0)
	public BigDecimal getCriteriaId() {
		return this.criteriaId;
	}

	public void setCriteriaId(BigDecimal criteriaId) {
		this.criteriaId = criteriaId;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "SCORE", precision = 22, scale = 0)
	public BigDecimal getScore() {
		return this.score;
	}

	public void setScore(BigDecimal score) {
		this.score = score;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuditSelectScoresId))
			return false;
		AuditSelectScoresId castOther = (AuditSelectScoresId) other;

		return ((this.getTaxYear() == castOther.getTaxYear()) || (this.getTaxYear() != null
				&& castOther.getTaxYear() != null && this.getTaxYear().equals(castOther.getTaxYear())))
				&& ((this.getCriteriaId() == castOther.getCriteriaId()) || (this.getCriteriaId() != null
						&& castOther.getCriteriaId() != null && this.getCriteriaId().equals(castOther.getCriteriaId())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getScore() == castOther.getScore()) || (this.getScore() != null
						&& castOther.getScore() != null && this.getScore().equals(castOther.getScore())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTaxYear() == null ? 0 : this.getTaxYear().hashCode());
		result = 37 * result + (getCriteriaId() == null ? 0 : this.getCriteriaId().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getScore() == null ? 0 : this.getScore().hashCode());
		return result;
	}

}
