package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuditSelectScores generated by hbm2java
 */
@Entity
@Table(name = "AUDIT_SELECT_SCORES")
public class AuditSelectScores implements java.io.Serializable {

	private AuditSelectScoresId id;

	public AuditSelectScores() {
	}

	public AuditSelectScores(AuditSelectScoresId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "taxYear", column = @Column(name = "TAX_YEAR", precision = 4, scale = 0)),
			@AttributeOverride(name = "criteriaId", column = @Column(name = "CRITERIA_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "score", column = @Column(name = "SCORE", precision = 22, scale = 0)) })
	public AuditSelectScoresId getId() {
		return this.id;
	}

	public void setId(AuditSelectScoresId id) {
		this.id = id;
	}

}
