package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AWageintensityId generated by hbm2java
 */
@Embeddable
public class AWageintensityId implements java.io.Serializable {

	private String ctrMatfis;
	private String exerci;
	private BigDecimal critid;
	private String actsec;
	private String ctrCatego;
	private BigDecimal tocat;
	private BigDecimal turnover;
	private BigDecimal ax1Brtimp;
	private BigDecimal cnsMassal;
	private BigDecimal salary;
	private BigDecimal wageintensity;
	private BigDecimal decok;

	public AWageintensityId() {
	}

	public AWageintensityId(String ctrMatfis, String exerci, BigDecimal critid, String actsec, String ctrCatego,
			BigDecimal tocat, BigDecimal turnover, BigDecimal ax1Brtimp, BigDecimal cnsMassal, BigDecimal salary,
			BigDecimal wageintensity, BigDecimal decok) {
		this.ctrMatfis = ctrMatfis;
		this.exerci = exerci;
		this.critid = critid;
		this.actsec = actsec;
		this.ctrCatego = ctrCatego;
		this.tocat = tocat;
		this.turnover = turnover;
		this.ax1Brtimp = ax1Brtimp;
		this.cnsMassal = cnsMassal;
		this.salary = salary;
		this.wageintensity = wageintensity;
		this.decok = decok;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "EXERCI", length = 4)
	public String getExerci() {
		return this.exerci;
	}

	public void setExerci(String exerci) {
		this.exerci = exerci;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "ACTSEC", length = 4)
	public String getActsec() {
		return this.actsec;
	}

	public void setActsec(String actsec) {
		this.actsec = actsec;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "TOCAT", precision = 22, scale = 0)
	public BigDecimal getTocat() {
		return this.tocat;
	}

	public void setTocat(BigDecimal tocat) {
		this.tocat = tocat;
	}

	@Column(name = "TURNOVER", precision = 22, scale = 0)
	public BigDecimal getTurnover() {
		return this.turnover;
	}

	public void setTurnover(BigDecimal turnover) {
		this.turnover = turnover;
	}

	@Column(name = "AX1_BRTIMP", precision = 22, scale = 0)
	public BigDecimal getAx1Brtimp() {
		return this.ax1Brtimp;
	}

	public void setAx1Brtimp(BigDecimal ax1Brtimp) {
		this.ax1Brtimp = ax1Brtimp;
	}

	@Column(name = "CNS_MASSAL", precision = 22, scale = 0)
	public BigDecimal getCnsMassal() {
		return this.cnsMassal;
	}

	public void setCnsMassal(BigDecimal cnsMassal) {
		this.cnsMassal = cnsMassal;
	}

	@Column(name = "SALARY", precision = 22, scale = 0)
	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	@Column(name = "WAGEINTENSITY", precision = 22, scale = 0)
	public BigDecimal getWageintensity() {
		return this.wageintensity;
	}

	public void setWageintensity(BigDecimal wageintensity) {
		this.wageintensity = wageintensity;
	}

	@Column(name = "DECOK", precision = 22, scale = 0)
	public BigDecimal getDecok() {
		return this.decok;
	}

	public void setDecok(BigDecimal decok) {
		this.decok = decok;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AWageintensityId))
			return false;
		AWageintensityId castOther = (AWageintensityId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getExerci() == castOther.getExerci()) || (this.getExerci() != null
						&& castOther.getExerci() != null && this.getExerci().equals(castOther.getExerci())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getActsec() == castOther.getActsec()) || (this.getActsec() != null
						&& castOther.getActsec() != null && this.getActsec().equals(castOther.getActsec())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getTocat() == castOther.getTocat()) || (this.getTocat() != null
						&& castOther.getTocat() != null && this.getTocat().equals(castOther.getTocat())))
				&& ((this.getTurnover() == castOther.getTurnover()) || (this.getTurnover() != null
						&& castOther.getTurnover() != null && this.getTurnover().equals(castOther.getTurnover())))
				&& ((this.getAx1Brtimp() == castOther.getAx1Brtimp()) || (this.getAx1Brtimp() != null
						&& castOther.getAx1Brtimp() != null && this.getAx1Brtimp().equals(castOther.getAx1Brtimp())))
				&& ((this.getCnsMassal() == castOther.getCnsMassal()) || (this.getCnsMassal() != null
						&& castOther.getCnsMassal() != null && this.getCnsMassal().equals(castOther.getCnsMassal())))
				&& ((this.getSalary() == castOther.getSalary()) || (this.getSalary() != null
						&& castOther.getSalary() != null && this.getSalary().equals(castOther.getSalary())))
				&& ((this.getWageintensity() == castOther.getWageintensity())
						|| (this.getWageintensity() != null && castOther.getWageintensity() != null
								&& this.getWageintensity().equals(castOther.getWageintensity())))
				&& ((this.getDecok() == castOther.getDecok()) || (this.getDecok() != null
						&& castOther.getDecok() != null && this.getDecok().equals(castOther.getDecok())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getExerci() == null ? 0 : this.getExerci().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getActsec() == null ? 0 : this.getActsec().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getTocat() == null ? 0 : this.getTocat().hashCode());
		result = 37 * result + (getTurnover() == null ? 0 : this.getTurnover().hashCode());
		result = 37 * result + (getAx1Brtimp() == null ? 0 : this.getAx1Brtimp().hashCode());
		result = 37 * result + (getCnsMassal() == null ? 0 : this.getCnsMassal().hashCode());
		result = 37 * result + (getSalary() == null ? 0 : this.getSalary().hashCode());
		result = 37 * result + (getWageintensity() == null ? 0 : this.getWageintensity().hashCode());
		result = 37 * result + (getDecok() == null ? 0 : this.getDecok().hashCode());
		return result;
	}

}
