package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AXrefvatturnoverId generated by hbm2java
 */
@Embeddable
public class AXrefvatturnoverId implements java.io.Serializable {

	private String ctrMatfis;
	private String exerci;
	private BigDecimal critid;
	private String actsec;
	private String ctrCatego;
	private BigDecimal tocat;
	private BigDecimal localturnover;
	private BigDecimal sumtva;
	private BigDecimal turnoverpc;
	private BigDecimal decok;

	public AXrefvatturnoverId() {
	}

	public AXrefvatturnoverId(String ctrMatfis, String exerci, BigDecimal critid, String actsec, String ctrCatego,
			BigDecimal tocat, BigDecimal localturnover, BigDecimal sumtva, BigDecimal turnoverpc, BigDecimal decok) {
		this.ctrMatfis = ctrMatfis;
		this.exerci = exerci;
		this.critid = critid;
		this.actsec = actsec;
		this.ctrCatego = ctrCatego;
		this.tocat = tocat;
		this.localturnover = localturnover;
		this.sumtva = sumtva;
		this.turnoverpc = turnoverpc;
		this.decok = decok;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "EXERCI", length = 4)
	public String getExerci() {
		return this.exerci;
	}

	public void setExerci(String exerci) {
		this.exerci = exerci;
	}

	@Column(name = "CRITID", precision = 22, scale = 0)
	public BigDecimal getCritid() {
		return this.critid;
	}

	public void setCritid(BigDecimal critid) {
		this.critid = critid;
	}

	@Column(name = "ACTSEC", length = 4)
	public String getActsec() {
		return this.actsec;
	}

	public void setActsec(String actsec) {
		this.actsec = actsec;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "TOCAT", precision = 22, scale = 0)
	public BigDecimal getTocat() {
		return this.tocat;
	}

	public void setTocat(BigDecimal tocat) {
		this.tocat = tocat;
	}

	@Column(name = "LOCALTURNOVER", precision = 22, scale = 0)
	public BigDecimal getLocalturnover() {
		return this.localturnover;
	}

	public void setLocalturnover(BigDecimal localturnover) {
		this.localturnover = localturnover;
	}

	@Column(name = "SUMTVA", precision = 22, scale = 0)
	public BigDecimal getSumtva() {
		return this.sumtva;
	}

	public void setSumtva(BigDecimal sumtva) {
		this.sumtva = sumtva;
	}

	@Column(name = "TURNOVERPC", precision = 22, scale = 0)
	public BigDecimal getTurnoverpc() {
		return this.turnoverpc;
	}

	public void setTurnoverpc(BigDecimal turnoverpc) {
		this.turnoverpc = turnoverpc;
	}

	@Column(name = "DECOK", precision = 22, scale = 0)
	public BigDecimal getDecok() {
		return this.decok;
	}

	public void setDecok(BigDecimal decok) {
		this.decok = decok;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AXrefvatturnoverId))
			return false;
		AXrefvatturnoverId castOther = (AXrefvatturnoverId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getExerci() == castOther.getExerci()) || (this.getExerci() != null
						&& castOther.getExerci() != null && this.getExerci().equals(castOther.getExerci())))
				&& ((this.getCritid() == castOther.getCritid()) || (this.getCritid() != null
						&& castOther.getCritid() != null && this.getCritid().equals(castOther.getCritid())))
				&& ((this.getActsec() == castOther.getActsec()) || (this.getActsec() != null
						&& castOther.getActsec() != null && this.getActsec().equals(castOther.getActsec())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getTocat() == castOther.getTocat()) || (this.getTocat() != null
						&& castOther.getTocat() != null && this.getTocat().equals(castOther.getTocat())))
				&& ((this.getLocalturnover() == castOther.getLocalturnover())
						|| (this.getLocalturnover() != null && castOther.getLocalturnover() != null
								&& this.getLocalturnover().equals(castOther.getLocalturnover())))
				&& ((this.getSumtva() == castOther.getSumtva()) || (this.getSumtva() != null
						&& castOther.getSumtva() != null && this.getSumtva().equals(castOther.getSumtva())))
				&& ((this.getTurnoverpc() == castOther.getTurnoverpc()) || (this.getTurnoverpc() != null
						&& castOther.getTurnoverpc() != null && this.getTurnoverpc().equals(castOther.getTurnoverpc())))
				&& ((this.getDecok() == castOther.getDecok()) || (this.getDecok() != null
						&& castOther.getDecok() != null && this.getDecok().equals(castOther.getDecok())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getExerci() == null ? 0 : this.getExerci().hashCode());
		result = 37 * result + (getCritid() == null ? 0 : this.getCritid().hashCode());
		result = 37 * result + (getActsec() == null ? 0 : this.getActsec().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getTocat() == null ? 0 : this.getTocat().hashCode());
		result = 37 * result + (getLocalturnover() == null ? 0 : this.getLocalturnover().hashCode());
		result = 37 * result + (getSumtva() == null ? 0 : this.getSumtva().hashCode());
		result = 37 * result + (getTurnoverpc() == null ? 0 : this.getTurnoverpc().hashCode());
		result = 37 * result + (getDecok() == null ? 0 : this.getDecok().hashCode());
		return result;
	}

}
