package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AZeroto generated by hbm2java
 */
@Entity
@Table(name = "A_ZEROTO")
public class AZeroto implements java.io.Serializable {

	private AZerotoId id;

	public AZeroto() {
	}

	public AZeroto(AZerotoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "zeroto", column = @Column(name = "ZEROTO", precision = 22, scale = 0)) })
	public AZerotoId getId() {
		return this.id;
	}

	public void setId(AZerotoId id) {
		this.id = id;
	}

}
