package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Criteriaavg generated by hbm2java
 */
@Entity
@Table(name = "CRITERIAAVG")
public class Criteriaavg implements java.io.Serializable {

	private CriteriaAvgId id;

	public Criteriaavg() {
	}

	public Criteriaavg(CriteriaAvgId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "crityear", column = @Column(name = "CRITYEAR", precision = 4, scale = 0)),
			@AttributeOverride(name = "actsec", column = @Column(name = "ACTSEC", length = 4)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "togroup", column = @Column(name = "TOGROUP", length = 4)),
			@AttributeOverride(name = "cnt", column = @Column(name = "CNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "gpcount", column = @Column(name = "GPCOUNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "avggpmargin", column = @Column(name = "AVGGPMARGIN", precision = 22, scale = 0)),
			@AttributeOverride(name = "npcount", column = @Column(name = "NPCOUNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "avgnpmargin", column = @Column(name = "AVGNPMARGIN", precision = 22, scale = 0)),
			@AttributeOverride(name = "wagecount", column = @Column(name = "WAGECOUNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "avgwageint", column = @Column(name = "AVGWAGEINT", precision = 22, scale = 0)),
			@AttributeOverride(name = "xrefcount", column = @Column(name = "XREFCOUNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "avgvattopc", column = @Column(name = "AVGVATTOPC", precision = 22, scale = 0)) })
	public CriteriaAvgId getId() {
		return this.id;
	}

	public void setId(CriteriaAvgId id) {
		this.id = id;
	}

}
