package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Criteriarange generated by hbm2java
 */
@Entity
@Table(name = "CRITERIARANGE")
public class Criteriarange implements java.io.Serializable {

	private CriteriarangeId id;

	public Criteriarange() {
	}

	public Criteriarange(CriteriarangeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "critid", column = @Column(name = "CRITID", precision = 22, scale = 0)),
			@AttributeOverride(name = "rangeid", column = @Column(name = "RANGEID", precision = 22, scale = 0)),
			@AttributeOverride(name = "lowerlimit", column = @Column(name = "LOWERLIMIT", precision = 126, scale = 0)),
			@AttributeOverride(name = "upperlimit", column = @Column(name = "UPPERLIMIT", precision = 126, scale = 0)),
			@AttributeOverride(name = "score", column = @Column(name = "SCORE", precision = 22, scale = 0)) })
	public CriteriarangeId getId() {
		return this.id;
	}

	public void setId(CriteriarangeId id) {
		this.id = id;
	}

}
