package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CriteriaGroupId generated by hbm2java
 */
@Embeddable
public class CriteriaGroupId implements java.io.Serializable {

	private Short criteriaYear;
	private BigDecimal actSec;
	private Character ctrCatego;
	private String toGroup;
	private BigDecimal criteriaGroupId;

	public CriteriaGroupId() {
	}

	public CriteriaGroupId(BigDecimal criteriaGroupId) {
		this.criteriaGroupId = criteriaGroupId;
	}

	public CriteriaGroupId(Short criteriaYear, BigDecimal actSec, Character ctrCatego, String toGroup,
			BigDecimal criteriaGroupId) {
		this.criteriaYear = criteriaYear;
		this.actSec = actSec;
		this.ctrCatego = ctrCatego;
		this.toGroup = toGroup;
		this.criteriaGroupId = criteriaGroupId;
	}

	@Column(name = "CRITERIA_YEAR", precision = 4, scale = 0)
	public Short getCriteriaYear() {
		return this.criteriaYear;
	}

	public void setCriteriaYear(Short criteriaYear) {
		this.criteriaYear = criteriaYear;
	}

	@Column(name = "ACT_SEC", precision = 22, scale = 0)
	public BigDecimal getActSec() {
		return this.actSec;
	}

	public void setActSec(BigDecimal actSec) {
		this.actSec = actSec;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public Character getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(Character ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "TO_GROUP", length = 4)
	public String getToGroup() {
		return this.toGroup;
	}

	public void setToGroup(String toGroup) {
		this.toGroup = toGroup;
	}

	@Column(name = "CRITERIA_GROUP_ID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCriteriaGroupId() {
		return this.criteriaGroupId;
	}

	public void setCriteriaGroupId(BigDecimal criteriaGroupId) {
		this.criteriaGroupId = criteriaGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CriteriaGroupId))
			return false;
		CriteriaGroupId castOther = (CriteriaGroupId) other;

		return ((this.getCriteriaYear() == castOther.getCriteriaYear()) || (this.getCriteriaYear() != null
				&& castOther.getCriteriaYear() != null && this.getCriteriaYear().equals(castOther.getCriteriaYear())))
				&& ((this.getActSec() == castOther.getActSec()) || (this.getActSec() != null
						&& castOther.getActSec() != null && this.getActSec().equals(castOther.getActSec())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getToGroup() == castOther.getToGroup()) || (this.getToGroup() != null
						&& castOther.getToGroup() != null && this.getToGroup().equals(castOther.getToGroup())))
				&& ((this.getCriteriaGroupId() == castOther.getCriteriaGroupId())
						|| (this.getCriteriaGroupId() != null && castOther.getCriteriaGroupId() != null
								&& this.getCriteriaGroupId().equals(castOther.getCriteriaGroupId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCriteriaYear() == null ? 0 : this.getCriteriaYear().hashCode());
		result = 37 * result + (getActSec() == null ? 0 : this.getActSec().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getToGroup() == null ? 0 : this.getToGroup().hashCode());
		result = 37 * result + (getCriteriaGroupId() == null ? 0 : this.getCriteriaGroupId().hashCode());
		return result;
	}

}
