package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Lastaudit generated by hbm2java
 */
@Entity
@Table(name = "LASTAUDIT")
public class Lastaudit implements java.io.Serializable {

	private LastauditId id;

	public Lastaudit() {
	}

	public Lastaudit(LastauditId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "vapFinvap", column = @Column(name = "VAP_FINVAP", length = 4)),
			@AttributeOverride(name = "vapMntred", column = @Column(name = "VAP_MNTRED", precision = 15, scale = 0)) })
	public LastauditId getId() {
		return this.id;
	}

	public void setId(LastauditId id) {
		this.id = id;
	}

}
