package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LastauditId generated by hbm2java
 */
@Embeddable
public class LastauditId implements java.io.Serializable {

	private String ctrMatfis;
	private String vapFinvap;
	private Long vapMntred;

	public LastauditId() {
	}

	public LastauditId(String ctrMatfis, String vapFinvap, Long vapMntred) {
		this.ctrMatfis = ctrMatfis;
		this.vapFinvap = vapFinvap;
		this.vapMntred = vapMntred;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "VAP_FINVAP", length = 4)
	public String getVapFinvap() {
		return this.vapFinvap;
	}

	public void setVapFinvap(String vapFinvap) {
		this.vapFinvap = vapFinvap;
	}

	@Column(name = "VAP_MNTRED", precision = 15, scale = 0)
	public Long getVapMntred() {
		return this.vapMntred;
	}

	public void setVapMntred(Long vapMntred) {
		this.vapMntred = vapMntred;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LastauditId))
			return false;
		LastauditId castOther = (LastauditId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getVapFinvap() == castOther.getVapFinvap()) || (this.getVapFinvap() != null
						&& castOther.getVapFinvap() != null && this.getVapFinvap().equals(castOther.getVapFinvap())))
				&& ((this.getVapMntred() == castOther.getVapMntred()) || (this.getVapMntred() != null
						&& castOther.getVapMntred() != null && this.getVapMntred().equals(castOther.getVapMntred())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getVapFinvap() == null ? 0 : this.getVapFinvap().hashCode());
		result = 37 * result + (getVapMntred() == null ? 0 : this.getVapMntred().hashCode());
		return result;
	}

}
