package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nomcpt generated by hbm2java
 */
@Entity
@Table(name = "NOMCPT")
public class Nomcpt implements java.io.Serializable {

	private String cptCodcpt;
	private String cptLibell;
	private Short cptNumord;

	public Nomcpt() {
	}

	public Nomcpt(String cptCodcpt) {
		this.cptCodcpt = cptCodcpt;
	}

	public Nomcpt(String cptCodcpt, String cptLibell, Short cptNumord) {
		this.cptCodcpt = cptCodcpt;
		this.cptLibell = cptLibell;
		this.cptNumord = cptNumord;
	}

	@Id

	@Column(name = "CPT_CODCPT", unique = true, nullable = false, length = 4)
	public String getCptCodcpt() {
		return this.cptCodcpt;
	}

	public void setCptCodcpt(String cptCodcpt) {
		this.cptCodcpt = cptCodcpt;
	}

	@Column(name = "CPT_LIBELL", length = 120)
	public String getCptLibell() {
		return this.cptLibell;
	}

	public void setCptLibell(String cptLibell) {
		this.cptLibell = cptLibell;
	}

	@Column(name = "CPT_NUMORD", precision = 3, scale = 0)
	public Short getCptNumord() {
		return this.cptNumord;
	}

	public void setCptNumord(Short cptNumord) {
		this.cptNumord = cptNumord;
	}

}
