package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oblfis generated by hbm2java
 */
@Entity
@Table(name = "OBLFIS")
public class Oblfis implements java.io.Serializable {

	private String oblCodobl;
	private String oblLibobl;
	private Date oblDatcre;
	private String oblGrpobl;
	private Set<Valobl> valobls = new HashSet<Valobl>(0);

	public Oblfis() {
	}

	public Oblfis(String oblCodobl, String oblLibobl) {
		this.oblCodobl = oblCodobl;
		this.oblLibobl = oblLibobl;
	}

	public Oblfis(String oblCodobl, String oblLibobl, Date oblDatcre, String oblGrpobl, Set<Valobl> valobls) {
		this.oblCodobl = oblCodobl;
		this.oblLibobl = oblLibobl;
		this.oblDatcre = oblDatcre;
		this.oblGrpobl = oblGrpobl;
		this.valobls = valobls;
	}

	@Id

	@Column(name = "OBL_CODOBL", unique = true, nullable = false, length = 2)
	public String getOblCodobl() {
		return this.oblCodobl;
	}

	public void setOblCodobl(String oblCodobl) {
		this.oblCodobl = oblCodobl;
	}

	@Column(name = "OBL_LIBOBL", nullable = false, length = 60)
	public String getOblLibobl() {
		return this.oblLibobl;
	}

	public void setOblLibobl(String oblLibobl) {
		this.oblLibobl = oblLibobl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OBL_DATCRE", length = 7)
	public Date getOblDatcre() {
		return this.oblDatcre;
	}

	public void setOblDatcre(Date oblDatcre) {
		this.oblDatcre = oblDatcre;
	}

	@Column(name = "OBL_GRPOBL", length = 2)
	public String getOblGrpobl() {
		return this.oblGrpobl;
	}

	public void setOblGrpobl(String oblGrpobl) {
		this.oblGrpobl = oblGrpobl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oblfis")
	public Set<Valobl> getValobls() {
		return this.valobls;
	}

	public void setValobls(Set<Valobl> valobls) {
		this.valobls = valobls;
	}

}
