package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgrpay generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGRPAY")
public class P3aAgrpay implements java.io.Serializable {

	private P3aAgrpayId id;

	public P3aAgrpay() {
	}

	public P3aAgrpay(P3aAgrpayId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "payExerci", column = @Column(name = "PAY_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "payMntann", column = @Column(name = "PAY_MNTANN", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMntacp", column = @Column(name = "PAY_MNTACP", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMntres", column = @Column(name = "PAY_MNTRES", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMnttfp", column = @Column(name = "PAY_MNTTFP", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMntfop", column = @Column(name = "PAY_MNTFOP", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMntdco", column = @Column(name = "PAY_MNTDCO", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMnttva", column = @Column(name = "PAY_MNTTVA", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMnttas", column = @Column(name = "PAY_MNTTAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMdtimb", column = @Column(name = "PAY_MDTIMB", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMnttcl", column = @Column(name = "PAY_MNTTCL", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMnttho", column = @Column(name = "PAY_MNTTHO", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMntaut", column = @Column(name = "PAY_MNTAUT", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMfodec", column = @Column(name = "PAY_MFODEC", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMfocap", column = @Column(name = "PAY_MFOCAP", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMfodet", column = @Column(name = "PAY_MFODET", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMnttel", column = @Column(name = "PAY_MNTTEL", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMntemp", column = @Column(name = "PAY_MNTEMP", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMtomat", column = @Column(name = "PAY_MTOMAT", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMpollu", column = @Column(name = "PAY_MPOLLU", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMclima", column = @Column(name = "PAY_MCLIMA", precision = 22, scale = 0)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "payPetrol", column = @Column(name = "PAY_PETROL", precision = 22, scale = 0)),
			@AttributeOverride(name = "payMtabac", column = @Column(name = "PAY_MTABAC", precision = 22, scale = 0)) })
	public P3aAgrpayId getId() {
		return this.id;
	}

	public void setId(P3aAgrpayId id) {
		this.id = id;
	}

}
