package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgrdco generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGRDCO")
public class P3aAgrdco implements java.io.Serializable {

	private P3aAgrdcoId id;

	public P3aAgrdco() {
	}

	public P3aAgrdco(P3aAgrdcoId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dcoExerci", column = @Column(name = "DCO_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "dcoCatadv", column = @Column(name = "DCO_CATADV", precision = 22, scale = 0)),
			@AttributeOverride(name = "dcoCatspe", column = @Column(name = "DCO_CATSPE", precision = 22, scale = 0)),
			@AttributeOverride(name = "dcoTotdue", column = @Column(name = "DCO_TOTDUE", precision = 22, scale = 0)),
			@AttributeOverride(name = "dcoMoideb", column = @Column(name = "DCO_MOIDEB", length = 2)),
			@AttributeOverride(name = "dcoCrdini", column = @Column(name = "DCO_CRDINI", precision = 22, scale = 0)),
			@AttributeOverride(name = "dcoDedloc", column = @Column(name = "DCO_DEDLOC", precision = 22, scale = 0)),
			@AttributeOverride(name = "tcoDedimp", column = @Column(name = "TCO_DEDIMP", precision = 22, scale = 0)),
			@AttributeOverride(name = "tcoMntpay", column = @Column(name = "TCO_MNTPAY", precision = 22, scale = 0)),
			@AttributeOverride(name = "tcoMoifin", column = @Column(name = "TCO_MOIFIN", length = 2)),
			@AttributeOverride(name = "tcoMntrep", column = @Column(name = "TCO_MNTREP", precision = 22, scale = 0)) })
	public P3aAgrdcoId getId() {
		return this.id;
	}

	public void setId(P3aAgrdcoId id) {
		this.id = id;
	}

}
