package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * P3aActagr generated by hbm2java
 */
@Entity
@Table(name = "P3A_ACTAGR", uniqueConstraints = @UniqueConstraint(columnNames = { "CTR_MATFIS", "CTR_ETBSEC",
		"ACT_QALLIB", "AGR_ANNACT" }))
public class P3aActagr implements java.io.Serializable {

	private P3aActagrId id;

	public P3aActagr() {
	}

	public P3aActagr(P3aActagrId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "agrAnnact", column = @Column(name = "AGR_ANNACT", length = 4)),
			@AttributeOverride(name = "actQallib", column = @Column(name = "ACT_QALLIB", length = 50)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", length = 3)),
			@AttributeOverride(name = "agrMntbin", column = @Column(name = "AGR_MNTBIN", precision = 22, scale = 0)) })
	public P3aActagrId getId() {
		return this.id;
	}

	public void setId(P3aActagrId id) {
		this.id = id;
	}

}
