package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAsinda generated by hbm2java
 */
@Entity
@Table(name = "P3A_ASINDA")
public class P3aAsinda implements java.io.Serializable {

	private P3aAsindaId id;
	private BigDecimal sndMntprd;
	private BigDecimal sndMntret;

	public P3aAsinda() {
	}

	public P3aAsinda(P3aAsindaId id) {
		this.id = id;
	}

	public P3aAsinda(P3aAsindaId id, BigDecimal sndMntprd, BigDecimal sndMntret) {
		this.id = id;
		this.sndMntprd = sndMntprd;
		this.sndMntret = sndMntret;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "sndAnnded", column = @Column(name = "SND_ANNDED", nullable = false, length = 4)),
			@AttributeOverride(name = "sndImpexp", column = @Column(name = "SND_IMPEXP", nullable = false, length = 12)) })
	public P3aAsindaId getId() {
		return this.id;
	}

	public void setId(P3aAsindaId id) {
		this.id = id;
	}

	@Column(name = "SND_MNTPRD", precision = 22, scale = 0)
	public BigDecimal getSndMntprd() {
		return this.sndMntprd;
	}

	public void setSndMntprd(BigDecimal sndMntprd) {
		this.sndMntprd = sndMntprd;
	}

	@Column(name = "SND_MNTRET", precision = 22, scale = 0)
	public BigDecimal getSndMntret() {
		return this.sndMntret;
	}

	public void setSndMntret(BigDecimal sndMntret) {
		this.sndMntret = sndMntret;
	}

}
