package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aAgrdcoId generated by hbm2java
 */
@Embeddable
public class P3aAgrdcoId implements java.io.Serializable {

	private String dcoExerci;
	private String ctrMatfis;
	private String ctrCatego;
	private String ctrEtbsec;
	private BigDecimal dcoCatadv;
	private BigDecimal dcoCatspe;
	private BigDecimal dcoTotdue;
	private String dcoMoideb;
	private BigDecimal dcoCrdini;
	private BigDecimal dcoDedloc;
	private BigDecimal tcoDedimp;
	private BigDecimal tcoMntpay;
	private String tcoMoifin;
	private BigDecimal tcoMntrep;

	public P3aAgrdcoId() {
	}

	public P3aAgrdcoId(String dcoExerci, String ctrMatfis, String ctrEtbsec) {
		this.dcoExerci = dcoExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
	}

	public P3aAgrdcoId(String dcoExerci, String ctrMatfis, String ctrCatego, String ctrEtbsec, BigDecimal dcoCatadv,
			BigDecimal dcoCatspe, BigDecimal dcoTotdue, String dcoMoideb, BigDecimal dcoCrdini, BigDecimal dcoDedloc,
			BigDecimal tcoDedimp, BigDecimal tcoMntpay, String tcoMoifin, BigDecimal tcoMntrep) {
		this.dcoExerci = dcoExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.dcoCatadv = dcoCatadv;
		this.dcoCatspe = dcoCatspe;
		this.dcoTotdue = dcoTotdue;
		this.dcoMoideb = dcoMoideb;
		this.dcoCrdini = dcoCrdini;
		this.dcoDedloc = dcoDedloc;
		this.tcoDedimp = tcoDedimp;
		this.tcoMntpay = tcoMntpay;
		this.tcoMoifin = tcoMoifin;
		this.tcoMntrep = tcoMntrep;
	}

	@Column(name = "DCO_EXERCI", nullable = false, length = 4)
	public String getDcoExerci() {
		return this.dcoExerci;
	}

	public void setDcoExerci(String dcoExerci) {
		this.dcoExerci = dcoExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "DCO_CATADV", precision = 22, scale = 0)
	public BigDecimal getDcoCatadv() {
		return this.dcoCatadv;
	}

	public void setDcoCatadv(BigDecimal dcoCatadv) {
		this.dcoCatadv = dcoCatadv;
	}

	@Column(name = "DCO_CATSPE", precision = 22, scale = 0)
	public BigDecimal getDcoCatspe() {
		return this.dcoCatspe;
	}

	public void setDcoCatspe(BigDecimal dcoCatspe) {
		this.dcoCatspe = dcoCatspe;
	}

	@Column(name = "DCO_TOTDUE", precision = 22, scale = 0)
	public BigDecimal getDcoTotdue() {
		return this.dcoTotdue;
	}

	public void setDcoTotdue(BigDecimal dcoTotdue) {
		this.dcoTotdue = dcoTotdue;
	}

	@Column(name = "DCO_MOIDEB", length = 2)
	public String getDcoMoideb() {
		return this.dcoMoideb;
	}

	public void setDcoMoideb(String dcoMoideb) {
		this.dcoMoideb = dcoMoideb;
	}

	@Column(name = "DCO_CRDINI", precision = 22, scale = 0)
	public BigDecimal getDcoCrdini() {
		return this.dcoCrdini;
	}

	public void setDcoCrdini(BigDecimal dcoCrdini) {
		this.dcoCrdini = dcoCrdini;
	}

	@Column(name = "DCO_DEDLOC", precision = 22, scale = 0)
	public BigDecimal getDcoDedloc() {
		return this.dcoDedloc;
	}

	public void setDcoDedloc(BigDecimal dcoDedloc) {
		this.dcoDedloc = dcoDedloc;
	}

	@Column(name = "TCO_DEDIMP", precision = 22, scale = 0)
	public BigDecimal getTcoDedimp() {
		return this.tcoDedimp;
	}

	public void setTcoDedimp(BigDecimal tcoDedimp) {
		this.tcoDedimp = tcoDedimp;
	}

	@Column(name = "TCO_MNTPAY", precision = 22, scale = 0)
	public BigDecimal getTcoMntpay() {
		return this.tcoMntpay;
	}

	public void setTcoMntpay(BigDecimal tcoMntpay) {
		this.tcoMntpay = tcoMntpay;
	}

	@Column(name = "TCO_MOIFIN", length = 2)
	public String getTcoMoifin() {
		return this.tcoMoifin;
	}

	public void setTcoMoifin(String tcoMoifin) {
		this.tcoMoifin = tcoMoifin;
	}

	@Column(name = "TCO_MNTREP", precision = 22, scale = 0)
	public BigDecimal getTcoMntrep() {
		return this.tcoMntrep;
	}

	public void setTcoMntrep(BigDecimal tcoMntrep) {
		this.tcoMntrep = tcoMntrep;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aAgrdcoId))
			return false;
		P3aAgrdcoId castOther = (P3aAgrdcoId) other;

		return ((this.getDcoExerci() == castOther.getDcoExerci()) || (this.getDcoExerci() != null
				&& castOther.getDcoExerci() != null && this.getDcoExerci().equals(castOther.getDcoExerci())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getDcoCatadv() == castOther.getDcoCatadv()) || (this.getDcoCatadv() != null
						&& castOther.getDcoCatadv() != null && this.getDcoCatadv().equals(castOther.getDcoCatadv())))
				&& ((this.getDcoCatspe() == castOther.getDcoCatspe()) || (this.getDcoCatspe() != null
						&& castOther.getDcoCatspe() != null && this.getDcoCatspe().equals(castOther.getDcoCatspe())))
				&& ((this.getDcoTotdue() == castOther.getDcoTotdue()) || (this.getDcoTotdue() != null
						&& castOther.getDcoTotdue() != null && this.getDcoTotdue().equals(castOther.getDcoTotdue())))
				&& ((this.getDcoMoideb() == castOther.getDcoMoideb()) || (this.getDcoMoideb() != null
						&& castOther.getDcoMoideb() != null && this.getDcoMoideb().equals(castOther.getDcoMoideb())))
				&& ((this.getDcoCrdini() == castOther.getDcoCrdini()) || (this.getDcoCrdini() != null
						&& castOther.getDcoCrdini() != null && this.getDcoCrdini().equals(castOther.getDcoCrdini())))
				&& ((this.getDcoDedloc() == castOther.getDcoDedloc()) || (this.getDcoDedloc() != null
						&& castOther.getDcoDedloc() != null && this.getDcoDedloc().equals(castOther.getDcoDedloc())))
				&& ((this.getTcoDedimp() == castOther.getTcoDedimp()) || (this.getTcoDedimp() != null
						&& castOther.getTcoDedimp() != null && this.getTcoDedimp().equals(castOther.getTcoDedimp())))
				&& ((this.getTcoMntpay() == castOther.getTcoMntpay()) || (this.getTcoMntpay() != null
						&& castOther.getTcoMntpay() != null && this.getTcoMntpay().equals(castOther.getTcoMntpay())))
				&& ((this.getTcoMoifin() == castOther.getTcoMoifin()) || (this.getTcoMoifin() != null
						&& castOther.getTcoMoifin() != null && this.getTcoMoifin().equals(castOther.getTcoMoifin())))
				&& ((this.getTcoMntrep() == castOther.getTcoMntrep()) || (this.getTcoMntrep() != null
						&& castOther.getTcoMntrep() != null && this.getTcoMntrep().equals(castOther.getTcoMntrep())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDcoExerci() == null ? 0 : this.getDcoExerci().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getDcoCatadv() == null ? 0 : this.getDcoCatadv().hashCode());
		result = 37 * result + (getDcoCatspe() == null ? 0 : this.getDcoCatspe().hashCode());
		result = 37 * result + (getDcoTotdue() == null ? 0 : this.getDcoTotdue().hashCode());
		result = 37 * result + (getDcoMoideb() == null ? 0 : this.getDcoMoideb().hashCode());
		result = 37 * result + (getDcoCrdini() == null ? 0 : this.getDcoCrdini().hashCode());
		result = 37 * result + (getDcoDedloc() == null ? 0 : this.getDcoDedloc().hashCode());
		result = 37 * result + (getTcoDedimp() == null ? 0 : this.getTcoDedimp().hashCode());
		result = 37 * result + (getTcoMntpay() == null ? 0 : this.getTcoMntpay().hashCode());
		result = 37 * result + (getTcoMoifin() == null ? 0 : this.getTcoMoifin().hashCode());
		result = 37 * result + (getTcoMntrep() == null ? 0 : this.getTcoMntrep().hashCode());
		return result;
	}

}
