package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aAsindaId generated by hbm2java
 */
@Embeddable
public class P3aAsindaId implements java.io.Serializable {

	private String ctrMatfis;
	private String ctrEtbsec;
	private String sndAnnded;
	private String sndImpexp;

	public P3aAsindaId() {
	}

	public P3aAsindaId(String ctrMatfis, String ctrEtbsec, String sndAnnded, String sndImpexp) {
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.sndAnnded = sndAnnded;
		this.sndImpexp = sndImpexp;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "SND_ANNDED", nullable = false, length = 4)
	public String getSndAnnded() {
		return this.sndAnnded;
	}

	public void setSndAnnded(String sndAnnded) {
		this.sndAnnded = sndAnnded;
	}

	@Column(name = "SND_IMPEXP", nullable = false, length = 12)
	public String getSndImpexp() {
		return this.sndImpexp;
	}

	public void setSndImpexp(String sndImpexp) {
		this.sndImpexp = sndImpexp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aAsindaId))
			return false;
		P3aAsindaId castOther = (P3aAsindaId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getSndAnnded() == castOther.getSndAnnded()) || (this.getSndAnnded() != null
						&& castOther.getSndAnnded() != null && this.getSndAnnded().equals(castOther.getSndAnnded())))
				&& ((this.getSndImpexp() == castOther.getSndImpexp()) || (this.getSndImpexp() != null
						&& castOther.getSndImpexp() != null && this.getSndImpexp().equals(castOther.getSndImpexp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getSndAnnded() == null ? 0 : this.getSndAnnded().hashCode());
		result = 37 * result + (getSndImpexp() == null ? 0 : this.getSndImpexp().hashCode());
		return result;
	}

}
