package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aActsecId generated by hbm2java
 */
@Embeddable
public class P3aActsecId implements java.io.Serializable {

	private String actSecact;
	private String actLibell;

	public P3aActsecId() {
	}

	public P3aActsecId(String actSecact, String actLibell) {
		this.actSecact = actSecact;
		this.actLibell = actLibell;
	}

	@Column(name = "ACT_SECACT", nullable = false, length = 2)
	public String getActSecact() {
		return this.actSecact;
	}

	public void setActSecact(String actSecact) {
		this.actSecact = actSecact;
	}

	@Column(name = "ACT_LIBELL", nullable = false, length = 120)
	public String getActLibell() {
		return this.actLibell;
	}

	public void setActLibell(String actLibell) {
		this.actLibell = actLibell;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aActsecId))
			return false;
		P3aActsecId castOther = (P3aActsecId) other;

		return ((this.getActSecact() == castOther.getActSecact()) || (this.getActSecact() != null
				&& castOther.getActSecact() != null && this.getActSecact().equals(castOther.getActSecact())))
				&& ((this.getActLibell() == castOther.getActLibell()) || (this.getActLibell() != null
						&& castOther.getActLibell() != null && this.getActLibell().equals(castOther.getActLibell())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getActSecact() == null ? 0 : this.getActSecact().hashCode());
		result = 37 * result + (getActLibell() == null ? 0 : this.getActLibell().hashCode());
		return result;
	}

}
