package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aActssc generated by hbm2java
 */
@Entity
@Table(name = "P3A_ACTSSC")
public class P3aActssc implements java.io.Serializable {

	private P3aActsscId id;

	public P3aActssc() {
	}

	public P3aActssc(P3aActsscId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "actSousec", column = @Column(name = "ACT_SOUSEC", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "actLibell", column = @Column(name = "ACT_LIBELL", length = 250)),
			@AttributeOverride(name = "actSecact", column = @Column(name = "ACT_SECACT", length = 2)) })
	public P3aActsscId getId() {
		return this.id;
	}

	public void setId(P3aActsscId id) {
		this.id = id;
	}

}
