package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aAgrpayId generated by hbm2java
 */
@Embeddable
public class P3aAgrpayId implements java.io.Serializable {

	private String payExerci;
	private String ctrCatego;
	private BigDecimal payMntann;
	private BigDecimal payMntacp;
	private BigDecimal payMntres;
	private BigDecimal payMnttfp;
	private BigDecimal payMntfop;
	private BigDecimal payMntdco;
	private BigDecimal payMnttva;
	private BigDecimal payMnttas;
	private BigDecimal payMdtimb;
	private BigDecimal payMnttcl;
	private BigDecimal payMnttho;
	private BigDecimal payMntaut;
	private BigDecimal payMfodec;
	private BigDecimal payMfocap;
	private BigDecimal payMfodet;
	private BigDecimal payMnttel;
	private BigDecimal payMntemp;
	private BigDecimal payMtomat;
	private BigDecimal payMpollu;
	private BigDecimal payMclima;
	private String ctrMatfis;
	private String ctrEtbsec;
	private BigDecimal payPetrol;
	private BigDecimal payMtabac;

	public P3aAgrpayId() {
	}

	public P3aAgrpayId(String payExerci, String ctrMatfis, String ctrEtbsec) {
		this.payExerci = payExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
	}

	public P3aAgrpayId(String payExerci, String ctrCatego, BigDecimal payMntann, BigDecimal payMntacp,
			BigDecimal payMntres, BigDecimal payMnttfp, BigDecimal payMntfop, BigDecimal payMntdco,
			BigDecimal payMnttva, BigDecimal payMnttas, BigDecimal payMdtimb, BigDecimal payMnttcl,
			BigDecimal payMnttho, BigDecimal payMntaut, BigDecimal payMfodec, BigDecimal payMfocap,
			BigDecimal payMfodet, BigDecimal payMnttel, BigDecimal payMntemp, BigDecimal payMtomat,
			BigDecimal payMpollu, BigDecimal payMclima, String ctrMatfis, String ctrEtbsec, BigDecimal payPetrol,
			BigDecimal payMtabac) {
		this.payExerci = payExerci;
		this.ctrCatego = ctrCatego;
		this.payMntann = payMntann;
		this.payMntacp = payMntacp;
		this.payMntres = payMntres;
		this.payMnttfp = payMnttfp;
		this.payMntfop = payMntfop;
		this.payMntdco = payMntdco;
		this.payMnttva = payMnttva;
		this.payMnttas = payMnttas;
		this.payMdtimb = payMdtimb;
		this.payMnttcl = payMnttcl;
		this.payMnttho = payMnttho;
		this.payMntaut = payMntaut;
		this.payMfodec = payMfodec;
		this.payMfocap = payMfocap;
		this.payMfodet = payMfodet;
		this.payMnttel = payMnttel;
		this.payMntemp = payMntemp;
		this.payMtomat = payMtomat;
		this.payMpollu = payMpollu;
		this.payMclima = payMclima;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.payPetrol = payPetrol;
		this.payMtabac = payMtabac;
	}

	@Column(name = "PAY_EXERCI", nullable = false, length = 4)
	public String getPayExerci() {
		return this.payExerci;
	}

	public void setPayExerci(String payExerci) {
		this.payExerci = payExerci;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "PAY_MNTANN", precision = 22, scale = 0)
	public BigDecimal getPayMntann() {
		return this.payMntann;
	}

	public void setPayMntann(BigDecimal payMntann) {
		this.payMntann = payMntann;
	}

	@Column(name = "PAY_MNTACP", precision = 22, scale = 0)
	public BigDecimal getPayMntacp() {
		return this.payMntacp;
	}

	public void setPayMntacp(BigDecimal payMntacp) {
		this.payMntacp = payMntacp;
	}

	@Column(name = "PAY_MNTRES", precision = 22, scale = 0)
	public BigDecimal getPayMntres() {
		return this.payMntres;
	}

	public void setPayMntres(BigDecimal payMntres) {
		this.payMntres = payMntres;
	}

	@Column(name = "PAY_MNTTFP", precision = 22, scale = 0)
	public BigDecimal getPayMnttfp() {
		return this.payMnttfp;
	}

	public void setPayMnttfp(BigDecimal payMnttfp) {
		this.payMnttfp = payMnttfp;
	}

	@Column(name = "PAY_MNTFOP", precision = 22, scale = 0)
	public BigDecimal getPayMntfop() {
		return this.payMntfop;
	}

	public void setPayMntfop(BigDecimal payMntfop) {
		this.payMntfop = payMntfop;
	}

	@Column(name = "PAY_MNTDCO", precision = 22, scale = 0)
	public BigDecimal getPayMntdco() {
		return this.payMntdco;
	}

	public void setPayMntdco(BigDecimal payMntdco) {
		this.payMntdco = payMntdco;
	}

	@Column(name = "PAY_MNTTVA", precision = 22, scale = 0)
	public BigDecimal getPayMnttva() {
		return this.payMnttva;
	}

	public void setPayMnttva(BigDecimal payMnttva) {
		this.payMnttva = payMnttva;
	}

	@Column(name = "PAY_MNTTAS", precision = 22, scale = 0)
	public BigDecimal getPayMnttas() {
		return this.payMnttas;
	}

	public void setPayMnttas(BigDecimal payMnttas) {
		this.payMnttas = payMnttas;
	}

	@Column(name = "PAY_MDTIMB", precision = 22, scale = 0)
	public BigDecimal getPayMdtimb() {
		return this.payMdtimb;
	}

	public void setPayMdtimb(BigDecimal payMdtimb) {
		this.payMdtimb = payMdtimb;
	}

	@Column(name = "PAY_MNTTCL", precision = 22, scale = 0)
	public BigDecimal getPayMnttcl() {
		return this.payMnttcl;
	}

	public void setPayMnttcl(BigDecimal payMnttcl) {
		this.payMnttcl = payMnttcl;
	}

	@Column(name = "PAY_MNTTHO", precision = 22, scale = 0)
	public BigDecimal getPayMnttho() {
		return this.payMnttho;
	}

	public void setPayMnttho(BigDecimal payMnttho) {
		this.payMnttho = payMnttho;
	}

	@Column(name = "PAY_MNTAUT", precision = 22, scale = 0)
	public BigDecimal getPayMntaut() {
		return this.payMntaut;
	}

	public void setPayMntaut(BigDecimal payMntaut) {
		this.payMntaut = payMntaut;
	}

	@Column(name = "PAY_MFODEC", precision = 22, scale = 0)
	public BigDecimal getPayMfodec() {
		return this.payMfodec;
	}

	public void setPayMfodec(BigDecimal payMfodec) {
		this.payMfodec = payMfodec;
	}

	@Column(name = "PAY_MFOCAP", precision = 22, scale = 0)
	public BigDecimal getPayMfocap() {
		return this.payMfocap;
	}

	public void setPayMfocap(BigDecimal payMfocap) {
		this.payMfocap = payMfocap;
	}

	@Column(name = "PAY_MFODET", precision = 22, scale = 0)
	public BigDecimal getPayMfodet() {
		return this.payMfodet;
	}

	public void setPayMfodet(BigDecimal payMfodet) {
		this.payMfodet = payMfodet;
	}

	@Column(name = "PAY_MNTTEL", precision = 22, scale = 0)
	public BigDecimal getPayMnttel() {
		return this.payMnttel;
	}

	public void setPayMnttel(BigDecimal payMnttel) {
		this.payMnttel = payMnttel;
	}

	@Column(name = "PAY_MNTEMP", precision = 22, scale = 0)
	public BigDecimal getPayMntemp() {
		return this.payMntemp;
	}

	public void setPayMntemp(BigDecimal payMntemp) {
		this.payMntemp = payMntemp;
	}

	@Column(name = "PAY_MTOMAT", precision = 22, scale = 0)
	public BigDecimal getPayMtomat() {
		return this.payMtomat;
	}

	public void setPayMtomat(BigDecimal payMtomat) {
		this.payMtomat = payMtomat;
	}

	@Column(name = "PAY_MPOLLU", precision = 22, scale = 0)
	public BigDecimal getPayMpollu() {
		return this.payMpollu;
	}

	public void setPayMpollu(BigDecimal payMpollu) {
		this.payMpollu = payMpollu;
	}

	@Column(name = "PAY_MCLIMA", precision = 22, scale = 0)
	public BigDecimal getPayMclima() {
		return this.payMclima;
	}

	public void setPayMclima(BigDecimal payMclima) {
		this.payMclima = payMclima;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "PAY_PETROL", precision = 22, scale = 0)
	public BigDecimal getPayPetrol() {
		return this.payPetrol;
	}

	public void setPayPetrol(BigDecimal payPetrol) {
		this.payPetrol = payPetrol;
	}

	@Column(name = "PAY_MTABAC", precision = 22, scale = 0)
	public BigDecimal getPayMtabac() {
		return this.payMtabac;
	}

	public void setPayMtabac(BigDecimal payMtabac) {
		this.payMtabac = payMtabac;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aAgrpayId))
			return false;
		P3aAgrpayId castOther = (P3aAgrpayId) other;

		return ((this.getPayExerci() == castOther.getPayExerci()) || (this.getPayExerci() != null
				&& castOther.getPayExerci() != null && this.getPayExerci().equals(castOther.getPayExerci())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getPayMntann() == castOther.getPayMntann()) || (this.getPayMntann() != null
						&& castOther.getPayMntann() != null && this.getPayMntann().equals(castOther.getPayMntann())))
				&& ((this.getPayMntacp() == castOther.getPayMntacp()) || (this.getPayMntacp() != null
						&& castOther.getPayMntacp() != null && this.getPayMntacp().equals(castOther.getPayMntacp())))
				&& ((this.getPayMntres() == castOther.getPayMntres()) || (this.getPayMntres() != null
						&& castOther.getPayMntres() != null && this.getPayMntres().equals(castOther.getPayMntres())))
				&& ((this.getPayMnttfp() == castOther.getPayMnttfp()) || (this.getPayMnttfp() != null
						&& castOther.getPayMnttfp() != null && this.getPayMnttfp().equals(castOther.getPayMnttfp())))
				&& ((this.getPayMntfop() == castOther.getPayMntfop()) || (this.getPayMntfop() != null
						&& castOther.getPayMntfop() != null && this.getPayMntfop().equals(castOther.getPayMntfop())))
				&& ((this.getPayMntdco() == castOther.getPayMntdco()) || (this.getPayMntdco() != null
						&& castOther.getPayMntdco() != null && this.getPayMntdco().equals(castOther.getPayMntdco())))
				&& ((this.getPayMnttva() == castOther.getPayMnttva()) || (this.getPayMnttva() != null
						&& castOther.getPayMnttva() != null && this.getPayMnttva().equals(castOther.getPayMnttva())))
				&& ((this.getPayMnttas() == castOther.getPayMnttas()) || (this.getPayMnttas() != null
						&& castOther.getPayMnttas() != null && this.getPayMnttas().equals(castOther.getPayMnttas())))
				&& ((this.getPayMdtimb() == castOther.getPayMdtimb()) || (this.getPayMdtimb() != null
						&& castOther.getPayMdtimb() != null && this.getPayMdtimb().equals(castOther.getPayMdtimb())))
				&& ((this.getPayMnttcl() == castOther.getPayMnttcl()) || (this.getPayMnttcl() != null
						&& castOther.getPayMnttcl() != null && this.getPayMnttcl().equals(castOther.getPayMnttcl())))
				&& ((this.getPayMnttho() == castOther.getPayMnttho()) || (this.getPayMnttho() != null
						&& castOther.getPayMnttho() != null && this.getPayMnttho().equals(castOther.getPayMnttho())))
				&& ((this.getPayMntaut() == castOther.getPayMntaut()) || (this.getPayMntaut() != null
						&& castOther.getPayMntaut() != null && this.getPayMntaut().equals(castOther.getPayMntaut())))
				&& ((this.getPayMfodec() == castOther.getPayMfodec()) || (this.getPayMfodec() != null
						&& castOther.getPayMfodec() != null && this.getPayMfodec().equals(castOther.getPayMfodec())))
				&& ((this.getPayMfocap() == castOther.getPayMfocap()) || (this.getPayMfocap() != null
						&& castOther.getPayMfocap() != null && this.getPayMfocap().equals(castOther.getPayMfocap())))
				&& ((this.getPayMfodet() == castOther.getPayMfodet()) || (this.getPayMfodet() != null
						&& castOther.getPayMfodet() != null && this.getPayMfodet().equals(castOther.getPayMfodet())))
				&& ((this.getPayMnttel() == castOther.getPayMnttel()) || (this.getPayMnttel() != null
						&& castOther.getPayMnttel() != null && this.getPayMnttel().equals(castOther.getPayMnttel())))
				&& ((this.getPayMntemp() == castOther.getPayMntemp()) || (this.getPayMntemp() != null
						&& castOther.getPayMntemp() != null && this.getPayMntemp().equals(castOther.getPayMntemp())))
				&& ((this.getPayMtomat() == castOther.getPayMtomat()) || (this.getPayMtomat() != null
						&& castOther.getPayMtomat() != null && this.getPayMtomat().equals(castOther.getPayMtomat())))
				&& ((this.getPayMpollu() == castOther.getPayMpollu()) || (this.getPayMpollu() != null
						&& castOther.getPayMpollu() != null && this.getPayMpollu().equals(castOther.getPayMpollu())))
				&& ((this.getPayMclima() == castOther.getPayMclima()) || (this.getPayMclima() != null
						&& castOther.getPayMclima() != null && this.getPayMclima().equals(castOther.getPayMclima())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getPayPetrol() == castOther.getPayPetrol()) || (this.getPayPetrol() != null
						&& castOther.getPayPetrol() != null && this.getPayPetrol().equals(castOther.getPayPetrol())))
				&& ((this.getPayMtabac() == castOther.getPayMtabac()) || (this.getPayMtabac() != null
						&& castOther.getPayMtabac() != null && this.getPayMtabac().equals(castOther.getPayMtabac())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPayExerci() == null ? 0 : this.getPayExerci().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getPayMntann() == null ? 0 : this.getPayMntann().hashCode());
		result = 37 * result + (getPayMntacp() == null ? 0 : this.getPayMntacp().hashCode());
		result = 37 * result + (getPayMntres() == null ? 0 : this.getPayMntres().hashCode());
		result = 37 * result + (getPayMnttfp() == null ? 0 : this.getPayMnttfp().hashCode());
		result = 37 * result + (getPayMntfop() == null ? 0 : this.getPayMntfop().hashCode());
		result = 37 * result + (getPayMntdco() == null ? 0 : this.getPayMntdco().hashCode());
		result = 37 * result + (getPayMnttva() == null ? 0 : this.getPayMnttva().hashCode());
		result = 37 * result + (getPayMnttas() == null ? 0 : this.getPayMnttas().hashCode());
		result = 37 * result + (getPayMdtimb() == null ? 0 : this.getPayMdtimb().hashCode());
		result = 37 * result + (getPayMnttcl() == null ? 0 : this.getPayMnttcl().hashCode());
		result = 37 * result + (getPayMnttho() == null ? 0 : this.getPayMnttho().hashCode());
		result = 37 * result + (getPayMntaut() == null ? 0 : this.getPayMntaut().hashCode());
		result = 37 * result + (getPayMfodec() == null ? 0 : this.getPayMfodec().hashCode());
		result = 37 * result + (getPayMfocap() == null ? 0 : this.getPayMfocap().hashCode());
		result = 37 * result + (getPayMfodet() == null ? 0 : this.getPayMfodet().hashCode());
		result = 37 * result + (getPayMnttel() == null ? 0 : this.getPayMnttel().hashCode());
		result = 37 * result + (getPayMntemp() == null ? 0 : this.getPayMntemp().hashCode());
		result = 37 * result + (getPayMtomat() == null ? 0 : this.getPayMtomat().hashCode());
		result = 37 * result + (getPayMpollu() == null ? 0 : this.getPayMpollu().hashCode());
		result = 37 * result + (getPayMclima() == null ? 0 : this.getPayMclima().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getPayPetrol() == null ? 0 : this.getPayPetrol().hashCode());
		result = 37 * result + (getPayMtabac() == null ? 0 : this.getPayMtabac().hashCode());
		return result;
	}

}
