package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgrtva generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGRTVA")
public class P3aAgrtva implements java.io.Serializable {

	private P3aAgrtvaId id;

	public P3aAgrtva() {
	}

	public P3aAgrtva(P3aAgrtvaId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tvaExerci", column = @Column(name = "TVA_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "tvaChaff6", column = @Column(name = "TVA_CHAFF6", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaff7", column = @Column(name = "TVA_CHAFF7", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf10", column = @Column(name = "TVA_CHAF10", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf12", column = @Column(name = "TVA_CHAF12", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaCaf125", column = @Column(name = "TVA_CAF125", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf15", column = @Column(name = "TVA_CHAF15", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf18", column = @Column(name = "TVA_CHAF18", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf22", column = @Column(name = "TVA_CHAF22", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf29", column = @Column(name = "TVA_CHAF29", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaChaf36", column = @Column(name = "TVA_CHAF36", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaTotdue", column = @Column(name = "TVA_TOTDUE", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaMoideb", column = @Column(name = "TVA_MOIDEB", length = 2)),
			@AttributeOverride(name = "tvaCrdini", column = @Column(name = "TVA_CRDINI", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaBasimb", column = @Column(name = "TVA_BASIMB", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedimb", column = @Column(name = "TVA_DEDIMB", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaBaseql", column = @Column(name = "TVA_BASEQL", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedeql", column = @Column(name = "TVA_DEDEQL", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaBaseqi", column = @Column(name = "TVA_BASEQI", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedeqi", column = @Column(name = "TVA_DEDEQI", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaBasaul", column = @Column(name = "TVA_BASAUL", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedaul", column = @Column(name = "TVA_DEDAUL", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaBasaui", column = @Column(name = "TVA_BASAUI", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedaui", column = @Column(name = "TVA_DEDAUI", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaBasrsm", column = @Column(name = "TVA_BASRSM", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedrsm", column = @Column(name = "TVA_DEDRSM", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaRsnres", column = @Column(name = "TVA_RSNRES", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaTrspor", column = @Column(name = "TVA_TRSPOR", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaDedreg", column = @Column(name = "TVA_DEDREG", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaRestit", column = @Column(name = "TVA_RESTIT", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaMntpay", column = @Column(name = "TVA_MNTPAY", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaMoifin", column = @Column(name = "TVA_MOIFIN", length = 2)),
			@AttributeOverride(name = "tvaCrdfin", column = @Column(name = "TVA_CRDFIN", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaAchsus", column = @Column(name = "TVA_ACHSUS", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaAchexo", column = @Column(name = "TVA_ACHEXO", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaAchndd", column = @Column(name = "TVA_ACHNDD", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaCafexp", column = @Column(name = "TVA_CAFEXP", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaCafsus", column = @Column(name = "TVA_CAFSUS", precision = 22, scale = 0)),
			@AttributeOverride(name = "tvaCafexo", column = @Column(name = "TVA_CAFEXO", precision = 22, scale = 0)) })
	public P3aAgrtvaId getId() {
		return this.id;
	}

	public void setId(P3aAgrtvaId id) {
		this.id = id;
	}

}
