package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aActsec generated by hbm2java
 */
@Entity
@Table(name = "P3A_ACTSEC")
public class P3aActsec implements java.io.Serializable {

	private P3aActsecId id;

	public P3aActsec() {
	}

	public P3aActsec(P3aActsecId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "actSecact", column = @Column(name = "ACT_SECACT", nullable = false, length = 2)),
			@AttributeOverride(name = "actLibell", column = @Column(name = "ACT_LIBELL", nullable = false, length = 120)) })
	public P3aActsecId getId() {
		return this.id;
	}

	public void setId(P3aActsecId id) {
		this.id = id;
	}

}
