package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aAgcnssId generated by hbm2java
 */
@Embeddable
public class P3aAgcnssId implements java.io.Serializable {

	private String ctrMatfis;
	private String ctrEtbsec;
	private String cnsExerci;

	public P3aAgcnssId() {
	}

	public P3aAgcnssId(String ctrMatfis, String ctrEtbsec, String cnsExerci) {
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.cnsExerci = cnsExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "CNS_EXERCI", nullable = false, length = 4)
	public String getCnsExerci() {
		return this.cnsExerci;
	}

	public void setCnsExerci(String cnsExerci) {
		this.cnsExerci = cnsExerci;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aAgcnssId))
			return false;
		P3aAgcnssId castOther = (P3aAgcnssId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getCnsExerci() == castOther.getCnsExerci()) || (this.getCnsExerci() != null
						&& castOther.getCnsExerci() != null && this.getCnsExerci().equals(castOther.getCnsExerci())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getCnsExerci() == null ? 0 : this.getCnsExerci().hashCode());
		return result;
	}

}
