package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aActiviId generated by hbm2java
 */
@Embeddable
public class P3aActiviId implements java.io.Serializable {

	private String actCodact;
	private String actLibabv;
	private String actLibell;
	private String actSecact;
	private long actSousec;

	public P3aActiviId() {
	}

	public P3aActiviId(String actCodact, String actLibell, String actSecact, long actSousec) {
		this.actCodact = actCodact;
		this.actLibell = actLibell;
		this.actSecact = actSecact;
		this.actSousec = actSousec;
	}

	public P3aActiviId(String actCodact, String actLibabv, String actLibell, String actSecact, long actSousec) {
		this.actCodact = actCodact;
		this.actLibabv = actLibabv;
		this.actLibell = actLibell;
		this.actSecact = actSecact;
		this.actSousec = actSousec;
	}

	@Column(name = "ACT_CODACT", nullable = false, length = 4)
	public String getActCodact() {
		return this.actCodact;
	}

	public void setActCodact(String actCodact) {
		this.actCodact = actCodact;
	}

	@Column(name = "ACT_LIBABV", length = 15)
	public String getActLibabv() {
		return this.actLibabv;
	}

	public void setActLibabv(String actLibabv) {
		this.actLibabv = actLibabv;
	}

	@Column(name = "ACT_LIBELL", nullable = false, length = 120)
	public String getActLibell() {
		return this.actLibell;
	}

	public void setActLibell(String actLibell) {
		this.actLibell = actLibell;
	}

	@Column(name = "ACT_SECACT", nullable = false, length = 2)
	public String getActSecact() {
		return this.actSecact;
	}

	public void setActSecact(String actSecact) {
		this.actSecact = actSecact;
	}

	@Column(name = "ACT_SOUSEC", nullable = false, precision = 10, scale = 0)
	public long getActSousec() {
		return this.actSousec;
	}

	public void setActSousec(long actSousec) {
		this.actSousec = actSousec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aActiviId))
			return false;
		P3aActiviId castOther = (P3aActiviId) other;

		return ((this.getActCodact() == castOther.getActCodact()) || (this.getActCodact() != null
				&& castOther.getActCodact() != null && this.getActCodact().equals(castOther.getActCodact())))
				&& ((this.getActLibabv() == castOther.getActLibabv()) || (this.getActLibabv() != null
						&& castOther.getActLibabv() != null && this.getActLibabv().equals(castOther.getActLibabv())))
				&& ((this.getActLibell() == castOther.getActLibell()) || (this.getActLibell() != null
						&& castOther.getActLibell() != null && this.getActLibell().equals(castOther.getActLibell())))
				&& ((this.getActSecact() == castOther.getActSecact()) || (this.getActSecact() != null
						&& castOther.getActSecact() != null && this.getActSecact().equals(castOther.getActSecact())))
				&& (this.getActSousec() == castOther.getActSousec());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getActCodact() == null ? 0 : this.getActCodact().hashCode());
		result = 37 * result + (getActLibabv() == null ? 0 : this.getActLibabv().hashCode());
		result = 37 * result + (getActLibell() == null ? 0 : this.getActLibell().hashCode());
		result = 37 * result + (getActSecact() == null ? 0 : this.getActSecact().hashCode());
		result = 37 * result + (int) this.getActSousec();
		return result;
	}

}
