package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgrtfp generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGRTFP")
public class P3aAgrtfp implements java.io.Serializable {

	private P3aAgrtfpId id;

	public P3aAgrtfp() {
	}

	public P3aAgrtfp(P3aAgrtfpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tfpExerci", column = @Column(name = "TFP_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "tfpMntdu1", column = @Column(name = "TFP_MNTDU1", precision = 22, scale = 0)),
			@AttributeOverride(name = "tfpMntdu2", column = @Column(name = "TFP_MNTDU2", precision = 22, scale = 0)),
			@AttributeOverride(name = "tfpMoideb", column = @Column(name = "TFP_MOIDEB", length = 2)),
			@AttributeOverride(name = "tfpCrdini", column = @Column(name = "TFP_CRDINI", precision = 22, scale = 0)),
			@AttributeOverride(name = "tfpRestou", column = @Column(name = "TFP_RESTOU", precision = 22, scale = 0)),
			@AttributeOverride(name = "tfpMntpay", column = @Column(name = "TFP_MNTPAY", precision = 22, scale = 0)),
			@AttributeOverride(name = "tfpMoifin", column = @Column(name = "TFP_MOIFIN", length = 2)),
			@AttributeOverride(name = "tfpMntrep", column = @Column(name = "TFP_MNTREP", precision = 22, scale = 0)) })
	public P3aAgrtfpId getId() {
		return this.id;
	}

	public void setId(P3aAgrtfpId id) {
		this.id = id;
	}

}
