package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgranx generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGRANX")
public class P3aAgranx implements java.io.Serializable {

	private P3aAgranxId id;

	public P3aAgranx() {
	}

	public P3aAgranx(P3aAgranxId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "agxTypocc", column = @Column(name = "AGX_TYPOCC", length = 1)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "empExerci", column = @Column(name = "EMP_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ax1Revimp", column = @Column(name = "AX1_REVIMP", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax1Avgnat", column = @Column(name = "AX1_AVGNAT", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax1Brtimp", column = @Column(name = "AX1_BRTIMP", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax1Revinv", column = @Column(name = "AX1_REVINV", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax1Mntret", column = @Column(name = "AX1_MNTRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax1Netsrv", column = @Column(name = "AX1_NETSRV", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Honora", column = @Column(name = "AX2_HONORA", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Loyers", column = @Column(name = "AX2_LOYERS", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Jetpre", column = @Column(name = "AX2_JETPRE", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Pluval", column = @Column(name = "AX2_PLUVAL", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Mntret", column = @Column(name = "AX2_MNTRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Ristor", column = @Column(name = "AX2_RISTOR", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax2Netsrv", column = @Column(name = "AX2_NETSRV", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax5Mntmar", column = @Column(name = "AX5_MNTMAR", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax5Mntret", column = @Column(name = "AX5_MNTRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax5Netsrv", column = @Column(name = "AX5_NETSRV", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax5Ristor", column = @Column(name = "AX5_RISTOR", precision = 22, scale = 0)),
			@AttributeOverride(name = "ax6Recouv", column = @Column(name = "AX6_RECOUV", precision = 22, scale = 0)) })
	public P3aAgranxId getId() {
		return this.id;
	}

	public void setId(P3aAgranxId id) {
		this.id = id;
	}

}
