package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgadeb generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGADEB")
public class P3aAgadeb implements java.io.Serializable {

	private P3aAgadebId id;
	private BigDecimal adbMntord;
	private BigDecimal adbRetirp;
	private BigDecimal adbRettva;
	private BigDecimal adbRetrsm;
	private BigDecimal adbMntpay;
	private BigDecimal adbAutret;

	public P3aAgadeb() {
	}

	public P3aAgadeb(P3aAgadebId id) {
		this.id = id;
	}

	public P3aAgadeb(P3aAgadebId id, BigDecimal adbMntord, BigDecimal adbRetirp, BigDecimal adbRettva,
			BigDecimal adbRetrsm, BigDecimal adbMntpay, BigDecimal adbAutret) {
		this.id = id;
		this.adbMntord = adbMntord;
		this.adbRetirp = adbRetirp;
		this.adbRettva = adbRettva;
		this.adbRetrsm = adbRetrsm;
		this.adbMntpay = adbMntpay;
		this.adbAutret = adbAutret;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "adbAnnees", column = @Column(name = "ADB_ANNEES", nullable = false, length = 4)) })
	public P3aAgadebId getId() {
		return this.id;
	}

	public void setId(P3aAgadebId id) {
		this.id = id;
	}

	@Column(name = "ADB_MNTORD", precision = 22, scale = 0)
	public BigDecimal getAdbMntord() {
		return this.adbMntord;
	}

	public void setAdbMntord(BigDecimal adbMntord) {
		this.adbMntord = adbMntord;
	}

	@Column(name = "ADB_RETIRP", precision = 22, scale = 0)
	public BigDecimal getAdbRetirp() {
		return this.adbRetirp;
	}

	public void setAdbRetirp(BigDecimal adbRetirp) {
		this.adbRetirp = adbRetirp;
	}

	@Column(name = "ADB_RETTVA", precision = 22, scale = 0)
	public BigDecimal getAdbRettva() {
		return this.adbRettva;
	}

	public void setAdbRettva(BigDecimal adbRettva) {
		this.adbRettva = adbRettva;
	}

	@Column(name = "ADB_RETRSM", precision = 22, scale = 0)
	public BigDecimal getAdbRetrsm() {
		return this.adbRetrsm;
	}

	public void setAdbRetrsm(BigDecimal adbRetrsm) {
		this.adbRetrsm = adbRetrsm;
	}

	@Column(name = "ADB_MNTPAY", precision = 22, scale = 0)
	public BigDecimal getAdbMntpay() {
		return this.adbMntpay;
	}

	public void setAdbMntpay(BigDecimal adbMntpay) {
		this.adbMntpay = adbMntpay;
	}

	@Column(name = "ADB_AUTRET", precision = 22, scale = 0)
	public BigDecimal getAdbAutret() {
		return this.adbAutret;
	}

	public void setAdbAutret(BigDecimal adbAutret) {
		this.adbAutret = adbAutret;
	}

}
