package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aActsscId generated by hbm2java
 */
@Embeddable
public class P3aActsscId implements java.io.Serializable {

	private long actSousec;
	private String actLibell;
	private String actSecact;

	public P3aActsscId() {
	}

	public P3aActsscId(long actSousec) {
		this.actSousec = actSousec;
	}

	public P3aActsscId(long actSousec, String actLibell, String actSecact) {
		this.actSousec = actSousec;
		this.actLibell = actLibell;
		this.actSecact = actSecact;
	}

	@Column(name = "ACT_SOUSEC", nullable = false, precision = 10, scale = 0)
	public long getActSousec() {
		return this.actSousec;
	}

	public void setActSousec(long actSousec) {
		this.actSousec = actSousec;
	}

	@Column(name = "ACT_LIBELL", length = 250)
	public String getActLibell() {
		return this.actLibell;
	}

	public void setActLibell(String actLibell) {
		this.actLibell = actLibell;
	}

	@Column(name = "ACT_SECACT", length = 2)
	public String getActSecact() {
		return this.actSecact;
	}

	public void setActSecact(String actSecact) {
		this.actSecact = actSecact;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aActsscId))
			return false;
		P3aActsscId castOther = (P3aActsscId) other;

		return (this.getActSousec() == castOther.getActSousec())
				&& ((this.getActLibell() == castOther.getActLibell()) || (this.getActLibell() != null
						&& castOther.getActLibell() != null && this.getActLibell().equals(castOther.getActLibell())))
				&& ((this.getActSecact() == castOther.getActSecact()) || (this.getActSecact() != null
						&& castOther.getActSecact() != null && this.getActSecact().equals(castOther.getActSecact())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getActSousec();
		result = 37 * result + (getActLibell() == null ? 0 : this.getActLibell().hashCode());
		result = 37 * result + (getActSecact() == null ? 0 : this.getActSecact().hashCode());
		return result;
	}

}
