package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aAgrtfpId generated by hbm2java
 */
@Embeddable
public class P3aAgrtfpId implements java.io.Serializable {

	private String tfpExerci;
	private String ctrMatfis;
	private String ctrCatego;
	private String ctrEtbsec;
	private BigDecimal tfpMntdu1;
	private BigDecimal tfpMntdu2;
	private String tfpMoideb;
	private BigDecimal tfpCrdini;
	private BigDecimal tfpRestou;
	private BigDecimal tfpMntpay;
	private String tfpMoifin;
	private BigDecimal tfpMntrep;

	public P3aAgrtfpId() {
	}

	public P3aAgrtfpId(String tfpExerci, String ctrMatfis, String ctrEtbsec) {
		this.tfpExerci = tfpExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
	}

	public P3aAgrtfpId(String tfpExerci, String ctrMatfis, String ctrCatego, String ctrEtbsec, BigDecimal tfpMntdu1,
			BigDecimal tfpMntdu2, String tfpMoideb, BigDecimal tfpCrdini, BigDecimal tfpRestou, BigDecimal tfpMntpay,
			String tfpMoifin, BigDecimal tfpMntrep) {
		this.tfpExerci = tfpExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.tfpMntdu1 = tfpMntdu1;
		this.tfpMntdu2 = tfpMntdu2;
		this.tfpMoideb = tfpMoideb;
		this.tfpCrdini = tfpCrdini;
		this.tfpRestou = tfpRestou;
		this.tfpMntpay = tfpMntpay;
		this.tfpMoifin = tfpMoifin;
		this.tfpMntrep = tfpMntrep;
	}

	@Column(name = "TFP_EXERCI", nullable = false, length = 4)
	public String getTfpExerci() {
		return this.tfpExerci;
	}

	public void setTfpExerci(String tfpExerci) {
		this.tfpExerci = tfpExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "TFP_MNTDU1", precision = 22, scale = 0)
	public BigDecimal getTfpMntdu1() {
		return this.tfpMntdu1;
	}

	public void setTfpMntdu1(BigDecimal tfpMntdu1) {
		this.tfpMntdu1 = tfpMntdu1;
	}

	@Column(name = "TFP_MNTDU2", precision = 22, scale = 0)
	public BigDecimal getTfpMntdu2() {
		return this.tfpMntdu2;
	}

	public void setTfpMntdu2(BigDecimal tfpMntdu2) {
		this.tfpMntdu2 = tfpMntdu2;
	}

	@Column(name = "TFP_MOIDEB", length = 2)
	public String getTfpMoideb() {
		return this.tfpMoideb;
	}

	public void setTfpMoideb(String tfpMoideb) {
		this.tfpMoideb = tfpMoideb;
	}

	@Column(name = "TFP_CRDINI", precision = 22, scale = 0)
	public BigDecimal getTfpCrdini() {
		return this.tfpCrdini;
	}

	public void setTfpCrdini(BigDecimal tfpCrdini) {
		this.tfpCrdini = tfpCrdini;
	}

	@Column(name = "TFP_RESTOU", precision = 22, scale = 0)
	public BigDecimal getTfpRestou() {
		return this.tfpRestou;
	}

	public void setTfpRestou(BigDecimal tfpRestou) {
		this.tfpRestou = tfpRestou;
	}

	@Column(name = "TFP_MNTPAY", precision = 22, scale = 0)
	public BigDecimal getTfpMntpay() {
		return this.tfpMntpay;
	}

	public void setTfpMntpay(BigDecimal tfpMntpay) {
		this.tfpMntpay = tfpMntpay;
	}

	@Column(name = "TFP_MOIFIN", length = 2)
	public String getTfpMoifin() {
		return this.tfpMoifin;
	}

	public void setTfpMoifin(String tfpMoifin) {
		this.tfpMoifin = tfpMoifin;
	}

	@Column(name = "TFP_MNTREP", precision = 22, scale = 0)
	public BigDecimal getTfpMntrep() {
		return this.tfpMntrep;
	}

	public void setTfpMntrep(BigDecimal tfpMntrep) {
		this.tfpMntrep = tfpMntrep;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aAgrtfpId))
			return false;
		P3aAgrtfpId castOther = (P3aAgrtfpId) other;

		return ((this.getTfpExerci() == castOther.getTfpExerci()) || (this.getTfpExerci() != null
				&& castOther.getTfpExerci() != null && this.getTfpExerci().equals(castOther.getTfpExerci())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getTfpMntdu1() == castOther.getTfpMntdu1()) || (this.getTfpMntdu1() != null
						&& castOther.getTfpMntdu1() != null && this.getTfpMntdu1().equals(castOther.getTfpMntdu1())))
				&& ((this.getTfpMntdu2() == castOther.getTfpMntdu2()) || (this.getTfpMntdu2() != null
						&& castOther.getTfpMntdu2() != null && this.getTfpMntdu2().equals(castOther.getTfpMntdu2())))
				&& ((this.getTfpMoideb() == castOther.getTfpMoideb()) || (this.getTfpMoideb() != null
						&& castOther.getTfpMoideb() != null && this.getTfpMoideb().equals(castOther.getTfpMoideb())))
				&& ((this.getTfpCrdini() == castOther.getTfpCrdini()) || (this.getTfpCrdini() != null
						&& castOther.getTfpCrdini() != null && this.getTfpCrdini().equals(castOther.getTfpCrdini())))
				&& ((this.getTfpRestou() == castOther.getTfpRestou()) || (this.getTfpRestou() != null
						&& castOther.getTfpRestou() != null && this.getTfpRestou().equals(castOther.getTfpRestou())))
				&& ((this.getTfpMntpay() == castOther.getTfpMntpay()) || (this.getTfpMntpay() != null
						&& castOther.getTfpMntpay() != null && this.getTfpMntpay().equals(castOther.getTfpMntpay())))
				&& ((this.getTfpMoifin() == castOther.getTfpMoifin()) || (this.getTfpMoifin() != null
						&& castOther.getTfpMoifin() != null && this.getTfpMoifin().equals(castOther.getTfpMoifin())))
				&& ((this.getTfpMntrep() == castOther.getTfpMntrep()) || (this.getTfpMntrep() != null
						&& castOther.getTfpMntrep() != null && this.getTfpMntrep().equals(castOther.getTfpMntrep())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTfpExerci() == null ? 0 : this.getTfpExerci().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getTfpMntdu1() == null ? 0 : this.getTfpMntdu1().hashCode());
		result = 37 * result + (getTfpMntdu2() == null ? 0 : this.getTfpMntdu2().hashCode());
		result = 37 * result + (getTfpMoideb() == null ? 0 : this.getTfpMoideb().hashCode());
		result = 37 * result + (getTfpCrdini() == null ? 0 : this.getTfpCrdini().hashCode());
		result = 37 * result + (getTfpRestou() == null ? 0 : this.getTfpRestou().hashCode());
		result = 37 * result + (getTfpMntpay() == null ? 0 : this.getTfpMntpay().hashCode());
		result = 37 * result + (getTfpMoifin() == null ? 0 : this.getTfpMoifin().hashCode());
		result = 37 * result + (getTfpMntrep() == null ? 0 : this.getTfpMntrep().hashCode());
		return result;
	}

}
