package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aAgrtvaId generated by hbm2java
 */
@Embeddable
public class P3aAgrtvaId implements java.io.Serializable {

	private String tvaExerci;
	private String ctrMatfis;
	private String ctrCatego;
	private String ctrEtbsec;
	private BigDecimal tvaChaff6;
	private BigDecimal tvaChaff7;
	private BigDecimal tvaChaf10;
	private BigDecimal tvaChaf12;
	private BigDecimal tvaCaf125;
	private BigDecimal tvaChaf15;
	private BigDecimal tvaChaf18;
	private BigDecimal tvaChaf22;
	private BigDecimal tvaChaf29;
	private BigDecimal tvaChaf36;
	private BigDecimal tvaTotdue;
	private String tvaMoideb;
	private BigDecimal tvaCrdini;
	private BigDecimal tvaBasimb;
	private BigDecimal tvaDedimb;
	private BigDecimal tvaBaseql;
	private BigDecimal tvaDedeql;
	private BigDecimal tvaBaseqi;
	private BigDecimal tvaDedeqi;
	private BigDecimal tvaBasaul;
	private BigDecimal tvaDedaul;
	private BigDecimal tvaBasaui;
	private BigDecimal tvaDedaui;
	private BigDecimal tvaBasrsm;
	private BigDecimal tvaDedrsm;
	private BigDecimal tvaRsnres;
	private BigDecimal tvaTrspor;
	private BigDecimal tvaDedreg;
	private BigDecimal tvaRestit;
	private BigDecimal tvaMntpay;
	private String tvaMoifin;
	private BigDecimal tvaCrdfin;
	private BigDecimal tvaAchsus;
	private BigDecimal tvaAchexo;
	private BigDecimal tvaAchndd;
	private BigDecimal tvaCafexp;
	private BigDecimal tvaCafsus;
	private BigDecimal tvaCafexo;

	public P3aAgrtvaId() {
	}

	public P3aAgrtvaId(String tvaExerci, String ctrMatfis, String ctrEtbsec) {
		this.tvaExerci = tvaExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
	}

	public P3aAgrtvaId(String tvaExerci, String ctrMatfis, String ctrCatego, String ctrEtbsec, BigDecimal tvaChaff6,
			BigDecimal tvaChaff7, BigDecimal tvaChaf10, BigDecimal tvaChaf12, BigDecimal tvaCaf125,
			BigDecimal tvaChaf15, BigDecimal tvaChaf18, BigDecimal tvaChaf22, BigDecimal tvaChaf29,
			BigDecimal tvaChaf36, BigDecimal tvaTotdue, String tvaMoideb, BigDecimal tvaCrdini, BigDecimal tvaBasimb,
			BigDecimal tvaDedimb, BigDecimal tvaBaseql, BigDecimal tvaDedeql, BigDecimal tvaBaseqi,
			BigDecimal tvaDedeqi, BigDecimal tvaBasaul, BigDecimal tvaDedaul, BigDecimal tvaBasaui,
			BigDecimal tvaDedaui, BigDecimal tvaBasrsm, BigDecimal tvaDedrsm, BigDecimal tvaRsnres,
			BigDecimal tvaTrspor, BigDecimal tvaDedreg, BigDecimal tvaRestit, BigDecimal tvaMntpay, String tvaMoifin,
			BigDecimal tvaCrdfin, BigDecimal tvaAchsus, BigDecimal tvaAchexo, BigDecimal tvaAchndd,
			BigDecimal tvaCafexp, BigDecimal tvaCafsus, BigDecimal tvaCafexo) {
		this.tvaExerci = tvaExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.tvaChaff6 = tvaChaff6;
		this.tvaChaff7 = tvaChaff7;
		this.tvaChaf10 = tvaChaf10;
		this.tvaChaf12 = tvaChaf12;
		this.tvaCaf125 = tvaCaf125;
		this.tvaChaf15 = tvaChaf15;
		this.tvaChaf18 = tvaChaf18;
		this.tvaChaf22 = tvaChaf22;
		this.tvaChaf29 = tvaChaf29;
		this.tvaChaf36 = tvaChaf36;
		this.tvaTotdue = tvaTotdue;
		this.tvaMoideb = tvaMoideb;
		this.tvaCrdini = tvaCrdini;
		this.tvaBasimb = tvaBasimb;
		this.tvaDedimb = tvaDedimb;
		this.tvaBaseql = tvaBaseql;
		this.tvaDedeql = tvaDedeql;
		this.tvaBaseqi = tvaBaseqi;
		this.tvaDedeqi = tvaDedeqi;
		this.tvaBasaul = tvaBasaul;
		this.tvaDedaul = tvaDedaul;
		this.tvaBasaui = tvaBasaui;
		this.tvaDedaui = tvaDedaui;
		this.tvaBasrsm = tvaBasrsm;
		this.tvaDedrsm = tvaDedrsm;
		this.tvaRsnres = tvaRsnres;
		this.tvaTrspor = tvaTrspor;
		this.tvaDedreg = tvaDedreg;
		this.tvaRestit = tvaRestit;
		this.tvaMntpay = tvaMntpay;
		this.tvaMoifin = tvaMoifin;
		this.tvaCrdfin = tvaCrdfin;
		this.tvaAchsus = tvaAchsus;
		this.tvaAchexo = tvaAchexo;
		this.tvaAchndd = tvaAchndd;
		this.tvaCafexp = tvaCafexp;
		this.tvaCafsus = tvaCafsus;
		this.tvaCafexo = tvaCafexo;
	}

	@Column(name = "TVA_EXERCI", nullable = false, length = 4)
	public String getTvaExerci() {
		return this.tvaExerci;
	}

	public void setTvaExerci(String tvaExerci) {
		this.tvaExerci = tvaExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "TVA_CHAFF6", precision = 22, scale = 0)
	public BigDecimal getTvaChaff6() {
		return this.tvaChaff6;
	}

	public void setTvaChaff6(BigDecimal tvaChaff6) {
		this.tvaChaff6 = tvaChaff6;
	}

	@Column(name = "TVA_CHAFF7", precision = 22, scale = 0)
	public BigDecimal getTvaChaff7() {
		return this.tvaChaff7;
	}

	public void setTvaChaff7(BigDecimal tvaChaff7) {
		this.tvaChaff7 = tvaChaff7;
	}

	@Column(name = "TVA_CHAF10", precision = 22, scale = 0)
	public BigDecimal getTvaChaf10() {
		return this.tvaChaf10;
	}

	public void setTvaChaf10(BigDecimal tvaChaf10) {
		this.tvaChaf10 = tvaChaf10;
	}

	@Column(name = "TVA_CHAF12", precision = 22, scale = 0)
	public BigDecimal getTvaChaf12() {
		return this.tvaChaf12;
	}

	public void setTvaChaf12(BigDecimal tvaChaf12) {
		this.tvaChaf12 = tvaChaf12;
	}

	@Column(name = "TVA_CAF125", precision = 22, scale = 0)
	public BigDecimal getTvaCaf125() {
		return this.tvaCaf125;
	}

	public void setTvaCaf125(BigDecimal tvaCaf125) {
		this.tvaCaf125 = tvaCaf125;
	}

	@Column(name = "TVA_CHAF15", precision = 22, scale = 0)
	public BigDecimal getTvaChaf15() {
		return this.tvaChaf15;
	}

	public void setTvaChaf15(BigDecimal tvaChaf15) {
		this.tvaChaf15 = tvaChaf15;
	}

	@Column(name = "TVA_CHAF18", precision = 22, scale = 0)
	public BigDecimal getTvaChaf18() {
		return this.tvaChaf18;
	}

	public void setTvaChaf18(BigDecimal tvaChaf18) {
		this.tvaChaf18 = tvaChaf18;
	}

	@Column(name = "TVA_CHAF22", precision = 22, scale = 0)
	public BigDecimal getTvaChaf22() {
		return this.tvaChaf22;
	}

	public void setTvaChaf22(BigDecimal tvaChaf22) {
		this.tvaChaf22 = tvaChaf22;
	}

	@Column(name = "TVA_CHAF29", precision = 22, scale = 0)
	public BigDecimal getTvaChaf29() {
		return this.tvaChaf29;
	}

	public void setTvaChaf29(BigDecimal tvaChaf29) {
		this.tvaChaf29 = tvaChaf29;
	}

	@Column(name = "TVA_CHAF36", precision = 22, scale = 0)
	public BigDecimal getTvaChaf36() {
		return this.tvaChaf36;
	}

	public void setTvaChaf36(BigDecimal tvaChaf36) {
		this.tvaChaf36 = tvaChaf36;
	}

	@Column(name = "TVA_TOTDUE", precision = 22, scale = 0)
	public BigDecimal getTvaTotdue() {
		return this.tvaTotdue;
	}

	public void setTvaTotdue(BigDecimal tvaTotdue) {
		this.tvaTotdue = tvaTotdue;
	}

	@Column(name = "TVA_MOIDEB", length = 2)
	public String getTvaMoideb() {
		return this.tvaMoideb;
	}

	public void setTvaMoideb(String tvaMoideb) {
		this.tvaMoideb = tvaMoideb;
	}

	@Column(name = "TVA_CRDINI", precision = 22, scale = 0)
	public BigDecimal getTvaCrdini() {
		return this.tvaCrdini;
	}

	public void setTvaCrdini(BigDecimal tvaCrdini) {
		this.tvaCrdini = tvaCrdini;
	}

	@Column(name = "TVA_BASIMB", precision = 22, scale = 0)
	public BigDecimal getTvaBasimb() {
		return this.tvaBasimb;
	}

	public void setTvaBasimb(BigDecimal tvaBasimb) {
		this.tvaBasimb = tvaBasimb;
	}

	@Column(name = "TVA_DEDIMB", precision = 22, scale = 0)
	public BigDecimal getTvaDedimb() {
		return this.tvaDedimb;
	}

	public void setTvaDedimb(BigDecimal tvaDedimb) {
		this.tvaDedimb = tvaDedimb;
	}

	@Column(name = "TVA_BASEQL", precision = 22, scale = 0)
	public BigDecimal getTvaBaseql() {
		return this.tvaBaseql;
	}

	public void setTvaBaseql(BigDecimal tvaBaseql) {
		this.tvaBaseql = tvaBaseql;
	}

	@Column(name = "TVA_DEDEQL", precision = 22, scale = 0)
	public BigDecimal getTvaDedeql() {
		return this.tvaDedeql;
	}

	public void setTvaDedeql(BigDecimal tvaDedeql) {
		this.tvaDedeql = tvaDedeql;
	}

	@Column(name = "TVA_BASEQI", precision = 22, scale = 0)
	public BigDecimal getTvaBaseqi() {
		return this.tvaBaseqi;
	}

	public void setTvaBaseqi(BigDecimal tvaBaseqi) {
		this.tvaBaseqi = tvaBaseqi;
	}

	@Column(name = "TVA_DEDEQI", precision = 22, scale = 0)
	public BigDecimal getTvaDedeqi() {
		return this.tvaDedeqi;
	}

	public void setTvaDedeqi(BigDecimal tvaDedeqi) {
		this.tvaDedeqi = tvaDedeqi;
	}

	@Column(name = "TVA_BASAUL", precision = 22, scale = 0)
	public BigDecimal getTvaBasaul() {
		return this.tvaBasaul;
	}

	public void setTvaBasaul(BigDecimal tvaBasaul) {
		this.tvaBasaul = tvaBasaul;
	}

	@Column(name = "TVA_DEDAUL", precision = 22, scale = 0)
	public BigDecimal getTvaDedaul() {
		return this.tvaDedaul;
	}

	public void setTvaDedaul(BigDecimal tvaDedaul) {
		this.tvaDedaul = tvaDedaul;
	}

	@Column(name = "TVA_BASAUI", precision = 22, scale = 0)
	public BigDecimal getTvaBasaui() {
		return this.tvaBasaui;
	}

	public void setTvaBasaui(BigDecimal tvaBasaui) {
		this.tvaBasaui = tvaBasaui;
	}

	@Column(name = "TVA_DEDAUI", precision = 22, scale = 0)
	public BigDecimal getTvaDedaui() {
		return this.tvaDedaui;
	}

	public void setTvaDedaui(BigDecimal tvaDedaui) {
		this.tvaDedaui = tvaDedaui;
	}

	@Column(name = "TVA_BASRSM", precision = 22, scale = 0)
	public BigDecimal getTvaBasrsm() {
		return this.tvaBasrsm;
	}

	public void setTvaBasrsm(BigDecimal tvaBasrsm) {
		this.tvaBasrsm = tvaBasrsm;
	}

	@Column(name = "TVA_DEDRSM", precision = 22, scale = 0)
	public BigDecimal getTvaDedrsm() {
		return this.tvaDedrsm;
	}

	public void setTvaDedrsm(BigDecimal tvaDedrsm) {
		this.tvaDedrsm = tvaDedrsm;
	}

	@Column(name = "TVA_RSNRES", precision = 22, scale = 0)
	public BigDecimal getTvaRsnres() {
		return this.tvaRsnres;
	}

	public void setTvaRsnres(BigDecimal tvaRsnres) {
		this.tvaRsnres = tvaRsnres;
	}

	@Column(name = "TVA_TRSPOR", precision = 22, scale = 0)
	public BigDecimal getTvaTrspor() {
		return this.tvaTrspor;
	}

	public void setTvaTrspor(BigDecimal tvaTrspor) {
		this.tvaTrspor = tvaTrspor;
	}

	@Column(name = "TVA_DEDREG", precision = 22, scale = 0)
	public BigDecimal getTvaDedreg() {
		return this.tvaDedreg;
	}

	public void setTvaDedreg(BigDecimal tvaDedreg) {
		this.tvaDedreg = tvaDedreg;
	}

	@Column(name = "TVA_RESTIT", precision = 22, scale = 0)
	public BigDecimal getTvaRestit() {
		return this.tvaRestit;
	}

	public void setTvaRestit(BigDecimal tvaRestit) {
		this.tvaRestit = tvaRestit;
	}

	@Column(name = "TVA_MNTPAY", precision = 22, scale = 0)
	public BigDecimal getTvaMntpay() {
		return this.tvaMntpay;
	}

	public void setTvaMntpay(BigDecimal tvaMntpay) {
		this.tvaMntpay = tvaMntpay;
	}

	@Column(name = "TVA_MOIFIN", length = 2)
	public String getTvaMoifin() {
		return this.tvaMoifin;
	}

	public void setTvaMoifin(String tvaMoifin) {
		this.tvaMoifin = tvaMoifin;
	}

	@Column(name = "TVA_CRDFIN", precision = 22, scale = 0)
	public BigDecimal getTvaCrdfin() {
		return this.tvaCrdfin;
	}

	public void setTvaCrdfin(BigDecimal tvaCrdfin) {
		this.tvaCrdfin = tvaCrdfin;
	}

	@Column(name = "TVA_ACHSUS", precision = 22, scale = 0)
	public BigDecimal getTvaAchsus() {
		return this.tvaAchsus;
	}

	public void setTvaAchsus(BigDecimal tvaAchsus) {
		this.tvaAchsus = tvaAchsus;
	}

	@Column(name = "TVA_ACHEXO", precision = 22, scale = 0)
	public BigDecimal getTvaAchexo() {
		return this.tvaAchexo;
	}

	public void setTvaAchexo(BigDecimal tvaAchexo) {
		this.tvaAchexo = tvaAchexo;
	}

	@Column(name = "TVA_ACHNDD", precision = 22, scale = 0)
	public BigDecimal getTvaAchndd() {
		return this.tvaAchndd;
	}

	public void setTvaAchndd(BigDecimal tvaAchndd) {
		this.tvaAchndd = tvaAchndd;
	}

	@Column(name = "TVA_CAFEXP", precision = 22, scale = 0)
	public BigDecimal getTvaCafexp() {
		return this.tvaCafexp;
	}

	public void setTvaCafexp(BigDecimal tvaCafexp) {
		this.tvaCafexp = tvaCafexp;
	}

	@Column(name = "TVA_CAFSUS", precision = 22, scale = 0)
	public BigDecimal getTvaCafsus() {
		return this.tvaCafsus;
	}

	public void setTvaCafsus(BigDecimal tvaCafsus) {
		this.tvaCafsus = tvaCafsus;
	}

	@Column(name = "TVA_CAFEXO", precision = 22, scale = 0)
	public BigDecimal getTvaCafexo() {
		return this.tvaCafexo;
	}

	public void setTvaCafexo(BigDecimal tvaCafexo) {
		this.tvaCafexo = tvaCafexo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aAgrtvaId))
			return false;
		P3aAgrtvaId castOther = (P3aAgrtvaId) other;

		return ((this.getTvaExerci() == castOther.getTvaExerci()) || (this.getTvaExerci() != null
				&& castOther.getTvaExerci() != null && this.getTvaExerci().equals(castOther.getTvaExerci())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getTvaChaff6() == castOther.getTvaChaff6()) || (this.getTvaChaff6() != null
						&& castOther.getTvaChaff6() != null && this.getTvaChaff6().equals(castOther.getTvaChaff6())))
				&& ((this.getTvaChaff7() == castOther.getTvaChaff7()) || (this.getTvaChaff7() != null
						&& castOther.getTvaChaff7() != null && this.getTvaChaff7().equals(castOther.getTvaChaff7())))
				&& ((this.getTvaChaf10() == castOther.getTvaChaf10()) || (this.getTvaChaf10() != null
						&& castOther.getTvaChaf10() != null && this.getTvaChaf10().equals(castOther.getTvaChaf10())))
				&& ((this.getTvaChaf12() == castOther.getTvaChaf12()) || (this.getTvaChaf12() != null
						&& castOther.getTvaChaf12() != null && this.getTvaChaf12().equals(castOther.getTvaChaf12())))
				&& ((this.getTvaCaf125() == castOther.getTvaCaf125()) || (this.getTvaCaf125() != null
						&& castOther.getTvaCaf125() != null && this.getTvaCaf125().equals(castOther.getTvaCaf125())))
				&& ((this.getTvaChaf15() == castOther.getTvaChaf15()) || (this.getTvaChaf15() != null
						&& castOther.getTvaChaf15() != null && this.getTvaChaf15().equals(castOther.getTvaChaf15())))
				&& ((this.getTvaChaf18() == castOther.getTvaChaf18()) || (this.getTvaChaf18() != null
						&& castOther.getTvaChaf18() != null && this.getTvaChaf18().equals(castOther.getTvaChaf18())))
				&& ((this.getTvaChaf22() == castOther.getTvaChaf22()) || (this.getTvaChaf22() != null
						&& castOther.getTvaChaf22() != null && this.getTvaChaf22().equals(castOther.getTvaChaf22())))
				&& ((this.getTvaChaf29() == castOther.getTvaChaf29()) || (this.getTvaChaf29() != null
						&& castOther.getTvaChaf29() != null && this.getTvaChaf29().equals(castOther.getTvaChaf29())))
				&& ((this.getTvaChaf36() == castOther.getTvaChaf36()) || (this.getTvaChaf36() != null
						&& castOther.getTvaChaf36() != null && this.getTvaChaf36().equals(castOther.getTvaChaf36())))
				&& ((this.getTvaTotdue() == castOther.getTvaTotdue()) || (this.getTvaTotdue() != null
						&& castOther.getTvaTotdue() != null && this.getTvaTotdue().equals(castOther.getTvaTotdue())))
				&& ((this.getTvaMoideb() == castOther.getTvaMoideb()) || (this.getTvaMoideb() != null
						&& castOther.getTvaMoideb() != null && this.getTvaMoideb().equals(castOther.getTvaMoideb())))
				&& ((this.getTvaCrdini() == castOther.getTvaCrdini()) || (this.getTvaCrdini() != null
						&& castOther.getTvaCrdini() != null && this.getTvaCrdini().equals(castOther.getTvaCrdini())))
				&& ((this.getTvaBasimb() == castOther.getTvaBasimb()) || (this.getTvaBasimb() != null
						&& castOther.getTvaBasimb() != null && this.getTvaBasimb().equals(castOther.getTvaBasimb())))
				&& ((this.getTvaDedimb() == castOther.getTvaDedimb()) || (this.getTvaDedimb() != null
						&& castOther.getTvaDedimb() != null && this.getTvaDedimb().equals(castOther.getTvaDedimb())))
				&& ((this.getTvaBaseql() == castOther.getTvaBaseql()) || (this.getTvaBaseql() != null
						&& castOther.getTvaBaseql() != null && this.getTvaBaseql().equals(castOther.getTvaBaseql())))
				&& ((this.getTvaDedeql() == castOther.getTvaDedeql()) || (this.getTvaDedeql() != null
						&& castOther.getTvaDedeql() != null && this.getTvaDedeql().equals(castOther.getTvaDedeql())))
				&& ((this.getTvaBaseqi() == castOther.getTvaBaseqi()) || (this.getTvaBaseqi() != null
						&& castOther.getTvaBaseqi() != null && this.getTvaBaseqi().equals(castOther.getTvaBaseqi())))
				&& ((this.getTvaDedeqi() == castOther.getTvaDedeqi()) || (this.getTvaDedeqi() != null
						&& castOther.getTvaDedeqi() != null && this.getTvaDedeqi().equals(castOther.getTvaDedeqi())))
				&& ((this.getTvaBasaul() == castOther.getTvaBasaul()) || (this.getTvaBasaul() != null
						&& castOther.getTvaBasaul() != null && this.getTvaBasaul().equals(castOther.getTvaBasaul())))
				&& ((this.getTvaDedaul() == castOther.getTvaDedaul()) || (this.getTvaDedaul() != null
						&& castOther.getTvaDedaul() != null && this.getTvaDedaul().equals(castOther.getTvaDedaul())))
				&& ((this.getTvaBasaui() == castOther.getTvaBasaui()) || (this.getTvaBasaui() != null
						&& castOther.getTvaBasaui() != null && this.getTvaBasaui().equals(castOther.getTvaBasaui())))
				&& ((this.getTvaDedaui() == castOther.getTvaDedaui()) || (this.getTvaDedaui() != null
						&& castOther.getTvaDedaui() != null && this.getTvaDedaui().equals(castOther.getTvaDedaui())))
				&& ((this.getTvaBasrsm() == castOther.getTvaBasrsm()) || (this.getTvaBasrsm() != null
						&& castOther.getTvaBasrsm() != null && this.getTvaBasrsm().equals(castOther.getTvaBasrsm())))
				&& ((this.getTvaDedrsm() == castOther.getTvaDedrsm()) || (this.getTvaDedrsm() != null
						&& castOther.getTvaDedrsm() != null && this.getTvaDedrsm().equals(castOther.getTvaDedrsm())))
				&& ((this.getTvaRsnres() == castOther.getTvaRsnres()) || (this.getTvaRsnres() != null
						&& castOther.getTvaRsnres() != null && this.getTvaRsnres().equals(castOther.getTvaRsnres())))
				&& ((this.getTvaTrspor() == castOther.getTvaTrspor()) || (this.getTvaTrspor() != null
						&& castOther.getTvaTrspor() != null && this.getTvaTrspor().equals(castOther.getTvaTrspor())))
				&& ((this.getTvaDedreg() == castOther.getTvaDedreg()) || (this.getTvaDedreg() != null
						&& castOther.getTvaDedreg() != null && this.getTvaDedreg().equals(castOther.getTvaDedreg())))
				&& ((this.getTvaRestit() == castOther.getTvaRestit()) || (this.getTvaRestit() != null
						&& castOther.getTvaRestit() != null && this.getTvaRestit().equals(castOther.getTvaRestit())))
				&& ((this.getTvaMntpay() == castOther.getTvaMntpay()) || (this.getTvaMntpay() != null
						&& castOther.getTvaMntpay() != null && this.getTvaMntpay().equals(castOther.getTvaMntpay())))
				&& ((this.getTvaMoifin() == castOther.getTvaMoifin()) || (this.getTvaMoifin() != null
						&& castOther.getTvaMoifin() != null && this.getTvaMoifin().equals(castOther.getTvaMoifin())))
				&& ((this.getTvaCrdfin() == castOther.getTvaCrdfin()) || (this.getTvaCrdfin() != null
						&& castOther.getTvaCrdfin() != null && this.getTvaCrdfin().equals(castOther.getTvaCrdfin())))
				&& ((this.getTvaAchsus() == castOther.getTvaAchsus()) || (this.getTvaAchsus() != null
						&& castOther.getTvaAchsus() != null && this.getTvaAchsus().equals(castOther.getTvaAchsus())))
				&& ((this.getTvaAchexo() == castOther.getTvaAchexo()) || (this.getTvaAchexo() != null
						&& castOther.getTvaAchexo() != null && this.getTvaAchexo().equals(castOther.getTvaAchexo())))
				&& ((this.getTvaAchndd() == castOther.getTvaAchndd()) || (this.getTvaAchndd() != null
						&& castOther.getTvaAchndd() != null && this.getTvaAchndd().equals(castOther.getTvaAchndd())))
				&& ((this.getTvaCafexp() == castOther.getTvaCafexp()) || (this.getTvaCafexp() != null
						&& castOther.getTvaCafexp() != null && this.getTvaCafexp().equals(castOther.getTvaCafexp())))
				&& ((this.getTvaCafsus() == castOther.getTvaCafsus()) || (this.getTvaCafsus() != null
						&& castOther.getTvaCafsus() != null && this.getTvaCafsus().equals(castOther.getTvaCafsus())))
				&& ((this.getTvaCafexo() == castOther.getTvaCafexo()) || (this.getTvaCafexo() != null
						&& castOther.getTvaCafexo() != null && this.getTvaCafexo().equals(castOther.getTvaCafexo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTvaExerci() == null ? 0 : this.getTvaExerci().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getTvaChaff6() == null ? 0 : this.getTvaChaff6().hashCode());
		result = 37 * result + (getTvaChaff7() == null ? 0 : this.getTvaChaff7().hashCode());
		result = 37 * result + (getTvaChaf10() == null ? 0 : this.getTvaChaf10().hashCode());
		result = 37 * result + (getTvaChaf12() == null ? 0 : this.getTvaChaf12().hashCode());
		result = 37 * result + (getTvaCaf125() == null ? 0 : this.getTvaCaf125().hashCode());
		result = 37 * result + (getTvaChaf15() == null ? 0 : this.getTvaChaf15().hashCode());
		result = 37 * result + (getTvaChaf18() == null ? 0 : this.getTvaChaf18().hashCode());
		result = 37 * result + (getTvaChaf22() == null ? 0 : this.getTvaChaf22().hashCode());
		result = 37 * result + (getTvaChaf29() == null ? 0 : this.getTvaChaf29().hashCode());
		result = 37 * result + (getTvaChaf36() == null ? 0 : this.getTvaChaf36().hashCode());
		result = 37 * result + (getTvaTotdue() == null ? 0 : this.getTvaTotdue().hashCode());
		result = 37 * result + (getTvaMoideb() == null ? 0 : this.getTvaMoideb().hashCode());
		result = 37 * result + (getTvaCrdini() == null ? 0 : this.getTvaCrdini().hashCode());
		result = 37 * result + (getTvaBasimb() == null ? 0 : this.getTvaBasimb().hashCode());
		result = 37 * result + (getTvaDedimb() == null ? 0 : this.getTvaDedimb().hashCode());
		result = 37 * result + (getTvaBaseql() == null ? 0 : this.getTvaBaseql().hashCode());
		result = 37 * result + (getTvaDedeql() == null ? 0 : this.getTvaDedeql().hashCode());
		result = 37 * result + (getTvaBaseqi() == null ? 0 : this.getTvaBaseqi().hashCode());
		result = 37 * result + (getTvaDedeqi() == null ? 0 : this.getTvaDedeqi().hashCode());
		result = 37 * result + (getTvaBasaul() == null ? 0 : this.getTvaBasaul().hashCode());
		result = 37 * result + (getTvaDedaul() == null ? 0 : this.getTvaDedaul().hashCode());
		result = 37 * result + (getTvaBasaui() == null ? 0 : this.getTvaBasaui().hashCode());
		result = 37 * result + (getTvaDedaui() == null ? 0 : this.getTvaDedaui().hashCode());
		result = 37 * result + (getTvaBasrsm() == null ? 0 : this.getTvaBasrsm().hashCode());
		result = 37 * result + (getTvaDedrsm() == null ? 0 : this.getTvaDedrsm().hashCode());
		result = 37 * result + (getTvaRsnres() == null ? 0 : this.getTvaRsnres().hashCode());
		result = 37 * result + (getTvaTrspor() == null ? 0 : this.getTvaTrspor().hashCode());
		result = 37 * result + (getTvaDedreg() == null ? 0 : this.getTvaDedreg().hashCode());
		result = 37 * result + (getTvaRestit() == null ? 0 : this.getTvaRestit().hashCode());
		result = 37 * result + (getTvaMntpay() == null ? 0 : this.getTvaMntpay().hashCode());
		result = 37 * result + (getTvaMoifin() == null ? 0 : this.getTvaMoifin().hashCode());
		result = 37 * result + (getTvaCrdfin() == null ? 0 : this.getTvaCrdfin().hashCode());
		result = 37 * result + (getTvaAchsus() == null ? 0 : this.getTvaAchsus().hashCode());
		result = 37 * result + (getTvaAchexo() == null ? 0 : this.getTvaAchexo().hashCode());
		result = 37 * result + (getTvaAchndd() == null ? 0 : this.getTvaAchndd().hashCode());
		result = 37 * result + (getTvaCafexp() == null ? 0 : this.getTvaCafexp().hashCode());
		result = 37 * result + (getTvaCafsus() == null ? 0 : this.getTvaCafsus().hashCode());
		result = 37 * result + (getTvaCafexo() == null ? 0 : this.getTvaCafexo().hashCode());
		return result;
	}

}
