package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgrres generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGRRES")
public class P3aAgrres implements java.io.Serializable {

	private P3aAgrresId id;

	public P3aAgrres() {
	}

	public P3aAgrres(P3aAgrresId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "resExerci", column = @Column(name = "RES_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "resSalbas", column = @Column(name = "RES_SALBAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "resSalret", column = @Column(name = "RES_SALRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resHonass", column = @Column(name = "RES_HONASS", precision = 22, scale = 0)),
			@AttributeOverride(name = "resHonret", column = @Column(name = "RES_HONRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resHonn15", column = @Column(name = "RES_HONN15", precision = 22, scale = 0)),
			@AttributeOverride(name = "resHnrret", column = @Column(name = "RES_HNRRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resHonrra", column = @Column(name = "RES_HONRRA", precision = 22, scale = 0)),
			@AttributeOverride(name = "resHonrrr", column = @Column(name = "RES_HONRRR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resLhoass", column = @Column(name = "RES_LHOASS", precision = 22, scale = 0)),
			@AttributeOverride(name = "resLhoret", column = @Column(name = "RES_LHORET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resRedbas", column = @Column(name = "RES_REDBAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "resRedmnt", column = @Column(name = "RES_REDMNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "resCspbas", column = @Column(name = "RES_CSPBAS", precision = 22, scale = 0)),
			@AttributeOverride(name = "resCspmnt", column = @Column(name = "RES_CSPMNT", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobprb", column = @Column(name = "RES_MOBPRB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobprr", column = @Column(name = "RES_MOBPRR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobmrb", column = @Column(name = "RES_MOBMRB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobmrr", column = @Column(name = "RES_MOBMRR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobpnb", column = @Column(name = "RES_MOBPNB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobpnr", column = @Column(name = "RES_MOBPNR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobmnb", column = @Column(name = "RES_MOBMNB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMobmnr", column = @Column(name = "RES_MOBMNR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resVmoass", column = @Column(name = "RES_VMOASS", precision = 22, scale = 0)),
			@AttributeOverride(name = "resVmoret", column = @Column(name = "RES_VMORET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resJetrba", column = @Column(name = "RES_JETRBA", precision = 22, scale = 0)),
			@AttributeOverride(name = "resJetrrt", column = @Column(name = "RES_JETRRT", precision = 22, scale = 0)),
			@AttributeOverride(name = "resJetnba", column = @Column(name = "RES_JETNBA", precision = 22, scale = 0)),
			@AttributeOverride(name = "resJetnrt", column = @Column(name = "RES_JETNRT", precision = 22, scale = 0)),
			@AttributeOverride(name = "resRtpraa", column = @Column(name = "RES_RTPRAA", precision = 22, scale = 0)),
			@AttributeOverride(name = "jetRtprar", column = @Column(name = "JET_RTPRAR", precision = 22, scale = 0)),
			@AttributeOverride(name = "jetIppeba", column = @Column(name = "JET_IPPEBA", precision = 22, scale = 0)),
			@AttributeOverride(name = "resIppret", column = @Column(name = "RES_IPPRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resPidacb", column = @Column(name = "RES_PIDACB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resPirret", column = @Column(name = "RES_PIRRET", precision = 22, scale = 0)),
			@AttributeOverride(name = "resImbpnb", column = @Column(name = "RES_IMBPNB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resImbpnr", column = @Column(name = "RES_IMBPNR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resImbmnb", column = @Column(name = "RES_IMBMNB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resImbmnr", column = @Column(name = "RES_IMBMNR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMarchb", column = @Column(name = "RES_MARCHB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resMarchr", column = @Column(name = "RES_MARCHR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resTva50b", column = @Column(name = "RES_TVA50B", precision = 22, scale = 0)),
			@AttributeOverride(name = "resTva50r", column = @Column(name = "RES_TVA50R", precision = 22, scale = 0)),
			@AttributeOverride(name = "resTrsanr", column = @Column(name = "RES_TRSANR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resTrsrnr", column = @Column(name = "RES_TRSRNR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resTpfrub", column = @Column(name = "RES_TPFRUB", precision = 22, scale = 0)),
			@AttributeOverride(name = "resTplegr", column = @Column(name = "RES_TPLEGR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resCapioa", column = @Column(name = "RES_CAPIOA", precision = 22, scale = 0)),
			@AttributeOverride(name = "resCapior", column = @Column(name = "RES_CAPIOR", precision = 22, scale = 0)),
			@AttributeOverride(name = "resAvvppa", column = @Column(name = "RES_AVVPPA", precision = 13, scale = 0)),
			@AttributeOverride(name = "resAvvppr", column = @Column(name = "RES_AVVPPR", precision = 13, scale = 0)),
			@AttributeOverride(name = "resHonbea", column = @Column(name = "RES_HONBEA", precision = 13, scale = 0)),
			@AttributeOverride(name = "resHonber", column = @Column(name = "RES_HONBER", precision = 13, scale = 0)),
			@AttributeOverride(name = "resPlvcsa", column = @Column(name = "RES_PLVCSA", precision = 13, scale = 0)),
			@AttributeOverride(name = "resPlvcsr", column = @Column(name = "RES_PLVCSR", precision = 13, scale = 0)),
			@AttributeOverride(name = "resCcoass", column = @Column(name = "RES_CCOASS", precision = 13, scale = 0)),
			@AttributeOverride(name = "resCcoret", column = @Column(name = "RES_CCORET", precision = 13, scale = 0)) })
	public P3aAgrresId getId() {
		return this.id;
	}

	public void setId(P3aAgrresId id) {
		this.id = id;
	}

}
