package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aAgcnss generated by hbm2java
 */
@Entity
@Table(name = "P3A_AGCNSS")
public class P3aAgcnss implements java.io.Serializable {

	private P3aAgcnssId id;
	private BigDecimal cnsMassal;
	private BigDecimal cnsCotouv;

	public P3aAgcnss() {
	}

	public P3aAgcnss(P3aAgcnssId id) {
		this.id = id;
	}

	public P3aAgcnss(P3aAgcnssId id, BigDecimal cnsMassal, BigDecimal cnsCotouv) {
		this.id = id;
		this.cnsMassal = cnsMassal;
		this.cnsCotouv = cnsCotouv;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "cnsExerci", column = @Column(name = "CNS_EXERCI", nullable = false, length = 4)) })
	public P3aAgcnssId getId() {
		return this.id;
	}

	public void setId(P3aAgcnssId id) {
		this.id = id;
	}

	@Column(name = "CNS_MASSAL", precision = 22, scale = 0)
	public BigDecimal getCnsMassal() {
		return this.cnsMassal;
	}

	public void setCnsMassal(BigDecimal cnsMassal) {
		this.cnsMassal = cnsMassal;
	}

	@Column(name = "CNS_COTOUV", precision = 22, scale = 0)
	public BigDecimal getCnsCotouv() {
		return this.cnsCotouv;
	}

	public void setCnsCotouv(BigDecimal cnsCotouv) {
		this.cnsCotouv = cnsCotouv;
	}

}
