package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aBurcenId generated by hbm2java
 */
@Embeddable
public class P3aBurcenId implements java.io.Serializable {

	private String bctCodbur;
	private String bctLibell;
	private String bctCodcen;
	private String bctTypstr;

	public P3aBurcenId() {
	}

	public P3aBurcenId(String bctCodbur) {
		this.bctCodbur = bctCodbur;
	}

	public P3aBurcenId(String bctCodbur, String bctLibell, String bctCodcen, String bctTypstr) {
		this.bctCodbur = bctCodbur;
		this.bctLibell = bctLibell;
		this.bctCodcen = bctCodcen;
		this.bctTypstr = bctTypstr;
	}

	@Column(name = "BCT_CODBUR", nullable = false, length = 3)
	public String getBctCodbur() {
		return this.bctCodbur;
	}

	public void setBctCodbur(String bctCodbur) {
		this.bctCodbur = bctCodbur;
	}

	@Column(name = "BCT_LIBELL", length = 60)
	public String getBctLibell() {
		return this.bctLibell;
	}

	public void setBctLibell(String bctLibell) {
		this.bctLibell = bctLibell;
	}

	@Column(name = "BCT_CODCEN", length = 3)
	public String getBctCodcen() {
		return this.bctCodcen;
	}

	public void setBctCodcen(String bctCodcen) {
		this.bctCodcen = bctCodcen;
	}

	@Column(name = "BCT_TYPSTR", length = 1)
	public String getBctTypstr() {
		return this.bctTypstr;
	}

	public void setBctTypstr(String bctTypstr) {
		this.bctTypstr = bctTypstr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aBurcenId))
			return false;
		P3aBurcenId castOther = (P3aBurcenId) other;

		return ((this.getBctCodbur() == castOther.getBctCodbur()) || (this.getBctCodbur() != null
				&& castOther.getBctCodbur() != null && this.getBctCodbur().equals(castOther.getBctCodbur())))
				&& ((this.getBctLibell() == castOther.getBctLibell()) || (this.getBctLibell() != null
						&& castOther.getBctLibell() != null && this.getBctLibell().equals(castOther.getBctLibell())))
				&& ((this.getBctCodcen() == castOther.getBctCodcen()) || (this.getBctCodcen() != null
						&& castOther.getBctCodcen() != null && this.getBctCodcen().equals(castOther.getBctCodcen())))
				&& ((this.getBctTypstr() == castOther.getBctTypstr()) || (this.getBctTypstr() != null
						&& castOther.getBctTypstr() != null && this.getBctTypstr().equals(castOther.getBctTypstr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBctCodbur() == null ? 0 : this.getBctCodbur().hashCode());
		result = 37 * result + (getBctLibell() == null ? 0 : this.getBctLibell().hashCode());
		result = 37 * result + (getBctCodcen() == null ? 0 : this.getBctCodcen().hashCode());
		result = 37 * result + (getBctTypstr() == null ? 0 : this.getBctTypstr().hashCode());
		return result;
	}

}
