package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aDecirdId generated by hbm2java
 */
@Embeddable
public class P3aDecirdId implements java.io.Serializable {

	private String irpExerci;
	private String ctrMatfis;
	private String ctrCatego;
	private String ctrEtbsec;
	private String irpTyprev;
	private Long irpCafloc;
	private Long irpCafexp;
	private Long irpCafttc;
	private Long irpMrescp;
	private Long irpMresfi;
	private Long irpDedexp;
	private Long irpDedaut;

	public P3aDecirdId() {
	}

	public P3aDecirdId(String irpExerci, String ctrMatfis, String ctrEtbsec, String irpTyprev) {
		this.irpExerci = irpExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.irpTyprev = irpTyprev;
	}

	public P3aDecirdId(String irpExerci, String ctrMatfis, String ctrCatego, String ctrEtbsec, String irpTyprev,
			Long irpCafloc, Long irpCafexp, Long irpCafttc, Long irpMrescp, Long irpMresfi, Long irpDedexp,
			Long irpDedaut) {
		this.irpExerci = irpExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.irpTyprev = irpTyprev;
		this.irpCafloc = irpCafloc;
		this.irpCafexp = irpCafexp;
		this.irpCafttc = irpCafttc;
		this.irpMrescp = irpMrescp;
		this.irpMresfi = irpMresfi;
		this.irpDedexp = irpDedexp;
		this.irpDedaut = irpDedaut;
	}

	@Column(name = "IRP_EXERCI", nullable = false, length = 4)
	public String getIrpExerci() {
		return this.irpExerci;
	}

	public void setIrpExerci(String irpExerci) {
		this.irpExerci = irpExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "IRP_TYPREV", nullable = false, length = 2)
	public String getIrpTyprev() {
		return this.irpTyprev;
	}

	public void setIrpTyprev(String irpTyprev) {
		this.irpTyprev = irpTyprev;
	}

	@Column(name = "IRP_CAFLOC", precision = 13, scale = 0)
	public Long getIrpCafloc() {
		return this.irpCafloc;
	}

	public void setIrpCafloc(Long irpCafloc) {
		this.irpCafloc = irpCafloc;
	}

	@Column(name = "IRP_CAFEXP", precision = 13, scale = 0)
	public Long getIrpCafexp() {
		return this.irpCafexp;
	}

	public void setIrpCafexp(Long irpCafexp) {
		this.irpCafexp = irpCafexp;
	}

	@Column(name = "IRP_CAFTTC", precision = 13, scale = 0)
	public Long getIrpCafttc() {
		return this.irpCafttc;
	}

	public void setIrpCafttc(Long irpCafttc) {
		this.irpCafttc = irpCafttc;
	}

	@Column(name = "IRP_MRESCP", precision = 13, scale = 0)
	public Long getIrpMrescp() {
		return this.irpMrescp;
	}

	public void setIrpMrescp(Long irpMrescp) {
		this.irpMrescp = irpMrescp;
	}

	@Column(name = "IRP_MRESFI", precision = 13, scale = 0)
	public Long getIrpMresfi() {
		return this.irpMresfi;
	}

	public void setIrpMresfi(Long irpMresfi) {
		this.irpMresfi = irpMresfi;
	}

	@Column(name = "IRP_DEDEXP", precision = 13, scale = 0)
	public Long getIrpDedexp() {
		return this.irpDedexp;
	}

	public void setIrpDedexp(Long irpDedexp) {
		this.irpDedexp = irpDedexp;
	}

	@Column(name = "IRP_DEDAUT", precision = 13, scale = 0)
	public Long getIrpDedaut() {
		return this.irpDedaut;
	}

	public void setIrpDedaut(Long irpDedaut) {
		this.irpDedaut = irpDedaut;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aDecirdId))
			return false;
		P3aDecirdId castOther = (P3aDecirdId) other;

		return ((this.getIrpExerci() == castOther.getIrpExerci()) || (this.getIrpExerci() != null
				&& castOther.getIrpExerci() != null && this.getIrpExerci().equals(castOther.getIrpExerci())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getIrpTyprev() == castOther.getIrpTyprev()) || (this.getIrpTyprev() != null
						&& castOther.getIrpTyprev() != null && this.getIrpTyprev().equals(castOther.getIrpTyprev())))
				&& ((this.getIrpCafloc() == castOther.getIrpCafloc()) || (this.getIrpCafloc() != null
						&& castOther.getIrpCafloc() != null && this.getIrpCafloc().equals(castOther.getIrpCafloc())))
				&& ((this.getIrpCafexp() == castOther.getIrpCafexp()) || (this.getIrpCafexp() != null
						&& castOther.getIrpCafexp() != null && this.getIrpCafexp().equals(castOther.getIrpCafexp())))
				&& ((this.getIrpCafttc() == castOther.getIrpCafttc()) || (this.getIrpCafttc() != null
						&& castOther.getIrpCafttc() != null && this.getIrpCafttc().equals(castOther.getIrpCafttc())))
				&& ((this.getIrpMrescp() == castOther.getIrpMrescp()) || (this.getIrpMrescp() != null
						&& castOther.getIrpMrescp() != null && this.getIrpMrescp().equals(castOther.getIrpMrescp())))
				&& ((this.getIrpMresfi() == castOther.getIrpMresfi()) || (this.getIrpMresfi() != null
						&& castOther.getIrpMresfi() != null && this.getIrpMresfi().equals(castOther.getIrpMresfi())))
				&& ((this.getIrpDedexp() == castOther.getIrpDedexp()) || (this.getIrpDedexp() != null
						&& castOther.getIrpDedexp() != null && this.getIrpDedexp().equals(castOther.getIrpDedexp())))
				&& ((this.getIrpDedaut() == castOther.getIrpDedaut()) || (this.getIrpDedaut() != null
						&& castOther.getIrpDedaut() != null && this.getIrpDedaut().equals(castOther.getIrpDedaut())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIrpExerci() == null ? 0 : this.getIrpExerci().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getIrpTyprev() == null ? 0 : this.getIrpTyprev().hashCode());
		result = 37 * result + (getIrpCafloc() == null ? 0 : this.getIrpCafloc().hashCode());
		result = 37 * result + (getIrpCafexp() == null ? 0 : this.getIrpCafexp().hashCode());
		result = 37 * result + (getIrpCafttc() == null ? 0 : this.getIrpCafttc().hashCode());
		result = 37 * result + (getIrpMrescp() == null ? 0 : this.getIrpMrescp().hashCode());
		result = 37 * result + (getIrpMresfi() == null ? 0 : this.getIrpMresfi().hashCode());
		result = 37 * result + (getIrpDedexp() == null ? 0 : this.getIrpDedexp().hashCode());
		result = 37 * result + (getIrpDedaut() == null ? 0 : this.getIrpDedaut().hashCode());
		return result;
	}

}
