package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aDecirpId generated by hbm2java
 */
@Embeddable
public class P3aDecirpId implements java.io.Serializable {

	private String irpExerci;
	private String ctrMatfis;
	private String ctrCatego;
	private String ctrEtbsec;
	private String irpCatrev;
	private Long irpRevbic;
	private Long irpRevbnc;
	private Long irpRevagr;
	private Long irpRevfon;
	private Long irpTrtsal;
	private Long irpPenvia;
	private Long irpRevmob;
	private Long irpRevcap;
	private Long irpRevtrt;
	private Long irpMntaba;
	private Long irpRevaut;
	private Long irpBenexp;
	private Long irpMdeduc;
	private Long irpTotrev;
	private Long irpDedinv;
	private Long irpNetimp;
	private Long irpTotimp;
	private Long irpExeant;
	private Long irpMacpro;
	private Long irpMretso;
	private Long irpAutded;
	private Long irpMexone;

	public P3aDecirpId() {
	}

	public P3aDecirpId(String irpExerci, String ctrMatfis, String ctrEtbsec) {
		this.irpExerci = irpExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
	}

	public P3aDecirpId(String irpExerci, String ctrMatfis, String ctrCatego, String ctrEtbsec, String irpCatrev,
			Long irpRevbic, Long irpRevbnc, Long irpRevagr, Long irpRevfon, Long irpTrtsal, Long irpPenvia,
			Long irpRevmob, Long irpRevcap, Long irpRevtrt, Long irpMntaba, Long irpRevaut, Long irpBenexp,
			Long irpMdeduc, Long irpTotrev, Long irpDedinv, Long irpNetimp, Long irpTotimp, Long irpExeant,
			Long irpMacpro, Long irpMretso, Long irpAutded, Long irpMexone) {
		this.irpExerci = irpExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.irpCatrev = irpCatrev;
		this.irpRevbic = irpRevbic;
		this.irpRevbnc = irpRevbnc;
		this.irpRevagr = irpRevagr;
		this.irpRevfon = irpRevfon;
		this.irpTrtsal = irpTrtsal;
		this.irpPenvia = irpPenvia;
		this.irpRevmob = irpRevmob;
		this.irpRevcap = irpRevcap;
		this.irpRevtrt = irpRevtrt;
		this.irpMntaba = irpMntaba;
		this.irpRevaut = irpRevaut;
		this.irpBenexp = irpBenexp;
		this.irpMdeduc = irpMdeduc;
		this.irpTotrev = irpTotrev;
		this.irpDedinv = irpDedinv;
		this.irpNetimp = irpNetimp;
		this.irpTotimp = irpTotimp;
		this.irpExeant = irpExeant;
		this.irpMacpro = irpMacpro;
		this.irpMretso = irpMretso;
		this.irpAutded = irpAutded;
		this.irpMexone = irpMexone;
	}

	@Column(name = "IRP_EXERCI", nullable = false, length = 4)
	public String getIrpExerci() {
		return this.irpExerci;
	}

	public void setIrpExerci(String irpExerci) {
		this.irpExerci = irpExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "IRP_CATREV", length = 17)
	public String getIrpCatrev() {
		return this.irpCatrev;
	}

	public void setIrpCatrev(String irpCatrev) {
		this.irpCatrev = irpCatrev;
	}

	@Column(name = "IRP_REVBIC", precision = 13, scale = 0)
	public Long getIrpRevbic() {
		return this.irpRevbic;
	}

	public void setIrpRevbic(Long irpRevbic) {
		this.irpRevbic = irpRevbic;
	}

	@Column(name = "IRP_REVBNC", precision = 13, scale = 0)
	public Long getIrpRevbnc() {
		return this.irpRevbnc;
	}

	public void setIrpRevbnc(Long irpRevbnc) {
		this.irpRevbnc = irpRevbnc;
	}

	@Column(name = "IRP_REVAGR", precision = 13, scale = 0)
	public Long getIrpRevagr() {
		return this.irpRevagr;
	}

	public void setIrpRevagr(Long irpRevagr) {
		this.irpRevagr = irpRevagr;
	}

	@Column(name = "IRP_REVFON", precision = 13, scale = 0)
	public Long getIrpRevfon() {
		return this.irpRevfon;
	}

	public void setIrpRevfon(Long irpRevfon) {
		this.irpRevfon = irpRevfon;
	}

	@Column(name = "IRP_TRTSAL", precision = 13, scale = 0)
	public Long getIrpTrtsal() {
		return this.irpTrtsal;
	}

	public void setIrpTrtsal(Long irpTrtsal) {
		this.irpTrtsal = irpTrtsal;
	}

	@Column(name = "IRP_PENVIA", precision = 13, scale = 0)
	public Long getIrpPenvia() {
		return this.irpPenvia;
	}

	public void setIrpPenvia(Long irpPenvia) {
		this.irpPenvia = irpPenvia;
	}

	@Column(name = "IRP_REVMOB", precision = 13, scale = 0)
	public Long getIrpRevmob() {
		return this.irpRevmob;
	}

	public void setIrpRevmob(Long irpRevmob) {
		this.irpRevmob = irpRevmob;
	}

	@Column(name = "IRP_REVCAP", precision = 13, scale = 0)
	public Long getIrpRevcap() {
		return this.irpRevcap;
	}

	public void setIrpRevcap(Long irpRevcap) {
		this.irpRevcap = irpRevcap;
	}

	@Column(name = "IRP_REVTRT", precision = 13, scale = 0)
	public Long getIrpRevtrt() {
		return this.irpRevtrt;
	}

	public void setIrpRevtrt(Long irpRevtrt) {
		this.irpRevtrt = irpRevtrt;
	}

	@Column(name = "IRP_MNTABA", precision = 13, scale = 0)
	public Long getIrpMntaba() {
		return this.irpMntaba;
	}

	public void setIrpMntaba(Long irpMntaba) {
		this.irpMntaba = irpMntaba;
	}

	@Column(name = "IRP_REVAUT", precision = 13, scale = 0)
	public Long getIrpRevaut() {
		return this.irpRevaut;
	}

	public void setIrpRevaut(Long irpRevaut) {
		this.irpRevaut = irpRevaut;
	}

	@Column(name = "IRP_BENEXP", precision = 13, scale = 0)
	public Long getIrpBenexp() {
		return this.irpBenexp;
	}

	public void setIrpBenexp(Long irpBenexp) {
		this.irpBenexp = irpBenexp;
	}

	@Column(name = "IRP_MDEDUC", precision = 13, scale = 0)
	public Long getIrpMdeduc() {
		return this.irpMdeduc;
	}

	public void setIrpMdeduc(Long irpMdeduc) {
		this.irpMdeduc = irpMdeduc;
	}

	@Column(name = "IRP_TOTREV", precision = 13, scale = 0)
	public Long getIrpTotrev() {
		return this.irpTotrev;
	}

	public void setIrpTotrev(Long irpTotrev) {
		this.irpTotrev = irpTotrev;
	}

	@Column(name = "IRP_DEDINV", precision = 13, scale = 0)
	public Long getIrpDedinv() {
		return this.irpDedinv;
	}

	public void setIrpDedinv(Long irpDedinv) {
		this.irpDedinv = irpDedinv;
	}

	@Column(name = "IRP_NETIMP", precision = 13, scale = 0)
	public Long getIrpNetimp() {
		return this.irpNetimp;
	}

	public void setIrpNetimp(Long irpNetimp) {
		this.irpNetimp = irpNetimp;
	}

	@Column(name = "IRP_TOTIMP", precision = 13, scale = 0)
	public Long getIrpTotimp() {
		return this.irpTotimp;
	}

	public void setIrpTotimp(Long irpTotimp) {
		this.irpTotimp = irpTotimp;
	}

	@Column(name = "IRP_EXEANT", precision = 13, scale = 0)
	public Long getIrpExeant() {
		return this.irpExeant;
	}

	public void setIrpExeant(Long irpExeant) {
		this.irpExeant = irpExeant;
	}

	@Column(name = "IRP_MACPRO", precision = 13, scale = 0)
	public Long getIrpMacpro() {
		return this.irpMacpro;
	}

	public void setIrpMacpro(Long irpMacpro) {
		this.irpMacpro = irpMacpro;
	}

	@Column(name = "IRP_MRETSO", precision = 13, scale = 0)
	public Long getIrpMretso() {
		return this.irpMretso;
	}

	public void setIrpMretso(Long irpMretso) {
		this.irpMretso = irpMretso;
	}

	@Column(name = "IRP_AUTDED", precision = 13, scale = 0)
	public Long getIrpAutded() {
		return this.irpAutded;
	}

	public void setIrpAutded(Long irpAutded) {
		this.irpAutded = irpAutded;
	}

	@Column(name = "IRP_MEXONE", precision = 13, scale = 0)
	public Long getIrpMexone() {
		return this.irpMexone;
	}

	public void setIrpMexone(Long irpMexone) {
		this.irpMexone = irpMexone;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aDecirpId))
			return false;
		P3aDecirpId castOther = (P3aDecirpId) other;

		return ((this.getIrpExerci() == castOther.getIrpExerci()) || (this.getIrpExerci() != null
				&& castOther.getIrpExerci() != null && this.getIrpExerci().equals(castOther.getIrpExerci())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getIrpCatrev() == castOther.getIrpCatrev()) || (this.getIrpCatrev() != null
						&& castOther.getIrpCatrev() != null && this.getIrpCatrev().equals(castOther.getIrpCatrev())))
				&& ((this.getIrpRevbic() == castOther.getIrpRevbic()) || (this.getIrpRevbic() != null
						&& castOther.getIrpRevbic() != null && this.getIrpRevbic().equals(castOther.getIrpRevbic())))
				&& ((this.getIrpRevbnc() == castOther.getIrpRevbnc()) || (this.getIrpRevbnc() != null
						&& castOther.getIrpRevbnc() != null && this.getIrpRevbnc().equals(castOther.getIrpRevbnc())))
				&& ((this.getIrpRevagr() == castOther.getIrpRevagr()) || (this.getIrpRevagr() != null
						&& castOther.getIrpRevagr() != null && this.getIrpRevagr().equals(castOther.getIrpRevagr())))
				&& ((this.getIrpRevfon() == castOther.getIrpRevfon()) || (this.getIrpRevfon() != null
						&& castOther.getIrpRevfon() != null && this.getIrpRevfon().equals(castOther.getIrpRevfon())))
				&& ((this.getIrpTrtsal() == castOther.getIrpTrtsal()) || (this.getIrpTrtsal() != null
						&& castOther.getIrpTrtsal() != null && this.getIrpTrtsal().equals(castOther.getIrpTrtsal())))
				&& ((this.getIrpPenvia() == castOther.getIrpPenvia()) || (this.getIrpPenvia() != null
						&& castOther.getIrpPenvia() != null && this.getIrpPenvia().equals(castOther.getIrpPenvia())))
				&& ((this.getIrpRevmob() == castOther.getIrpRevmob()) || (this.getIrpRevmob() != null
						&& castOther.getIrpRevmob() != null && this.getIrpRevmob().equals(castOther.getIrpRevmob())))
				&& ((this.getIrpRevcap() == castOther.getIrpRevcap()) || (this.getIrpRevcap() != null
						&& castOther.getIrpRevcap() != null && this.getIrpRevcap().equals(castOther.getIrpRevcap())))
				&& ((this.getIrpRevtrt() == castOther.getIrpRevtrt()) || (this.getIrpRevtrt() != null
						&& castOther.getIrpRevtrt() != null && this.getIrpRevtrt().equals(castOther.getIrpRevtrt())))
				&& ((this.getIrpMntaba() == castOther.getIrpMntaba()) || (this.getIrpMntaba() != null
						&& castOther.getIrpMntaba() != null && this.getIrpMntaba().equals(castOther.getIrpMntaba())))
				&& ((this.getIrpRevaut() == castOther.getIrpRevaut()) || (this.getIrpRevaut() != null
						&& castOther.getIrpRevaut() != null && this.getIrpRevaut().equals(castOther.getIrpRevaut())))
				&& ((this.getIrpBenexp() == castOther.getIrpBenexp()) || (this.getIrpBenexp() != null
						&& castOther.getIrpBenexp() != null && this.getIrpBenexp().equals(castOther.getIrpBenexp())))
				&& ((this.getIrpMdeduc() == castOther.getIrpMdeduc()) || (this.getIrpMdeduc() != null
						&& castOther.getIrpMdeduc() != null && this.getIrpMdeduc().equals(castOther.getIrpMdeduc())))
				&& ((this.getIrpTotrev() == castOther.getIrpTotrev()) || (this.getIrpTotrev() != null
						&& castOther.getIrpTotrev() != null && this.getIrpTotrev().equals(castOther.getIrpTotrev())))
				&& ((this.getIrpDedinv() == castOther.getIrpDedinv()) || (this.getIrpDedinv() != null
						&& castOther.getIrpDedinv() != null && this.getIrpDedinv().equals(castOther.getIrpDedinv())))
				&& ((this.getIrpNetimp() == castOther.getIrpNetimp()) || (this.getIrpNetimp() != null
						&& castOther.getIrpNetimp() != null && this.getIrpNetimp().equals(castOther.getIrpNetimp())))
				&& ((this.getIrpTotimp() == castOther.getIrpTotimp()) || (this.getIrpTotimp() != null
						&& castOther.getIrpTotimp() != null && this.getIrpTotimp().equals(castOther.getIrpTotimp())))
				&& ((this.getIrpExeant() == castOther.getIrpExeant()) || (this.getIrpExeant() != null
						&& castOther.getIrpExeant() != null && this.getIrpExeant().equals(castOther.getIrpExeant())))
				&& ((this.getIrpMacpro() == castOther.getIrpMacpro()) || (this.getIrpMacpro() != null
						&& castOther.getIrpMacpro() != null && this.getIrpMacpro().equals(castOther.getIrpMacpro())))
				&& ((this.getIrpMretso() == castOther.getIrpMretso()) || (this.getIrpMretso() != null
						&& castOther.getIrpMretso() != null && this.getIrpMretso().equals(castOther.getIrpMretso())))
				&& ((this.getIrpAutded() == castOther.getIrpAutded()) || (this.getIrpAutded() != null
						&& castOther.getIrpAutded() != null && this.getIrpAutded().equals(castOther.getIrpAutded())))
				&& ((this.getIrpMexone() == castOther.getIrpMexone()) || (this.getIrpMexone() != null
						&& castOther.getIrpMexone() != null && this.getIrpMexone().equals(castOther.getIrpMexone())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIrpExerci() == null ? 0 : this.getIrpExerci().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getIrpCatrev() == null ? 0 : this.getIrpCatrev().hashCode());
		result = 37 * result + (getIrpRevbic() == null ? 0 : this.getIrpRevbic().hashCode());
		result = 37 * result + (getIrpRevbnc() == null ? 0 : this.getIrpRevbnc().hashCode());
		result = 37 * result + (getIrpRevagr() == null ? 0 : this.getIrpRevagr().hashCode());
		result = 37 * result + (getIrpRevfon() == null ? 0 : this.getIrpRevfon().hashCode());
		result = 37 * result + (getIrpTrtsal() == null ? 0 : this.getIrpTrtsal().hashCode());
		result = 37 * result + (getIrpPenvia() == null ? 0 : this.getIrpPenvia().hashCode());
		result = 37 * result + (getIrpRevmob() == null ? 0 : this.getIrpRevmob().hashCode());
		result = 37 * result + (getIrpRevcap() == null ? 0 : this.getIrpRevcap().hashCode());
		result = 37 * result + (getIrpRevtrt() == null ? 0 : this.getIrpRevtrt().hashCode());
		result = 37 * result + (getIrpMntaba() == null ? 0 : this.getIrpMntaba().hashCode());
		result = 37 * result + (getIrpRevaut() == null ? 0 : this.getIrpRevaut().hashCode());
		result = 37 * result + (getIrpBenexp() == null ? 0 : this.getIrpBenexp().hashCode());
		result = 37 * result + (getIrpMdeduc() == null ? 0 : this.getIrpMdeduc().hashCode());
		result = 37 * result + (getIrpTotrev() == null ? 0 : this.getIrpTotrev().hashCode());
		result = 37 * result + (getIrpDedinv() == null ? 0 : this.getIrpDedinv().hashCode());
		result = 37 * result + (getIrpNetimp() == null ? 0 : this.getIrpNetimp().hashCode());
		result = 37 * result + (getIrpTotimp() == null ? 0 : this.getIrpTotimp().hashCode());
		result = 37 * result + (getIrpExeant() == null ? 0 : this.getIrpExeant().hashCode());
		result = 37 * result + (getIrpMacpro() == null ? 0 : this.getIrpMacpro().hashCode());
		result = 37 * result + (getIrpMretso() == null ? 0 : this.getIrpMretso().hashCode());
		result = 37 * result + (getIrpAutded() == null ? 0 : this.getIrpAutded().hashCode());
		result = 37 * result + (getIrpMexone() == null ? 0 : this.getIrpMexone().hashCode());
		return result;
	}

}
