package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aDecsocId generated by hbm2java
 */
@Embeddable
public class P3aDecsocId implements java.io.Serializable {

	private String imsExerci;
	private String ctrMatfis;
	private String ctrEtbsec;
	private String imsTypsoc;
	private Long imsStkdeb;
	private Long imsStkfin;
	private Long imsMachat;
	private Long imsCafloc;
	private Long imsCafexp;
	private Long imsCaft10;
	private Long imsCaft20;
	private Long imsCaft35;
	private Long imsCafttc;
	private String imsCrescp;
	private Long imsMrescp;
	private String imsCresfi;
	private Long imsMresfi;
	private Long imsBenf10;
	private Long imsBenf20;
	private Long imsBenf35;
	private Long imsDeduc1;
	private Long imsDeduc2;
	private Long imsDeduc3;
	private Long imsBeni10;
	private Long imsBeni20;
	private Long imsBeni35;
	private Long imsImpodu;
	private Long imsMexean;
	private Long imsMacpro;
	private Long imsMretso;
	private Long imsRestit;
	private Long imsMntpay;
	private Long imsReport;
	private Long imsBennso;
	private String imsTypdec;

	public P3aDecsocId() {
	}

	public P3aDecsocId(String imsExerci, String ctrMatfis, String ctrEtbsec) {
		this.imsExerci = imsExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
	}

	public P3aDecsocId(String imsExerci, String ctrMatfis, String ctrEtbsec, String imsTypsoc, Long imsStkdeb,
			Long imsStkfin, Long imsMachat, Long imsCafloc, Long imsCafexp, Long imsCaft10, Long imsCaft20,
			Long imsCaft35, Long imsCafttc, String imsCrescp, Long imsMrescp, String imsCresfi, Long imsMresfi,
			Long imsBenf10, Long imsBenf20, Long imsBenf35, Long imsDeduc1, Long imsDeduc2, Long imsDeduc3,
			Long imsBeni10, Long imsBeni20, Long imsBeni35, Long imsImpodu, Long imsMexean, Long imsMacpro,
			Long imsMretso, Long imsRestit, Long imsMntpay, Long imsReport, Long imsBennso, String imsTypdec) {
		this.imsExerci = imsExerci;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.imsTypsoc = imsTypsoc;
		this.imsStkdeb = imsStkdeb;
		this.imsStkfin = imsStkfin;
		this.imsMachat = imsMachat;
		this.imsCafloc = imsCafloc;
		this.imsCafexp = imsCafexp;
		this.imsCaft10 = imsCaft10;
		this.imsCaft20 = imsCaft20;
		this.imsCaft35 = imsCaft35;
		this.imsCafttc = imsCafttc;
		this.imsCrescp = imsCrescp;
		this.imsMrescp = imsMrescp;
		this.imsCresfi = imsCresfi;
		this.imsMresfi = imsMresfi;
		this.imsBenf10 = imsBenf10;
		this.imsBenf20 = imsBenf20;
		this.imsBenf35 = imsBenf35;
		this.imsDeduc1 = imsDeduc1;
		this.imsDeduc2 = imsDeduc2;
		this.imsDeduc3 = imsDeduc3;
		this.imsBeni10 = imsBeni10;
		this.imsBeni20 = imsBeni20;
		this.imsBeni35 = imsBeni35;
		this.imsImpodu = imsImpodu;
		this.imsMexean = imsMexean;
		this.imsMacpro = imsMacpro;
		this.imsMretso = imsMretso;
		this.imsRestit = imsRestit;
		this.imsMntpay = imsMntpay;
		this.imsReport = imsReport;
		this.imsBennso = imsBennso;
		this.imsTypdec = imsTypdec;
	}

	@Column(name = "IMS_EXERCI", nullable = false, length = 4)
	public String getImsExerci() {
		return this.imsExerci;
	}

	public void setImsExerci(String imsExerci) {
		this.imsExerci = imsExerci;
	}

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "IMS_TYPSOC", length = 1)
	public String getImsTypsoc() {
		return this.imsTypsoc;
	}

	public void setImsTypsoc(String imsTypsoc) {
		this.imsTypsoc = imsTypsoc;
	}

	@Column(name = "IMS_STKDEB", precision = 14, scale = 0)
	public Long getImsStkdeb() {
		return this.imsStkdeb;
	}

	public void setImsStkdeb(Long imsStkdeb) {
		this.imsStkdeb = imsStkdeb;
	}

	@Column(name = "IMS_STKFIN", precision = 14, scale = 0)
	public Long getImsStkfin() {
		return this.imsStkfin;
	}

	public void setImsStkfin(Long imsStkfin) {
		this.imsStkfin = imsStkfin;
	}

	@Column(name = "IMS_MACHAT", precision = 14, scale = 0)
	public Long getImsMachat() {
		return this.imsMachat;
	}

	public void setImsMachat(Long imsMachat) {
		this.imsMachat = imsMachat;
	}

	@Column(name = "IMS_CAFLOC", precision = 14, scale = 0)
	public Long getImsCafloc() {
		return this.imsCafloc;
	}

	public void setImsCafloc(Long imsCafloc) {
		this.imsCafloc = imsCafloc;
	}

	@Column(name = "IMS_CAFEXP", precision = 14, scale = 0)
	public Long getImsCafexp() {
		return this.imsCafexp;
	}

	public void setImsCafexp(Long imsCafexp) {
		this.imsCafexp = imsCafexp;
	}

	@Column(name = "IMS_CAFT10", precision = 14, scale = 0)
	public Long getImsCaft10() {
		return this.imsCaft10;
	}

	public void setImsCaft10(Long imsCaft10) {
		this.imsCaft10 = imsCaft10;
	}

	@Column(name = "IMS_CAFT20", precision = 14, scale = 0)
	public Long getImsCaft20() {
		return this.imsCaft20;
	}

	public void setImsCaft20(Long imsCaft20) {
		this.imsCaft20 = imsCaft20;
	}

	@Column(name = "IMS_CAFT35", precision = 14, scale = 0)
	public Long getImsCaft35() {
		return this.imsCaft35;
	}

	public void setImsCaft35(Long imsCaft35) {
		this.imsCaft35 = imsCaft35;
	}

	@Column(name = "IMS_CAFTTC", precision = 14, scale = 0)
	public Long getImsCafttc() {
		return this.imsCafttc;
	}

	public void setImsCafttc(Long imsCafttc) {
		this.imsCafttc = imsCafttc;
	}

	@Column(name = "IMS_CRESCP", length = 240)
	public String getImsCrescp() {
		return this.imsCrescp;
	}

	public void setImsCrescp(String imsCrescp) {
		this.imsCrescp = imsCrescp;
	}

	@Column(name = "IMS_MRESCP", precision = 14, scale = 0)
	public Long getImsMrescp() {
		return this.imsMrescp;
	}

	public void setImsMrescp(Long imsMrescp) {
		this.imsMrescp = imsMrescp;
	}

	@Column(name = "IMS_CRESFI", length = 13)
	public String getImsCresfi() {
		return this.imsCresfi;
	}

	public void setImsCresfi(String imsCresfi) {
		this.imsCresfi = imsCresfi;
	}

	@Column(name = "IMS_MRESFI", precision = 14, scale = 0)
	public Long getImsMresfi() {
		return this.imsMresfi;
	}

	public void setImsMresfi(Long imsMresfi) {
		this.imsMresfi = imsMresfi;
	}

	@Column(name = "IMS_BENF10", precision = 14, scale = 0)
	public Long getImsBenf10() {
		return this.imsBenf10;
	}

	public void setImsBenf10(Long imsBenf10) {
		this.imsBenf10 = imsBenf10;
	}

	@Column(name = "IMS_BENF20", precision = 14, scale = 0)
	public Long getImsBenf20() {
		return this.imsBenf20;
	}

	public void setImsBenf20(Long imsBenf20) {
		this.imsBenf20 = imsBenf20;
	}

	@Column(name = "IMS_BENF35", precision = 14, scale = 0)
	public Long getImsBenf35() {
		return this.imsBenf35;
	}

	public void setImsBenf35(Long imsBenf35) {
		this.imsBenf35 = imsBenf35;
	}

	@Column(name = "IMS_DEDUC1", precision = 14, scale = 0)
	public Long getImsDeduc1() {
		return this.imsDeduc1;
	}

	public void setImsDeduc1(Long imsDeduc1) {
		this.imsDeduc1 = imsDeduc1;
	}

	@Column(name = "IMS_DEDUC2", precision = 14, scale = 0)
	public Long getImsDeduc2() {
		return this.imsDeduc2;
	}

	public void setImsDeduc2(Long imsDeduc2) {
		this.imsDeduc2 = imsDeduc2;
	}

	@Column(name = "IMS_DEDUC3", precision = 14, scale = 0)
	public Long getImsDeduc3() {
		return this.imsDeduc3;
	}

	public void setImsDeduc3(Long imsDeduc3) {
		this.imsDeduc3 = imsDeduc3;
	}

	@Column(name = "IMS_BENI10", precision = 14, scale = 0)
	public Long getImsBeni10() {
		return this.imsBeni10;
	}

	public void setImsBeni10(Long imsBeni10) {
		this.imsBeni10 = imsBeni10;
	}

	@Column(name = "IMS_BENI20", precision = 14, scale = 0)
	public Long getImsBeni20() {
		return this.imsBeni20;
	}

	public void setImsBeni20(Long imsBeni20) {
		this.imsBeni20 = imsBeni20;
	}

	@Column(name = "IMS_BENI35", precision = 14, scale = 0)
	public Long getImsBeni35() {
		return this.imsBeni35;
	}

	public void setImsBeni35(Long imsBeni35) {
		this.imsBeni35 = imsBeni35;
	}

	@Column(name = "IMS_IMPODU", precision = 14, scale = 0)
	public Long getImsImpodu() {
		return this.imsImpodu;
	}

	public void setImsImpodu(Long imsImpodu) {
		this.imsImpodu = imsImpodu;
	}

	@Column(name = "IMS_MEXEAN", precision = 14, scale = 0)
	public Long getImsMexean() {
		return this.imsMexean;
	}

	public void setImsMexean(Long imsMexean) {
		this.imsMexean = imsMexean;
	}

	@Column(name = "IMS_MACPRO", precision = 14, scale = 0)
	public Long getImsMacpro() {
		return this.imsMacpro;
	}

	public void setImsMacpro(Long imsMacpro) {
		this.imsMacpro = imsMacpro;
	}

	@Column(name = "IMS_MRETSO", precision = 14, scale = 0)
	public Long getImsMretso() {
		return this.imsMretso;
	}

	public void setImsMretso(Long imsMretso) {
		this.imsMretso = imsMretso;
	}

	@Column(name = "IMS_RESTIT", precision = 14, scale = 0)
	public Long getImsRestit() {
		return this.imsRestit;
	}

	public void setImsRestit(Long imsRestit) {
		this.imsRestit = imsRestit;
	}

	@Column(name = "IMS_MNTPAY", precision = 14, scale = 0)
	public Long getImsMntpay() {
		return this.imsMntpay;
	}

	public void setImsMntpay(Long imsMntpay) {
		this.imsMntpay = imsMntpay;
	}

	@Column(name = "IMS_REPORT", precision = 14, scale = 0)
	public Long getImsReport() {
		return this.imsReport;
	}

	public void setImsReport(Long imsReport) {
		this.imsReport = imsReport;
	}

	@Column(name = "IMS_BENNSO", precision = 14, scale = 0)
	public Long getImsBennso() {
		return this.imsBennso;
	}

	public void setImsBennso(Long imsBennso) {
		this.imsBennso = imsBennso;
	}

	@Column(name = "IMS_TYPDEC", length = 2)
	public String getImsTypdec() {
		return this.imsTypdec;
	}

	public void setImsTypdec(String imsTypdec) {
		this.imsTypdec = imsTypdec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aDecsocId))
			return false;
		P3aDecsocId castOther = (P3aDecsocId) other;

		return ((this.getImsExerci() == castOther.getImsExerci()) || (this.getImsExerci() != null
				&& castOther.getImsExerci() != null && this.getImsExerci().equals(castOther.getImsExerci())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getImsTypsoc() == castOther.getImsTypsoc()) || (this.getImsTypsoc() != null
						&& castOther.getImsTypsoc() != null && this.getImsTypsoc().equals(castOther.getImsTypsoc())))
				&& ((this.getImsStkdeb() == castOther.getImsStkdeb()) || (this.getImsStkdeb() != null
						&& castOther.getImsStkdeb() != null && this.getImsStkdeb().equals(castOther.getImsStkdeb())))
				&& ((this.getImsStkfin() == castOther.getImsStkfin()) || (this.getImsStkfin() != null
						&& castOther.getImsStkfin() != null && this.getImsStkfin().equals(castOther.getImsStkfin())))
				&& ((this.getImsMachat() == castOther.getImsMachat()) || (this.getImsMachat() != null
						&& castOther.getImsMachat() != null && this.getImsMachat().equals(castOther.getImsMachat())))
				&& ((this.getImsCafloc() == castOther.getImsCafloc()) || (this.getImsCafloc() != null
						&& castOther.getImsCafloc() != null && this.getImsCafloc().equals(castOther.getImsCafloc())))
				&& ((this.getImsCafexp() == castOther.getImsCafexp()) || (this.getImsCafexp() != null
						&& castOther.getImsCafexp() != null && this.getImsCafexp().equals(castOther.getImsCafexp())))
				&& ((this.getImsCaft10() == castOther.getImsCaft10()) || (this.getImsCaft10() != null
						&& castOther.getImsCaft10() != null && this.getImsCaft10().equals(castOther.getImsCaft10())))
				&& ((this.getImsCaft20() == castOther.getImsCaft20()) || (this.getImsCaft20() != null
						&& castOther.getImsCaft20() != null && this.getImsCaft20().equals(castOther.getImsCaft20())))
				&& ((this.getImsCaft35() == castOther.getImsCaft35()) || (this.getImsCaft35() != null
						&& castOther.getImsCaft35() != null && this.getImsCaft35().equals(castOther.getImsCaft35())))
				&& ((this.getImsCafttc() == castOther.getImsCafttc()) || (this.getImsCafttc() != null
						&& castOther.getImsCafttc() != null && this.getImsCafttc().equals(castOther.getImsCafttc())))
				&& ((this.getImsCrescp() == castOther.getImsCrescp()) || (this.getImsCrescp() != null
						&& castOther.getImsCrescp() != null && this.getImsCrescp().equals(castOther.getImsCrescp())))
				&& ((this.getImsMrescp() == castOther.getImsMrescp()) || (this.getImsMrescp() != null
						&& castOther.getImsMrescp() != null && this.getImsMrescp().equals(castOther.getImsMrescp())))
				&& ((this.getImsCresfi() == castOther.getImsCresfi()) || (this.getImsCresfi() != null
						&& castOther.getImsCresfi() != null && this.getImsCresfi().equals(castOther.getImsCresfi())))
				&& ((this.getImsMresfi() == castOther.getImsMresfi()) || (this.getImsMresfi() != null
						&& castOther.getImsMresfi() != null && this.getImsMresfi().equals(castOther.getImsMresfi())))
				&& ((this.getImsBenf10() == castOther.getImsBenf10()) || (this.getImsBenf10() != null
						&& castOther.getImsBenf10() != null && this.getImsBenf10().equals(castOther.getImsBenf10())))
				&& ((this.getImsBenf20() == castOther.getImsBenf20()) || (this.getImsBenf20() != null
						&& castOther.getImsBenf20() != null && this.getImsBenf20().equals(castOther.getImsBenf20())))
				&& ((this.getImsBenf35() == castOther.getImsBenf35()) || (this.getImsBenf35() != null
						&& castOther.getImsBenf35() != null && this.getImsBenf35().equals(castOther.getImsBenf35())))
				&& ((this.getImsDeduc1() == castOther.getImsDeduc1()) || (this.getImsDeduc1() != null
						&& castOther.getImsDeduc1() != null && this.getImsDeduc1().equals(castOther.getImsDeduc1())))
				&& ((this.getImsDeduc2() == castOther.getImsDeduc2()) || (this.getImsDeduc2() != null
						&& castOther.getImsDeduc2() != null && this.getImsDeduc2().equals(castOther.getImsDeduc2())))
				&& ((this.getImsDeduc3() == castOther.getImsDeduc3()) || (this.getImsDeduc3() != null
						&& castOther.getImsDeduc3() != null && this.getImsDeduc3().equals(castOther.getImsDeduc3())))
				&& ((this.getImsBeni10() == castOther.getImsBeni10()) || (this.getImsBeni10() != null
						&& castOther.getImsBeni10() != null && this.getImsBeni10().equals(castOther.getImsBeni10())))
				&& ((this.getImsBeni20() == castOther.getImsBeni20()) || (this.getImsBeni20() != null
						&& castOther.getImsBeni20() != null && this.getImsBeni20().equals(castOther.getImsBeni20())))
				&& ((this.getImsBeni35() == castOther.getImsBeni35()) || (this.getImsBeni35() != null
						&& castOther.getImsBeni35() != null && this.getImsBeni35().equals(castOther.getImsBeni35())))
				&& ((this.getImsImpodu() == castOther.getImsImpodu()) || (this.getImsImpodu() != null
						&& castOther.getImsImpodu() != null && this.getImsImpodu().equals(castOther.getImsImpodu())))
				&& ((this.getImsMexean() == castOther.getImsMexean()) || (this.getImsMexean() != null
						&& castOther.getImsMexean() != null && this.getImsMexean().equals(castOther.getImsMexean())))
				&& ((this.getImsMacpro() == castOther.getImsMacpro()) || (this.getImsMacpro() != null
						&& castOther.getImsMacpro() != null && this.getImsMacpro().equals(castOther.getImsMacpro())))
				&& ((this.getImsMretso() == castOther.getImsMretso()) || (this.getImsMretso() != null
						&& castOther.getImsMretso() != null && this.getImsMretso().equals(castOther.getImsMretso())))
				&& ((this.getImsRestit() == castOther.getImsRestit()) || (this.getImsRestit() != null
						&& castOther.getImsRestit() != null && this.getImsRestit().equals(castOther.getImsRestit())))
				&& ((this.getImsMntpay() == castOther.getImsMntpay()) || (this.getImsMntpay() != null
						&& castOther.getImsMntpay() != null && this.getImsMntpay().equals(castOther.getImsMntpay())))
				&& ((this.getImsReport() == castOther.getImsReport()) || (this.getImsReport() != null
						&& castOther.getImsReport() != null && this.getImsReport().equals(castOther.getImsReport())))
				&& ((this.getImsBennso() == castOther.getImsBennso()) || (this.getImsBennso() != null
						&& castOther.getImsBennso() != null && this.getImsBennso().equals(castOther.getImsBennso())))
				&& ((this.getImsTypdec() == castOther.getImsTypdec()) || (this.getImsTypdec() != null
						&& castOther.getImsTypdec() != null && this.getImsTypdec().equals(castOther.getImsTypdec())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImsExerci() == null ? 0 : this.getImsExerci().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getImsTypsoc() == null ? 0 : this.getImsTypsoc().hashCode());
		result = 37 * result + (getImsStkdeb() == null ? 0 : this.getImsStkdeb().hashCode());
		result = 37 * result + (getImsStkfin() == null ? 0 : this.getImsStkfin().hashCode());
		result = 37 * result + (getImsMachat() == null ? 0 : this.getImsMachat().hashCode());
		result = 37 * result + (getImsCafloc() == null ? 0 : this.getImsCafloc().hashCode());
		result = 37 * result + (getImsCafexp() == null ? 0 : this.getImsCafexp().hashCode());
		result = 37 * result + (getImsCaft10() == null ? 0 : this.getImsCaft10().hashCode());
		result = 37 * result + (getImsCaft20() == null ? 0 : this.getImsCaft20().hashCode());
		result = 37 * result + (getImsCaft35() == null ? 0 : this.getImsCaft35().hashCode());
		result = 37 * result + (getImsCafttc() == null ? 0 : this.getImsCafttc().hashCode());
		result = 37 * result + (getImsCrescp() == null ? 0 : this.getImsCrescp().hashCode());
		result = 37 * result + (getImsMrescp() == null ? 0 : this.getImsMrescp().hashCode());
		result = 37 * result + (getImsCresfi() == null ? 0 : this.getImsCresfi().hashCode());
		result = 37 * result + (getImsMresfi() == null ? 0 : this.getImsMresfi().hashCode());
		result = 37 * result + (getImsBenf10() == null ? 0 : this.getImsBenf10().hashCode());
		result = 37 * result + (getImsBenf20() == null ? 0 : this.getImsBenf20().hashCode());
		result = 37 * result + (getImsBenf35() == null ? 0 : this.getImsBenf35().hashCode());
		result = 37 * result + (getImsDeduc1() == null ? 0 : this.getImsDeduc1().hashCode());
		result = 37 * result + (getImsDeduc2() == null ? 0 : this.getImsDeduc2().hashCode());
		result = 37 * result + (getImsDeduc3() == null ? 0 : this.getImsDeduc3().hashCode());
		result = 37 * result + (getImsBeni10() == null ? 0 : this.getImsBeni10().hashCode());
		result = 37 * result + (getImsBeni20() == null ? 0 : this.getImsBeni20().hashCode());
		result = 37 * result + (getImsBeni35() == null ? 0 : this.getImsBeni35().hashCode());
		result = 37 * result + (getImsImpodu() == null ? 0 : this.getImsImpodu().hashCode());
		result = 37 * result + (getImsMexean() == null ? 0 : this.getImsMexean().hashCode());
		result = 37 * result + (getImsMacpro() == null ? 0 : this.getImsMacpro().hashCode());
		result = 37 * result + (getImsMretso() == null ? 0 : this.getImsMretso().hashCode());
		result = 37 * result + (getImsRestit() == null ? 0 : this.getImsRestit().hashCode());
		result = 37 * result + (getImsMntpay() == null ? 0 : this.getImsMntpay().hashCode());
		result = 37 * result + (getImsReport() == null ? 0 : this.getImsReport().hashCode());
		result = 37 * result + (getImsBennso() == null ? 0 : this.getImsBennso().hashCode());
		result = 37 * result + (getImsTypdec() == null ? 0 : this.getImsTypdec().hashCode());
		return result;
	}

}
