package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aDecirp generated by hbm2java
 */
@Entity
@Table(name = "P3A_DECIRP")
public class P3aDecirp implements java.io.Serializable {

	private P3aDecirpId id;

	public P3aDecirp() {
	}

	public P3aDecirp(P3aDecirpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "irpExerci", column = @Column(name = "IRP_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "irpCatrev", column = @Column(name = "IRP_CATREV", length = 17)),
			@AttributeOverride(name = "irpRevbic", column = @Column(name = "IRP_REVBIC", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevbnc", column = @Column(name = "IRP_REVBNC", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevagr", column = @Column(name = "IRP_REVAGR", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevfon", column = @Column(name = "IRP_REVFON", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpTrtsal", column = @Column(name = "IRP_TRTSAL", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpPenvia", column = @Column(name = "IRP_PENVIA", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevmob", column = @Column(name = "IRP_REVMOB", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevcap", column = @Column(name = "IRP_REVCAP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevtrt", column = @Column(name = "IRP_REVTRT", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMntaba", column = @Column(name = "IRP_MNTABA", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpRevaut", column = @Column(name = "IRP_REVAUT", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpBenexp", column = @Column(name = "IRP_BENEXP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMdeduc", column = @Column(name = "IRP_MDEDUC", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpTotrev", column = @Column(name = "IRP_TOTREV", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpDedinv", column = @Column(name = "IRP_DEDINV", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpNetimp", column = @Column(name = "IRP_NETIMP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpTotimp", column = @Column(name = "IRP_TOTIMP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpExeant", column = @Column(name = "IRP_EXEANT", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMacpro", column = @Column(name = "IRP_MACPRO", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMretso", column = @Column(name = "IRP_MRETSO", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpAutded", column = @Column(name = "IRP_AUTDED", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMexone", column = @Column(name = "IRP_MEXONE", precision = 13, scale = 0)) })
	public P3aDecirpId getId() {
		return this.id;
	}

	public void setId(P3aDecirpId id) {
		this.id = id;
	}

}
