package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aDecird generated by hbm2java
 */
@Entity
@Table(name = "P3A_DECIRD")
public class P3aDecird implements java.io.Serializable {

	private P3aDecirdId id;

	public P3aDecird() {
	}

	public P3aDecird(P3aDecirdId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "irpExerci", column = @Column(name = "IRP_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "irpTyprev", column = @Column(name = "IRP_TYPREV", nullable = false, length = 2)),
			@AttributeOverride(name = "irpCafloc", column = @Column(name = "IRP_CAFLOC", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpCafexp", column = @Column(name = "IRP_CAFEXP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpCafttc", column = @Column(name = "IRP_CAFTTC", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMrescp", column = @Column(name = "IRP_MRESCP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpMresfi", column = @Column(name = "IRP_MRESFI", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpDedexp", column = @Column(name = "IRP_DEDEXP", precision = 13, scale = 0)),
			@AttributeOverride(name = "irpDedaut", column = @Column(name = "IRP_DEDAUT", precision = 13, scale = 0)) })
	public P3aDecirdId getId() {
		return this.id;
	}

	public void setId(P3aDecirdId id) {
		this.id = id;
	}

}
