package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aDecsoc generated by hbm2java
 */
@Entity
@Table(name = "P3A_DECSOC")
public class P3aDecsoc implements java.io.Serializable {

	private P3aDecsocId id;

	public P3aDecsoc() {
	}

	public P3aDecsoc(P3aDecsocId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "imsExerci", column = @Column(name = "IMS_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "imsTypsoc", column = @Column(name = "IMS_TYPSOC", length = 1)),
			@AttributeOverride(name = "imsStkdeb", column = @Column(name = "IMS_STKDEB", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsStkfin", column = @Column(name = "IMS_STKFIN", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsMachat", column = @Column(name = "IMS_MACHAT", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCafloc", column = @Column(name = "IMS_CAFLOC", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCafexp", column = @Column(name = "IMS_CAFEXP", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCaft10", column = @Column(name = "IMS_CAFT10", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCaft20", column = @Column(name = "IMS_CAFT20", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCaft35", column = @Column(name = "IMS_CAFT35", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCafttc", column = @Column(name = "IMS_CAFTTC", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCrescp", column = @Column(name = "IMS_CRESCP", length = 240)),
			@AttributeOverride(name = "imsMrescp", column = @Column(name = "IMS_MRESCP", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsCresfi", column = @Column(name = "IMS_CRESFI", length = 13)),
			@AttributeOverride(name = "imsMresfi", column = @Column(name = "IMS_MRESFI", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBenf10", column = @Column(name = "IMS_BENF10", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBenf20", column = @Column(name = "IMS_BENF20", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBenf35", column = @Column(name = "IMS_BENF35", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsDeduc1", column = @Column(name = "IMS_DEDUC1", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsDeduc2", column = @Column(name = "IMS_DEDUC2", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsDeduc3", column = @Column(name = "IMS_DEDUC3", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBeni10", column = @Column(name = "IMS_BENI10", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBeni20", column = @Column(name = "IMS_BENI20", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBeni35", column = @Column(name = "IMS_BENI35", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsImpodu", column = @Column(name = "IMS_IMPODU", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsMexean", column = @Column(name = "IMS_MEXEAN", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsMacpro", column = @Column(name = "IMS_MACPRO", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsMretso", column = @Column(name = "IMS_MRETSO", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsRestit", column = @Column(name = "IMS_RESTIT", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsMntpay", column = @Column(name = "IMS_MNTPAY", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsReport", column = @Column(name = "IMS_REPORT", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsBennso", column = @Column(name = "IMS_BENNSO", precision = 14, scale = 0)),
			@AttributeOverride(name = "imsTypdec", column = @Column(name = "IMS_TYPDEC", length = 2)) })
	public P3aDecsocId getId() {
		return this.id;
	}

	public void setId(P3aDecsocId id) {
		this.id = id;
	}

}
