package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aFrncpt generated by hbm2java
 */
@Entity
@Table(name = "P3A_FRNCPT")
public class P3aFrncpt implements java.io.Serializable {

	private P3aFrncptId id;

	public P3aFrncpt() {
	}

	public P3aFrncpt(P3aFrncptId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "fprNumero", column = @Column(name = "FPR_NUMERO", nullable = false, length = 14)),
			@AttributeOverride(name = "cptCodcpt", column = @Column(name = "CPT_CODCPT", nullable = false, length = 4)),
			@AttributeOverride(name = "cptLibell", column = @Column(name = "CPT_LIBELL", length = 120)),
			@AttributeOverride(name = "bilAnnees", column = @Column(name = "BIL_ANNEES", length = 4)),
			@AttributeOverride(name = "bilMntann", column = @Column(name = "BIL_MNTANN", precision = 16, scale = 3)) })
	public P3aFrncptId getId() {
		return this.id;
	}

	public void setId(P3aFrncptId id) {
		this.id = id;
	}

}
