package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aFrncptId generated by hbm2java
 */
@Embeddable
public class P3aFrncptId implements java.io.Serializable {

	private String ctrMatfis;
	private String ctrEtbsec;
	private String fprNumero;
	private String cptCodcpt;
	private String cptLibell;
	private String bilAnnees;
	private BigDecimal bilMntann;

	public P3aFrncptId() {
	}

	public P3aFrncptId(String ctrEtbsec, String fprNumero, String cptCodcpt) {
		this.ctrEtbsec = ctrEtbsec;
		this.fprNumero = fprNumero;
		this.cptCodcpt = cptCodcpt;
	}

	public P3aFrncptId(String ctrMatfis, String ctrEtbsec, String fprNumero, String cptCodcpt, String cptLibell,
			String bilAnnees, BigDecimal bilMntann) {
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.fprNumero = fprNumero;
		this.cptCodcpt = cptCodcpt;
		this.cptLibell = cptLibell;
		this.bilAnnees = bilAnnees;
		this.bilMntann = bilMntann;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "FPR_NUMERO", nullable = false, length = 14)
	public String getFprNumero() {
		return this.fprNumero;
	}

	public void setFprNumero(String fprNumero) {
		this.fprNumero = fprNumero;
	}

	@Column(name = "CPT_CODCPT", nullable = false, length = 4)
	public String getCptCodcpt() {
		return this.cptCodcpt;
	}

	public void setCptCodcpt(String cptCodcpt) {
		this.cptCodcpt = cptCodcpt;
	}

	@Column(name = "CPT_LIBELL", length = 120)
	public String getCptLibell() {
		return this.cptLibell;
	}

	public void setCptLibell(String cptLibell) {
		this.cptLibell = cptLibell;
	}

	@Column(name = "BIL_ANNEES", length = 4)
	public String getBilAnnees() {
		return this.bilAnnees;
	}

	public void setBilAnnees(String bilAnnees) {
		this.bilAnnees = bilAnnees;
	}

	@Column(name = "BIL_MNTANN", precision = 16, scale = 3)
	public BigDecimal getBilMntann() {
		return this.bilMntann;
	}

	public void setBilMntann(BigDecimal bilMntann) {
		this.bilMntann = bilMntann;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aFrncptId))
			return false;
		P3aFrncptId castOther = (P3aFrncptId) other;

		return ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
				&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getFprNumero() == castOther.getFprNumero()) || (this.getFprNumero() != null
						&& castOther.getFprNumero() != null && this.getFprNumero().equals(castOther.getFprNumero())))
				&& ((this.getCptCodcpt() == castOther.getCptCodcpt()) || (this.getCptCodcpt() != null
						&& castOther.getCptCodcpt() != null && this.getCptCodcpt().equals(castOther.getCptCodcpt())))
				&& ((this.getCptLibell() == castOther.getCptLibell()) || (this.getCptLibell() != null
						&& castOther.getCptLibell() != null && this.getCptLibell().equals(castOther.getCptLibell())))
				&& ((this.getBilAnnees() == castOther.getBilAnnees()) || (this.getBilAnnees() != null
						&& castOther.getBilAnnees() != null && this.getBilAnnees().equals(castOther.getBilAnnees())))
				&& ((this.getBilMntann() == castOther.getBilMntann()) || (this.getBilMntann() != null
						&& castOther.getBilMntann() != null && this.getBilMntann().equals(castOther.getBilMntann())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getFprNumero() == null ? 0 : this.getFprNumero().hashCode());
		result = 37 * result + (getCptCodcpt() == null ? 0 : this.getCptCodcpt().hashCode());
		result = 37 * result + (getCptLibell() == null ? 0 : this.getCptLibell().hashCode());
		result = 37 * result + (getBilAnnees() == null ? 0 : this.getBilAnnees().hashCode());
		result = 37 * result + (getBilMntann() == null ? 0 : this.getBilMntann().hashCode());
		return result;
	}

}
