package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aMotctr generated by hbm2java
 */
@Entity
@Table(name = "P3A_MOTCTR")
public class P3aMotctr implements java.io.Serializable {

	private P3aMotctrId id;

	public P3aMotctr() {
	}

	public P3aMotctr(P3aMotctrId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "prvIdprog", column = @Column(name = "PRV_IDPROG", length = 11)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", length = 3)),
			@AttributeOverride(name = "mvrCodmot", column = @Column(name = "MVR_CODMOT", length = 4)),
			@AttributeOverride(name = "mvrLibmot", column = @Column(name = "MVR_LIBMOT", length = 125)) })
	public P3aMotctrId getId() {
		return this.id;
	}

	public void setId(P3aMotctrId id) {
		this.id = id;
	}

}
