package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * P3aResvapId generated by hbm2java
 */
@Embeddable
public class P3aResvapId implements java.io.Serializable {

	private String prvIdprog;
	private String ctrMatfis;
	private String ctrEtbsec;
	private String vapFinvap;
	private String impCodimp;
	private String impLibimp;
	private Long vapMntred;

	public P3aResvapId() {
	}

	public P3aResvapId(String prvIdprog, String ctrMatfis, String ctrEtbsec, String vapFinvap, String impCodimp,
			String impLibimp, Long vapMntred) {
		this.prvIdprog = prvIdprog;
		this.ctrMatfis = ctrMatfis;
		this.ctrEtbsec = ctrEtbsec;
		this.vapFinvap = vapFinvap;
		this.impCodimp = impCodimp;
		this.impLibimp = impLibimp;
		this.vapMntred = vapMntred;
	}

	@Column(name = "PRV_IDPROG", length = 11)
	public String getPrvIdprog() {
		return this.prvIdprog;
	}

	public void setPrvIdprog(String prvIdprog) {
		this.prvIdprog = prvIdprog;
	}

	@Column(name = "CTR_MATFIS", length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_ETBSEC", length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "VAP_FINVAP", length = 4)
	public String getVapFinvap() {
		return this.vapFinvap;
	}

	public void setVapFinvap(String vapFinvap) {
		this.vapFinvap = vapFinvap;
	}

	@Column(name = "IMP_CODIMP", length = 9)
	public String getImpCodimp() {
		return this.impCodimp;
	}

	public void setImpCodimp(String impCodimp) {
		this.impCodimp = impCodimp;
	}

	@Column(name = "IMP_LIBIMP", length = 60)
	public String getImpLibimp() {
		return this.impLibimp;
	}

	public void setImpLibimp(String impLibimp) {
		this.impLibimp = impLibimp;
	}

	@Column(name = "VAP_MNTRED", precision = 15, scale = 0)
	public Long getVapMntred() {
		return this.vapMntred;
	}

	public void setVapMntred(Long vapMntred) {
		this.vapMntred = vapMntred;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof P3aResvapId))
			return false;
		P3aResvapId castOther = (P3aResvapId) other;

		return ((this.getPrvIdprog() == castOther.getPrvIdprog()) || (this.getPrvIdprog() != null
				&& castOther.getPrvIdprog() != null && this.getPrvIdprog().equals(castOther.getPrvIdprog())))
				&& ((this.getCtrMatfis() == castOther.getCtrMatfis()) || (this.getCtrMatfis() != null
						&& castOther.getCtrMatfis() != null && this.getCtrMatfis().equals(castOther.getCtrMatfis())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& ((this.getVapFinvap() == castOther.getVapFinvap()) || (this.getVapFinvap() != null
						&& castOther.getVapFinvap() != null && this.getVapFinvap().equals(castOther.getVapFinvap())))
				&& ((this.getImpCodimp() == castOther.getImpCodimp()) || (this.getImpCodimp() != null
						&& castOther.getImpCodimp() != null && this.getImpCodimp().equals(castOther.getImpCodimp())))
				&& ((this.getImpLibimp() == castOther.getImpLibimp()) || (this.getImpLibimp() != null
						&& castOther.getImpLibimp() != null && this.getImpLibimp().equals(castOther.getImpLibimp())))
				&& ((this.getVapMntred() == castOther.getVapMntred()) || (this.getVapMntred() != null
						&& castOther.getVapMntred() != null && this.getVapMntred().equals(castOther.getVapMntred())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPrvIdprog() == null ? 0 : this.getPrvIdprog().hashCode());
		result = 37 * result + (getCtrMatfis() == null ? 0 : this.getCtrMatfis().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + (getVapFinvap() == null ? 0 : this.getVapFinvap().hashCode());
		result = 37 * result + (getImpCodimp() == null ? 0 : this.getImpCodimp().hashCode());
		result = 37 * result + (getImpLibimp() == null ? 0 : this.getImpLibimp().hashCode());
		result = 37 * result + (getVapMntred() == null ? 0 : this.getVapMntred().hashCode());
		return result;
	}

}
