package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aResvap generated by hbm2java
 */
@Entity
@Table(name = "P3A_RESVAP")
public class P3aResvap implements java.io.Serializable {

	private P3aResvapId id;

	public P3aResvap() {
	}

	public P3aResvap(P3aResvapId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "prvIdprog", column = @Column(name = "PRV_IDPROG", length = 11)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", length = 3)),
			@AttributeOverride(name = "vapFinvap", column = @Column(name = "VAP_FINVAP", length = 4)),
			@AttributeOverride(name = "impCodimp", column = @Column(name = "IMP_CODIMP", length = 9)),
			@AttributeOverride(name = "impLibimp", column = @Column(name = "IMP_LIBIMP", length = 60)),
			@AttributeOverride(name = "vapMntred", column = @Column(name = "VAP_MNTRED", precision = 15, scale = 0)) })
	public P3aResvapId getId() {
		return this.id;
	}

	public void setId(P3aResvapId id) {
		this.id = id;
	}

}
