package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * P3aSitfis generated by hbm2java
 */
@Entity
@Table(name = "P3A_SITFIS")
public class P3aSitfis implements java.io.Serializable {

	private P3aSitfisId id;

	public P3aSitfis() {
	}

	public P3aSitfis(P3aSitfisId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sitExerci", column = @Column(name = "SIT_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "oblCodobl", column = @Column(name = "OBL_CODOBL", length = 2)),
			@AttributeOverride(name = "oblLibell", column = @Column(name = "OBL_LIBELL", length = 240)),
			@AttributeOverride(name = "sitDefdep", column = @Column(name = "SIT_DEFDEP", length = 12)) })
	public P3aSitfisId getId() {
		return this.id;
	}

	public void setId(P3aSitfisId id) {
		this.id = id;
	}

}
