package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pactagr generated by hbm2java
 */
@Entity
@Table(name = "PACTAGR")
public class Pactagr implements java.io.Serializable {

	private PactagrId id;

	public Pactagr() {
	}

	public Pactagr(PactagrId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "agrAnnact", column = @Column(name = "AGR_ANNACT")),
			@AttributeOverride(name = "actQallib", column = @Column(name = "ACT_QALLIB")),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS")),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC")),
			@AttributeOverride(name = "agrMntbin", column = @Column(name = "AGR_MNTBIN")) })
	public PactagrId getId() {
		return this.id;
	}

	public void setId(PactagrId id) {
		this.id = id;
	}

}
