package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Param generated by hbm2java
 */
@Entity
@Table(name = "PARAM")
public class Param implements java.io.Serializable {

	private Short crityear;

	public Param() {
	}

	public Param(Short crityear) {
		this.crityear = crityear;
	}

	@Id

	@Column(name = "CRITYEAR", precision = 4, scale = 0)
	public Short getCrityear() {
		return this.crityear;
	}

	public void setCrityear(Short crityear) {
		this.crityear = crityear;
	}

}
