package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Selectionscores generated by hbm2java
 */
@Entity
@Table(name = "SELECTIONSCORES")
public class Selectionscores implements java.io.Serializable {

	private SelectionscoresId id;

	public Selectionscores() {
	}

	public Selectionscores(SelectionscoresId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "crityear", column = @Column(name = "CRITYEAR", precision = 4, scale = 0)),
			@AttributeOverride(name = "actsec", column = @Column(name = "ACTSEC", length = 4)),
			@AttributeOverride(name = "actLibell", column = @Column(name = "ACT_LIBELL", length = 120)),
			@AttributeOverride(name = "tocat", column = @Column(name = "TOCAT", precision = 22, scale = 0)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, length = 8)),
			@AttributeOverride(name = "ctrRaison", column = @Column(name = "CTR_RAISON", length = 120)),
			@AttributeOverride(name = "gpscore", column = @Column(name = "GPSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "npscore", column = @Column(name = "NPSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "wagescore", column = @Column(name = "WAGESCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "xrefvattoscore", column = @Column(name = "XREFVATTOSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "vatcredscore", column = @Column(name = "VATCREDSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "conseclossscore", column = @Column(name = "CONSECLOSSSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "xrefimportscore", column = @Column(name = "XREFIMPORTSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "incdefaultscore", column = @Column(name = "INCDEFAULTSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "vatdefaultscore", column = @Column(name = "VATDEFAULTSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "noauditscore", column = @Column(name = "NOAUDITSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "exportdeductscore", column = @Column(name = "EXPORTDEDUCTSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "zerotoscore", column = @Column(name = "ZEROTOSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "rentreportscore", column = @Column(name = "RENTREPORTSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "vatdecdefscore", column = @Column(name = "VATDECDEFSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "audpayscore", column = @Column(name = "AUDPAYSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "exportbenescore", column = @Column(name = "EXPORTBENESCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "salefiscalscore", column = @Column(name = "SALEFISCALSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "cashmoretoscore", column = @Column(name = "CASHMORETOSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "acctfiscalscore", column = @Column(name = "ACCTFISCALSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "advtotaltoscore", column = @Column(name = "ADVTOTALTOSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "caftotclscore", column = @Column(name = "CAFTOTCLSCORE", precision = 22, scale = 0)),
			@AttributeOverride(name = "totalscore", column = @Column(name = "TOTALSCORE", precision = 22, scale = 0)) })
	public SelectionscoresId getId() {
		return this.id;
	}

	public void setId(SelectionscoresId id) {
		this.id = id;
	}

}
