package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Sitfis generated by hbm2java
 */
@Entity
@Table(name = "SITFIS")
public class Sitfis implements java.io.Serializable {

	private SitfisId id;

	public Sitfis() {
	}

	public Sitfis(SitfisId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sitExerci", column = @Column(name = "SIT_EXERCI", nullable = false, length = 4)),
			@AttributeOverride(name = "sitSitfis", column = @Column(name = "SIT_SITFIS", nullable = false, length = 1)),
			@AttributeOverride(name = "sitRevenu", column = @Column(name = "SIT_REVENU", nullable = false, precision = 13, scale = 0)),
			@AttributeOverride(name = "sitBenefi", column = @Column(name = "SIT_BENEFI", nullable = false, precision = 13, scale = 0)),
			@AttributeOverride(name = "prvIdprog", column = @Column(name = "PRV_IDPROG", nullable = false, length = 8)),
			@AttributeOverride(name = "prvCodcen", column = @Column(name = "PRV_CODCEN", nullable = false, length = 3)),
			@AttributeOverride(name = "ctrTypctr", column = @Column(name = "CTR_TYPCTR", nullable = false, length = 1)),
			@AttributeOverride(name = "ctrMatfis", column = @Column(name = "CTR_MATFIS", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "ctrMatcle", column = @Column(name = "CTR_MATCLE", nullable = false, length = 1)),
			@AttributeOverride(name = "ctrCatego", column = @Column(name = "CTR_CATEGO", nullable = false, length = 1)),
			@AttributeOverride(name = "ctrEtbsec", column = @Column(name = "CTR_ETBSEC", nullable = false, length = 3)),
			@AttributeOverride(name = "ctrNumcin", column = @Column(name = "CTR_NUMCIN", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "lpvNumord", column = @Column(name = "LPV_NUMORD", precision = 3, scale = 0)) })
	public SitfisId getId() {
		return this.id;
	}

	public void setId(SitfisId id) {
		this.id = id;
	}

}
