package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SitfisId generated by hbm2java
 */
@Embeddable
public class SitfisId implements java.io.Serializable {

	private String sitExerci;
	private String sitSitfis;
	private long sitRevenu;
	private long sitBenefi;
	private String prvIdprog;
	private String prvCodcen;
	private String ctrTypctr;
	private int ctrMatfis;
	private String ctrMatcle;
	private String ctrCatego;
	private String ctrEtbsec;
	private int ctrNumcin;
	private Short lpvNumord;

	public SitfisId() {
	}

	public SitfisId(String sitExerci, String sitSitfis, long sitRevenu, long sitBenefi, String prvIdprog,
			String prvCodcen, String ctrTypctr, int ctrMatfis, String ctrMatcle, String ctrCatego, String ctrEtbsec,
			int ctrNumcin) {
		this.sitExerci = sitExerci;
		this.sitSitfis = sitSitfis;
		this.sitRevenu = sitRevenu;
		this.sitBenefi = sitBenefi;
		this.prvIdprog = prvIdprog;
		this.prvCodcen = prvCodcen;
		this.ctrTypctr = ctrTypctr;
		this.ctrMatfis = ctrMatfis;
		this.ctrMatcle = ctrMatcle;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.ctrNumcin = ctrNumcin;
	}

	public SitfisId(String sitExerci, String sitSitfis, long sitRevenu, long sitBenefi, String prvIdprog,
			String prvCodcen, String ctrTypctr, int ctrMatfis, String ctrMatcle, String ctrCatego, String ctrEtbsec,
			int ctrNumcin, Short lpvNumord) {
		this.sitExerci = sitExerci;
		this.sitSitfis = sitSitfis;
		this.sitRevenu = sitRevenu;
		this.sitBenefi = sitBenefi;
		this.prvIdprog = prvIdprog;
		this.prvCodcen = prvCodcen;
		this.ctrTypctr = ctrTypctr;
		this.ctrMatfis = ctrMatfis;
		this.ctrMatcle = ctrMatcle;
		this.ctrCatego = ctrCatego;
		this.ctrEtbsec = ctrEtbsec;
		this.ctrNumcin = ctrNumcin;
		this.lpvNumord = lpvNumord;
	}

	@Column(name = "SIT_EXERCI", nullable = false, length = 4)
	public String getSitExerci() {
		return this.sitExerci;
	}

	public void setSitExerci(String sitExerci) {
		this.sitExerci = sitExerci;
	}

	@Column(name = "SIT_SITFIS", nullable = false, length = 1)
	public String getSitSitfis() {
		return this.sitSitfis;
	}

	public void setSitSitfis(String sitSitfis) {
		this.sitSitfis = sitSitfis;
	}

	@Column(name = "SIT_REVENU", nullable = false, precision = 13, scale = 0)
	public long getSitRevenu() {
		return this.sitRevenu;
	}

	public void setSitRevenu(long sitRevenu) {
		this.sitRevenu = sitRevenu;
	}

	@Column(name = "SIT_BENEFI", nullable = false, precision = 13, scale = 0)
	public long getSitBenefi() {
		return this.sitBenefi;
	}

	public void setSitBenefi(long sitBenefi) {
		this.sitBenefi = sitBenefi;
	}

	@Column(name = "PRV_IDPROG", nullable = false, length = 8)
	public String getPrvIdprog() {
		return this.prvIdprog;
	}

	public void setPrvIdprog(String prvIdprog) {
		this.prvIdprog = prvIdprog;
	}

	@Column(name = "PRV_CODCEN", nullable = false, length = 3)
	public String getPrvCodcen() {
		return this.prvCodcen;
	}

	public void setPrvCodcen(String prvCodcen) {
		this.prvCodcen = prvCodcen;
	}

	@Column(name = "CTR_TYPCTR", nullable = false, length = 1)
	public String getCtrTypctr() {
		return this.ctrTypctr;
	}

	public void setCtrTypctr(String ctrTypctr) {
		this.ctrTypctr = ctrTypctr;
	}

	@Column(name = "CTR_MATFIS", nullable = false, precision = 7, scale = 0)
	public int getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(int ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_MATCLE", nullable = false, length = 1)
	public String getCtrMatcle() {
		return this.ctrMatcle;
	}

	public void setCtrMatcle(String ctrMatcle) {
		this.ctrMatcle = ctrMatcle;
	}

	@Column(name = "CTR_CATEGO", nullable = false, length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "CTR_ETBSEC", nullable = false, length = 3)
	public String getCtrEtbsec() {
		return this.ctrEtbsec;
	}

	public void setCtrEtbsec(String ctrEtbsec) {
		this.ctrEtbsec = ctrEtbsec;
	}

	@Column(name = "CTR_NUMCIN", nullable = false, precision = 8, scale = 0)
	public int getCtrNumcin() {
		return this.ctrNumcin;
	}

	public void setCtrNumcin(int ctrNumcin) {
		this.ctrNumcin = ctrNumcin;
	}

	@Column(name = "LPV_NUMORD", precision = 3, scale = 0)
	public Short getLpvNumord() {
		return this.lpvNumord;
	}

	public void setLpvNumord(Short lpvNumord) {
		this.lpvNumord = lpvNumord;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SitfisId))
			return false;
		SitfisId castOther = (SitfisId) other;

		return ((this.getSitExerci() == castOther.getSitExerci()) || (this.getSitExerci() != null
				&& castOther.getSitExerci() != null && this.getSitExerci().equals(castOther.getSitExerci())))
				&& ((this.getSitSitfis() == castOther.getSitSitfis()) || (this.getSitSitfis() != null
						&& castOther.getSitSitfis() != null && this.getSitSitfis().equals(castOther.getSitSitfis())))
				&& (this.getSitRevenu() == castOther.getSitRevenu())
				&& (this.getSitBenefi() == castOther.getSitBenefi())
				&& ((this.getPrvIdprog() == castOther.getPrvIdprog()) || (this.getPrvIdprog() != null
						&& castOther.getPrvIdprog() != null && this.getPrvIdprog().equals(castOther.getPrvIdprog())))
				&& ((this.getPrvCodcen() == castOther.getPrvCodcen()) || (this.getPrvCodcen() != null
						&& castOther.getPrvCodcen() != null && this.getPrvCodcen().equals(castOther.getPrvCodcen())))
				&& ((this.getCtrTypctr() == castOther.getCtrTypctr()) || (this.getCtrTypctr() != null
						&& castOther.getCtrTypctr() != null && this.getCtrTypctr().equals(castOther.getCtrTypctr())))
				&& (this.getCtrMatfis() == castOther.getCtrMatfis())
				&& ((this.getCtrMatcle() == castOther.getCtrMatcle()) || (this.getCtrMatcle() != null
						&& castOther.getCtrMatcle() != null && this.getCtrMatcle().equals(castOther.getCtrMatcle())))
				&& ((this.getCtrCatego() == castOther.getCtrCatego()) || (this.getCtrCatego() != null
						&& castOther.getCtrCatego() != null && this.getCtrCatego().equals(castOther.getCtrCatego())))
				&& ((this.getCtrEtbsec() == castOther.getCtrEtbsec()) || (this.getCtrEtbsec() != null
						&& castOther.getCtrEtbsec() != null && this.getCtrEtbsec().equals(castOther.getCtrEtbsec())))
				&& (this.getCtrNumcin() == castOther.getCtrNumcin())
				&& ((this.getLpvNumord() == castOther.getLpvNumord()) || (this.getLpvNumord() != null
						&& castOther.getLpvNumord() != null && this.getLpvNumord().equals(castOther.getLpvNumord())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSitExerci() == null ? 0 : this.getSitExerci().hashCode());
		result = 37 * result + (getSitSitfis() == null ? 0 : this.getSitSitfis().hashCode());
		result = 37 * result + (int) this.getSitRevenu();
		result = 37 * result + (int) this.getSitBenefi();
		result = 37 * result + (getPrvIdprog() == null ? 0 : this.getPrvIdprog().hashCode());
		result = 37 * result + (getPrvCodcen() == null ? 0 : this.getPrvCodcen().hashCode());
		result = 37 * result + (getCtrTypctr() == null ? 0 : this.getCtrTypctr().hashCode());
		result = 37 * result + this.getCtrMatfis();
		result = 37 * result + (getCtrMatcle() == null ? 0 : this.getCtrMatcle().hashCode());
		result = 37 * result + (getCtrCatego() == null ? 0 : this.getCtrCatego().hashCode());
		result = 37 * result + (getCtrEtbsec() == null ? 0 : this.getCtrEtbsec().hashCode());
		result = 37 * result + this.getCtrNumcin();
		result = 37 * result + (getLpvNumord() == null ? 0 : this.getLpvNumord().hashCode());
		return result;
	}

}
