package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TempSelectScores generated by hbm2java
 */
@Entity
@Table(name = "TEMP_SELECT_SCORES")
public class TempSelectScores implements java.io.Serializable {

	private Short taxYear;
	private BigDecimal criteriaId;
	private String ctrMatfis;
	private BigDecimal score;
	private BigDecimal id;
	public Short getTaxYear() {
		return taxYear;
	}
	public void setTaxYear(Short taxYear) {
		this.taxYear = taxYear;
	}
	public BigDecimal getCriteriaId() {
		return criteriaId;
	}
	public void setCriteriaId(BigDecimal criteriaId) {
		this.criteriaId = criteriaId;
	}
	
	public String getCtrMatfis() {
		return ctrMatfis;
	}
	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}
	public BigDecimal getScore() {
		return score;
	}
	public void setScore(BigDecimal score) {
		this.score = score;
	}
	
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator ="TEMP_SELECT_SCORES_SEQ1" )
	@SequenceGenerator(name="TEMP_SELECT_SCORES_SEQ1", sequenceName="TEMP_SELECT_SCORES_SEQ1", allocationSize=1)
	public BigDecimal getId() {
		return id;
	}
	public void setId(BigDecimal id) {
		this.id = id;
	}

}
