package esprit.projet.persistance.model;
// Generated 4 sept. 2020 01:10:18 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tpcategory generated by hbm2java
 */
@Entity
@Table(name = "TPCATEGORY",schema = "p3arisk")

public class Tpcategory implements java.io.Serializable {

	private String ctrMatfis;
	private String ctrRaison;
	private Date ctrDatouv;
	private String actsec;
	private String actLibell;
	private String ctrCatego;
	private BigDecimal turnover;
	private BigDecimal tocat;
	private Short crityear;

	public Tpcategory() {
	}

	public Tpcategory(String ctrMatfis, String ctrRaison) {
		this.ctrMatfis = ctrMatfis;
		this.ctrRaison = ctrRaison;
	}

	public Tpcategory(String ctrMatfis, String ctrRaison, Date ctrDatouv, String actsec, String actLibell,
			String ctrCatego, BigDecimal turnover, BigDecimal tocat, Short crityear) {
		this.ctrMatfis = ctrMatfis;
		this.ctrRaison = ctrRaison;
		this.ctrDatouv = ctrDatouv;
		this.actsec = actsec;
		this.actLibell = actLibell;
		this.ctrCatego = ctrCatego;
		this.turnover = turnover;
		this.tocat = tocat;
		this.crityear = crityear;
	}

	@Id

	@Column(name = "CTR_MATFIS", nullable = false, length = 8)
	public String getCtrMatfis() {
		return this.ctrMatfis;
	}

	public void setCtrMatfis(String ctrMatfis) {
		this.ctrMatfis = ctrMatfis;
	}

	@Column(name = "CTR_RAISON", nullable = false, length = 120)
	public String getCtrRaison() {
		return this.ctrRaison;
	}

	public void setCtrRaison(String ctrRaison) {
		this.ctrRaison = ctrRaison;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTR_DATOUV", length = 7)
	public Date getCtrDatouv() {
		return this.ctrDatouv;
	}

	public void setCtrDatouv(Date ctrDatouv) {
		this.ctrDatouv = ctrDatouv;
	}

	@Column(name = "ACTSEC", length = 4)
	public String getActsec() {
		return this.actsec;
	}

	public void setActsec(String actsec) {
		this.actsec = actsec;
	}

	@Column(name = "ACT_LIBELL", length = 120)
	public String getActLibell() {
		return this.actLibell;
	}

	public void setActLibell(String actLibell) {
		this.actLibell = actLibell;
	}

	@Column(name = "CTR_CATEGO", length = 1)
	public String getCtrCatego() {
		return this.ctrCatego;
	}

	public void setCtrCatego(String ctrCatego) {
		this.ctrCatego = ctrCatego;
	}

	@Column(name = "TURNOVER", precision = 22, scale = 0)
	public BigDecimal getTurnover() {
		return this.turnover;
	}

	public void setTurnover(BigDecimal turnover) {
		this.turnover = turnover;
	}

	@Column(name = "TOCAT", precision = 22, scale = 0)
	public BigDecimal getTocat() {
		return this.tocat;
	}

	public void setTocat(BigDecimal tocat) {
		this.tocat = tocat;
	}

	@Column(name = "CRITYEAR", precision = 4, scale = 0)
	public Short getCrityear() {
		return this.crityear;
	}

	public void setCrityear(Short crityear) {
		this.crityear = crityear;
	}

}
