package esprit.projet.persistance.model;
// Generated 30 ao�t 2020 13:08:24 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ValoblId generated by hbm2java
 */
@Embeddable
public class ValoblId implements java.io.Serializable {

	private String oblValobl;
	private String oblCodobl;

	public ValoblId() {
	}

	public ValoblId(String oblValobl, String oblCodobl) {
		this.oblValobl = oblValobl;
		this.oblCodobl = oblCodobl;
	}

	@Column(name = "OBL_VALOBL", nullable = false, length = 1)
	public String getOblValobl() {
		return this.oblValobl;
	}

	public void setOblValobl(String oblValobl) {
		this.oblValobl = oblValobl;
	}

	@Column(name = "OBL_CODOBL", nullable = false, length = 2)
	public String getOblCodobl() {
		return this.oblCodobl;
	}

	public void setOblCodobl(String oblCodobl) {
		this.oblCodobl = oblCodobl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValoblId))
			return false;
		ValoblId castOther = (ValoblId) other;

		return ((this.getOblValobl() == castOther.getOblValobl()) || (this.getOblValobl() != null
				&& castOther.getOblValobl() != null && this.getOblValobl().equals(castOther.getOblValobl())))
				&& ((this.getOblCodobl() == castOther.getOblCodobl()) || (this.getOblCodobl() != null
						&& castOther.getOblCodobl() != null && this.getOblCodobl().equals(castOther.getOblCodobl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOblValobl() == null ? 0 : this.getOblValobl().hashCode());
		result = 37 * result + (getOblCodobl() == null ? 0 : this.getOblCodobl().hashCode());
		return result;
	}

}
